#### Import dependencies

In [44]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams,Prefetch,PayloadFieldSchema,PointStruct,MatchAny,FieldCondition,Filter,PayloadSchemaType
import pandas as pd 
import numpy as np 
import json
import tiktoken

### Retrive all item from qdrant Collection

In [3]:
qdrant_client=QdrantClient(url="http://localhost:6333")

In [4]:
dummy_vector=np.zeros(1536).tolist()

In [5]:
payload=qdrant_client.query_points(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    query=dummy_vector,
    using="text-embedding-model-3-small",
    limit=1000,
    with_payload=['parent_asin'],
    with_vectors=False
)

In [6]:
payload

QueryResponse(points=[ScoredPoint(id=400, version=1, score=0.0, payload={'parent_asin': 'B09QGP16MY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=497, version=1, score=0.0, payload={'parent_asin': 'B0B8P44G8M'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=297, version=1, score=0.0, payload={'parent_asin': 'B0BXRSFB93'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=364, version=1, score=0.0, payload={'parent_asin': 'B0BYKDMMVJ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=124, version=1, score=0.0, payload={'parent_asin': 'B0BS3V1QBY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=346, version=1, score=0.0, payload={'parent_asin': 'B0BL2HJ8WS'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=143, version=1, score=0.0, payload={'parent_asin': 'B0BMXG42VN'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=44, version=1, score=0.0, payload={'parent_asin': 'B0BLCMRKR4'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=198, version=1, score=0.0, payload={'parent_asin': 'B0C6QS154C'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=308, version=1, score=0.0, payload={'parent_asin': 'B0BZQ5YKKY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=428, version=1, score=0.0, payload={'parent_asin': 'B0C27X5VJD'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=181, version=1, score=0.0, payload={'parent_asin': 'B0BM71PJQ9'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=226, version=1, score=0.0, payload={'parent_asin': 'B08WQ55H4Y'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=288, version=1, score=0.0, payload={'parent_asin': 'B0BSFCQWLG'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=455, version=1, score=0.0, payload={'parent_asin': 'B0BCKCJQPN'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=121, version=1, score=0.0, payload={'parent_asin': 'B0C6PGF8BV'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=321, version=1, score=0.0, payload={'parent_asin': 'B0B1TB2J5S'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=99, version=1, score=0.0, payload={'parent_asin': 'B0B6J4Y4QX'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=287, version=1, score=0.0, payload={'parent_asin': 'B0BT6SCPW7'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=84, version=1, score=0.0, payload={'parent_asin': 'B09WVHZ4X8'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=466, version=1, score=0.0, payload={'parent_asin': 'B0BGPPX7DC'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=304, version=1, score=0.0, payload={'parent_asin': 'B0BY2BBDS9'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=292, version=1, score=0.0, payload={'parent_asin': 'B0BR8NKQ12'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=385, version=1, score=0.0, payload={'parent_asin': 'B09X5HVNFL'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=131, version=1, score=0.0, payload={'parent_asin': 'B09W22V8XJ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=186, version=1, score=0.0, payload={'parent_asin': 'B0BJZV7QVF'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=71, version=1, score=0.0, payload={'parent_asin': 'B09PQ97H3G'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=135, version=1, score=0.0, payload={'parent_asin': 'B0B24PHF8M'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=42, version=1, score=0.0, payload={'parent_asin': 'B0B31H2TBX'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=323, version=1, score=0.0, payload={'parent_asin': 'B0BRHBQ92D'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=294, version=1, score=0.0, payload={'parent_asin': 'B09Q88GR4K'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=336, version=1, score=0.0, payload={'parent_asin': 'B0CGJDBNPJ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=38, version=1, score=0.0, payload={'parent_asin': 'B09YHWCNCH'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=424, version=1, score=0.0, payload={'parent_asin': 'B09LH466KZ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=192, version=1, score=0.0, payload={'parent_asin': 'B0CBBBTY2C'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=282, version=1, score=0.0, payload={'parent_asin': 'B0C772GZRF'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=258, version=1, score=0.0, payload={'parent_asin': 'B09T5YML6T'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=46, version=1, score=0.0, payload={'parent_asin': 'B09R6STLP7'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=59, version=1, score=0.0, payload={'parent_asin': 'B0BDZY67PK'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=463, version=1, score=0.0, payload={'parent_asin': 'B0BTYQ7VVM'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=314, version=1, score=0.0, payload={'parent_asin': 'B0B2W9G1M8'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=234, version=1, score=0.0, payload={'parent_asin': 'B0B77CJD7T'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=351, version=1, score=0.0, payload={'parent_asin': 'B0B4N1D73R'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=110, version=1, score=0.0, payload={'parent_asin': 'B0BMG766L1'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=247, version=1, score=0.0, payload={'parent_asin': 'B0B9HVFZD5'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=474, version=1, score=0.0, payload={'parent_asin': 'B09XQGN52P'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=12, version=1, score=0.0, payload={'parent_asin': 'B0C2C87FW3'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=127, version=1, score=0.0, payload={'parent_asin': 'B09W5STB6T'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=144, version=1, score=0.0, payload={'parent_asin': 'B09DKGPST6'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=213, version=1, score=0.0, payload={'parent_asin': 'B0BF4STLSR'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=339, version=1, score=0.0, payload={'parent_asin': 'B09B9MSWL3'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=109, version=1, score=0.0, payload={'parent_asin': 'B09Q5M5W8R'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=191, version=1, score=0.0, payload={'parent_asin': 'B0B5LJ2L26'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=236, version=1, score=0.0, payload={'parent_asin': 'B0BR8Q2PXN'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=270, version=1, score=0.0, payload={'parent_asin': 'B0B27Y4J4V'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=312, version=1, score=0.0, payload={'parent_asin': 'B08V8R6JML'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=352, version=1, score=0.0, payload={'parent_asin': 'B0C16S18PX'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=122, version=1, score=0.0, payload={'parent_asin': 'B0BQ6M5ZLQ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=202, version=1, score=0.0, payload={'parent_asin': 'B0B6Z2978H'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=235, version=1, score=0.0, payload={'parent_asin': 'B0B7NMSTT9'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=375, version=1, score=0.0, payload={'parent_asin': 'B09T6N7GTR'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=356, version=1, score=0.0, payload={'parent_asin': 'B0BWDRP69M'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=996, version=2, score=0.0, payload={'parent_asin': 'B0C7RF6YTR'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=784, version=2, score=0.0, payload={'parent_asin': 'B0B3T848VM'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=572, version=2, score=0.0, payload={'parent_asin': 'B0BJKGFB7R'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=800, version=2, score=0.0, payload={'parent_asin': 'B0C4GW8CCC'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=685, version=2, score=0.0, payload={'parent_asin': 'B0B4P3W9VJ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=805, version=2, score=0.0, payload={'parent_asin': 'B0C2YR4WXM'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=607, version=2, score=0.0, payload={'parent_asin': 'B0B778L1DZ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=690, version=2, score=0.0, payload={'parent_asin': 'B09ZL3PXF2'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=820, version=2, score=0.0, payload={'parent_asin': 'B0CCTZ65CC'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=873, version=2, score=0.0, payload={'parent_asin': 'B0BK957165'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=923, version=2, score=0.0, payload={'parent_asin': 'B0C1NDPD5L'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=945, version=2, score=0.0, payload={'parent_asin': 'B0BV276QMH'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=997, version=2, score=0.0, payload={'parent_asin': 'B09PV2HYB3'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=770, version=2, score=0.0, payload={'parent_asin': 'B09W2D4VM3'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=742, version=2, score=0.0, payload={'parent_asin': 'B0C3XYD574'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=511, version=2, score=0.0, payload={'parent_asin': 'B0B5115YWR'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=631, version=2, score=0.0, payload={'parent_asin': 'B0C5HKTYVC'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=907, version=2, score=0.0, payload={'parent_asin': 'B0C6FDCK21'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=900, version=2, score=0.0, payload={'parent_asin': 'B0BNN776VN'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=910, version=2, score=0.0, payload={'parent_asin': 'B0CGR9GYFT'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=723, version=2, score=0.0, payload={'parent_asin': 'B0BSGDCVND'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=848, version=2, score=0.0, payload={'parent_asin': 'B0BMG7VRY8'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=519, version=2, score=0.0, payload={'parent_asin': 'B0CD43HNTS'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=696, version=2, score=0.0, payload={'parent_asin': 'B0BKQCC73S'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=808, version=2, score=0.0, payload={'parent_asin': 'B0BCF5DLWV'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=862, version=2, score=0.0, payload={'parent_asin': 'B0B5XSXRK3'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=886, version=2, score=0.0, payload={'parent_asin': 'B0C64SQ23S'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=955, version=2, score=0.0, payload={'parent_asin': 'B0891ND31G'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=976, version=2, score=0.0, payload={'parent_asin': 'B09TR8VXGL'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=564, version=2, score=0.0, payload={'parent_asin': 'B0B4PWTZTC'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=889, version=2, score=0.0, payload={'parent_asin': 'B0B2VSLMHR'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=918, version=2, score=0.0, payload={'parent_asin': 'B0B6PKDSMN'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=913, version=2, score=0.0, payload={'parent_asin': 'B0BHLD7QW8'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=998, version=2, score=0.0, payload={'parent_asin': 'B0BMQDTQJL'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=537, version=2, score=0.0, payload={'parent_asin': 'B0BMM5QQST'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=536, version=2, score=0.0, payload={'parent_asin': 'B0B7DJ6ZZ4'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=540, version=2, score=0.0, payload={'parent_asin': 'B0B8NCR19L'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=850, version=2, score=0.0, payload={'parent_asin': 'B0B4V7XW21'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=968, version=2, score=0.0, payload={'parent_asin': 'B08NW1RXPF'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=702, version=2, score=0.0, payload={'parent_asin': 'B09ZTG58W5'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=842, version=2, score=0.0, payload={'parent_asin': 'B0BFCBMG7S'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=623, version=2, score=0.0, payload={'parent_asin': 'B0C4LKBK1Y'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=978, version=2, score=0.0, payload={'parent_asin': 'B0BJK3V3P4'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=601, version=2, score=0.0, payload={'parent_asin': 'B0BJSHNPCK'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=716, version=2, score=0.0, payload={'parent_asin': 'B0CDLCLTMT'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=832, version=2, score=0.0, payload={'parent_asin': 'B0C3V6WD2X'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=510, version=2, score=0.0, payload={'parent_asin': 'B09LC16CBP'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=953, version=2, score=0.0, payload={'parent_asin': 'B0B2R8R4Q2'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=982, version=2, score=0.0, payload={'parent_asin': 'B0B5T2NMPN'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=672, version=2, score=0.0, payload={'parent_asin': 'B0BQJWKBMF'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=817, version=2, score=0.0, payload={'parent_asin': 'B0CJ66R5H2'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=694, version=2, score=0.0, payload={'parent_asin': 'B087ZMF5PR'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=818, version=2, score=0.0, payload={'parent_asin': 'B0C8CKSLZC'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=505, version=2, score=0.0, payload={'parent_asin': 'B0973DV11T'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=781, version=2, score=0.0, payload={'parent_asin': 'B0BZKPJ2W7'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=504, version=2, score=0.0, payload={'parent_asin': 'B0BHRRNXV4'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=541, version=2, score=0.0, payload={'parent_asin': 'B0CGRSBNY1'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=588, version=2, score=0.0, payload={'parent_asin': 'B0B6P9SM9S'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=736, version=2, score=0.0, payload={'parent_asin': 'B0C53KN68T'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=847, version=2, score=0.0, payload={'parent_asin': 'B09Y54P7J9'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=939, version=2, score=0.0, payload={'parent_asin': 'B0BGLRMPQD'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=635, version=2, score=0.0, payload={'parent_asin': 'B0BHSPB4JL'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=652, version=2, score=0.0, payload={'parent_asin': 'B0BY2HY395'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=965, version=2, score=0.0, payload={'parent_asin': 'B0BN55992N'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=870, version=2, score=0.0, payload={'parent_asin': 'B0B59FCVCD'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=724, version=2, score=0.0, payload={'parent_asin': 'B09V5DGTSP'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=582, version=2, score=0.0, payload={'parent_asin': 'B0BKSXQ9D3'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=867, version=2, score=0.0, payload={'parent_asin': 'B0BVTCG71C'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=846, version=2, score=0.0, payload={'parent_asin': 'B0C65RMTNV'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=772, version=2, score=0.0, payload={'parent_asin': 'B0B87RQ2M5'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=565, version=2, score=0.0, payload={'parent_asin': 'B0B4ZG9BJF'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=730, version=2, score=0.0, payload={'parent_asin': 'B0C5HRS7TQ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=619, version=2, score=0.0, payload={'parent_asin': 'B0C373P4M7'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=809, version=2, score=0.0, payload={'parent_asin': 'B0BC13TQJQ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=592, version=2, score=0.0, payload={'parent_asin': 'B0C8CYKKW3'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=734, version=2, score=0.0, payload={'parent_asin': 'B0BMVGCQGS'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=748, version=2, score=0.0, payload={'parent_asin': 'B0BL6VDHXC'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=566, version=2, score=0.0, payload={'parent_asin': 'B09TK9NY5W'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=793, version=2, score=0.0, payload={'parent_asin': 'B08L5ZW5DK'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=667, version=2, score=0.0, payload={'parent_asin': 'B0B3LRFV26'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=906, version=2, score=0.0, payload={'parent_asin': 'B09TP9WJXH'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=746, version=2, score=0.0, payload={'parent_asin': 'B0BKKP997X'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=959, version=2, score=0.0, payload={'parent_asin': 'B0B6TS9CHB'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=993, version=2, score=0.0, payload={'parent_asin': 'B09VWDTSNY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=523, version=2, score=0.0, payload={'parent_asin': 'B099K711GD'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=533, version=2, score=0.0, payload={'parent_asin': 'B0BB7CYXXW'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=568, version=2, score=0.0, payload={'parent_asin': 'B09YMRF553'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=789, version=2, score=0.0, payload={'parent_asin': 'B0C996WY16'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=810, version=2, score=0.0, payload={'parent_asin': 'B0CGHXJR1Z'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=553, version=2, score=0.0, payload={'parent_asin': 'B09V7LNPC3'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=896, version=2, score=0.0, payload={'parent_asin': 'B09VF5ZCRC'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=799, version=2, score=0.0, payload={'parent_asin': 'B08P1T8R46'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=823, version=2, score=0.0, payload={'parent_asin': 'B0BJDVXB6T'}, vector=None, shard_key=None, order_value

In [7]:
parent_asin_list=[items.payload["parent_asin"] for items in payload.points]

In [8]:
len(parent_asin_list)

1000

In [11]:

df_reviews = pd.read_json("C:\\Users\\jaysi\\Desktop\\Desktop\\Ai-engineering\\data\\meta_Electronics_2022_23_with_categeory_rating_100_sample_2000.jsonl", lines=True)

In [12]:
df_reviews.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,[],4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN
2,All Electronics,USB C Docking Station Dual Monitor for MacBook...,3.9,1193,[【18-in-1Docking Station】With USB C Docking St...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ZMUIPNG,"[Electronics, Computers & Accessories, Laptop ...","{'Product Dimensions': '3.94""L x 1.18""W x 3.94...",B09SFN9NRX,NaN,NaN,NaN
3,Camera & Photo,[2023 Upgraded] Telescopes for Adults Astronom...,4.1,219,[🎁【2023 All New Experience】The newly upgraded ...,[],169.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Good picture quality', 'url': 'htt...",HUTACT,"[Electronics, Camera & Photo, Binoculars & Sco...","{'Product Dimensions': '32.5""D x 5.5""W x 9.7""H...",B09TP3SZ7C,NaN,NaN,NaN
4,AMAZON FASHION,"Laptop Bag 15.6 Inch, Laptop Briefcase Messeng...",4.5,222,"[Leather,Mesh, Imported, Multi-pockets and Lar...",[],24.95,[{'thumb': 'https://m.media-amazon.com/images/...,[],KPIQIU,"[Electronics, Computers & Accessories, Laptop ...",{'Product Dimensions': '16 x 2 x 12 inches; 1....,B0B5H7T7XZ,NaN,NaN,NaN

In [13]:
len(df_reviews)

2000

In [14]:
df_reviews_sample=df_reviews[df_reviews["parent_asin"].isin(parent_asin_list)]

In [15]:
df_reviews_sample

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,[],4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN
2,All Electronics,USB C Docking Station Dual Monitor for MacBook...,3.9,1193,[【18-in-1Docking Station】With USB C Docking St...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ZMUIPNG,"[Electronics, Computers & Accessories, Laptop ...","{'Product Dimensions': '3.94""L x 1.18""W x 3.94...",B09SFN9NRX,NaN,NaN,NaN
5,All Electronics,"Double Din Car Stereo with Backup Camera, 7 In...",4.0,191,[【Phone Mirror Link】Car stereo support mirror ...,[],39.93,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'TRASH', 'url': 'https://www.amazon...",LSLYA,"[Electronics, Car & Vehicle Electronics, Car E...",{'Package Dimensions': '8.19 x 6.1 x 5.04 inch...,B0BGR8FS29,NaN,NaN,NaN
8,All Electronics,Aigo 32GB Digital Voice Recorder 3072kbps one-...,4.0,174,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'aigo 32GB Digital Voice Recorder 3...,aigo,"[Electronics, Portable Audio & Video, Digital ...","{'Item Weight': '46 Grams', 'Item model number...",B09YD1FZDN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992,Camera & Photo,4K Smoke Detector WiFi Hidden Cameras HD 1080P...,2.7,238,[Full HD camera: 1080P HD resolution allows yo...,[],49.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Does it REALLY WORK? I put it to ...,Thanmiral,"[Electronics, Camera & Photo, Video Surveillan...",{'Package Dimensions': '5 x 4.92 x 1.54 inches...,B09KV7HQK9,NaN,NaN,NaN
1994,Cell Phones & Accessories,"for DJI OM 6 Magsafe Adapter Clamp, Compatible...",4.5,346,[Compatible Gimbal Stabilizer: for DJI Osmo Mo...,[],15.95,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'The Perfect Fix To Replace Stock C...,Aerbeis,"[Electronics, Camera & Photo, Accessories, Pro...",{'Package Dimensions': '2.87 x 2.8 x 0.39 inch...,B0BNF5NF31,NaN,NaN,NaN
1995,Office Products,"WALI Single Monitor Stand, Adjustable Gas Spri...",4.2,210,[Compatibility: The single monitor arm fits mo...,[],47.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'WALI Single Monitor Stand White (G...,WALI,"[Electronics, Computers & Accessories, Compute...","{'Manufacturer': 'WALI', 'Brand': 'WALI', 'Ite...",B09RTDQ8LZ,NaN,NaN,NaN
1997,All Electronics,BenQ TH585P 1080p Home Entertainment Projector...,4.5,327,[1080P RESOLUTION: 1080p Full HD image quality...,[Turn any space into your private arena. TH585...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'TH671ST - Low Input Lag', 'url': '...",BenQ,"[Electronics, Video Projectors]",{'Product Dimensions': '18.1 x 13.5 x 7 inches...,B09WF96S4C,NaN,NaN,NaN
1999,AMAZON FASHION,"Hp hope Smart Backpack for Women Travel, Durab...",4.5,339,"[polyester, Made in the USA or Imported, Nylon...",[],79.58,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': ' Hp hope Smart Backpack for Women ...,Hp hope,"[Electronics, Computers & Accessories, Laptop ...",{'Product Dimensions': '7 x 11.8 x 16.5 inches...,B09WDPZYX7,NaN,NaN,NaN

In [16]:
len(df_reviews_sample)

1000

### define Function To Preprocess Review Data

In [23]:
def preprocess_review_data(row):
    return f"{row['title']} {row['description']}"

In [24]:
encoading=tiktoken.encoding_for_model("text-embedding-3-small")

In [19]:
encoading.encode("can i get some earPhone")

[4919, 602, 636, 1063, 2487, 7084]

In [29]:
def toek_count(row,model="text-embedding-3-small"):
    encoading=tiktoken.encoding_for_model(model)
    return len(encoading.encode(row["preprocessed_data"]))

In [26]:
df_reviews_sample['preprocessed_data']=df_reviews_sample.apply(preprocess_review_data,axis=1)

In [30]:
df_reviews_sample["preprocessd_data_token_count"]=df_reviews_sample.apply(toek_count,axis=1)

In [31]:
df_reviews_sample.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,preprocessed_data,preprocessd_data_token_count
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",77
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,[],4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",34
2,All Electronics,USB C Docking Station Dual Monitor for MacBook...,3.9,1193,[【18-in-1Docking Station】With USB C Docking St...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ZMUIPNG,"[Electronics, Computers & Accessories, Laptop ...","{'Product Dimensions': '3.94""L x 1.18""W x 3.94...",B09SFN9NRX,NaN,NaN,NaN,USB C Docking Station Dual Monitor for MacBook...,58
5,All Electronics,"Double Din Car Stereo with Backup Camera, 7 In...",4.0,191,[【Phone Mirror Link】Car stereo support mirror ...,[],39.93,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'TRASH', 'url': 'https://www.amazon...",LSLYA,"[Electronics, Car & Vehicle Electronics, Car E...",{'Package Dimensions': '8.19 x 6.1 x 5.04 inch...,B0BGR8FS29,NaN,NaN,NaN,"Double Din Car Stereo with Backup Camera, 7 In...",45
8,All Electronics,Aigo 32GB Digital Voice Recorder 3072kbps one-...,4.0,174,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'aigo 32GB Digital Voice Recorder 3...,aigo,"[Electronics, Portable Audio & Video, Digital ...","{'Item Weight': '46 Grams', 'Item model number...",B09YD1FZDN,NaN,NaN,NaN,Aigo 32GB Digital Voice Recorder 3072kbps one-...,31

In [32]:
len(df_reviews_sample)

1000

In [35]:
token_counts=df_reviews_sample["preprocessd_data_token_count"].sum()

In [36]:
token_counts

np.int64(93799)

### Create a new Qdrant Collection For reviews

In [43]:
qdrant_client.create_collection(
    collection_name="Amazon-item-collection-01-reviews",
    vectors_config=VectorParams(size=1536,distance=Distance.COSINE)
)

True

In [45]:
qdrant_client.create_payload_index(
    collection_name="Amazon-item-collection-01-reviews",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

In [46]:
def get_embedding(text,model="text-embedding-3-small"):
    response=openai.embeddings.create(
        input=[text],
        model=model
    )
    return response.data[0].embedding

In [47]:
def get_embedding_batch(text_list,model="text-embedding-3-small",batch_size=100):
    if len(text_list)<=batch_size:
        response=openai.embeddings.create(input=text_list,model=model)
        return [embedding.embedding for embedding in response.data]

    all_embeddings=[]
    counter=1
    for i in range(0,len(text_list),batch_size):
        batch=text_list[i:i+batch_size]
        response=openai.embeddings.create(input=batch,model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        counter+=1
    
    return all_embeddings

### Embedded The Text