In [1]:
print("Hello")

Hello

In [2]:
import pandas as pd;
import openai

In [3]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance,VectorParams,PointStruct

Read And Sample dataset with Amazon inventory data

In [4]:
df_items=pd.read_json("C:\\Users\\jaysi\\Desktop\\Desktop\\Ai-engineering\\data\\meta_Electronics_2022_23_with_categeory_rating_100_sample_2000.jsonl",lines=True)

In [5]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,[],4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN
2,All Electronics,USB C Docking Station Dual Monitor for MacBook...,3.9,1193,[【18-in-1Docking Station】With USB C Docking St...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ZMUIPNG,"[Electronics, Computers & Accessories, Laptop ...","{'Product Dimensions': '3.94""L x 1.18""W x 3.94...",B09SFN9NRX,NaN,NaN,NaN
3,Camera & Photo,[2023 Upgraded] Telescopes for Adults Astronom...,4.1,219,[🎁【2023 All New Experience】The newly upgraded ...,[],169.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Good picture quality', 'url': 'htt...",HUTACT,"[Electronics, Camera & Photo, Binoculars & Sco...","{'Product Dimensions': '32.5""D x 5.5""W x 9.7""H...",B09TP3SZ7C,NaN,NaN,NaN
4,AMAZON FASHION,"Laptop Bag 15.6 Inch, Laptop Briefcase Messeng...",4.5,222,"[Leather,Mesh, Imported, Multi-pockets and Lar...",[],24.95,[{'thumb': 'https://m.media-amazon.com/images/...,[],KPIQIU,"[Electronics, Computers & Accessories, Laptop ...",{'Product Dimensions': '16 x 2 x 12 inches; 1....,B0B5H7T7XZ,NaN,NaN,NaN

In [6]:
list(df_items['features'].items())[0]

(0,
 ['【Fast Charging Cord】These USB C cables provide up to a 3A charging current to greatly shorten the charging time, meets QC2.0 /3.0 fast charging protocol,Incredibly charge your phone from 0 to 80% in 50 minute. 480Mbps (40-60M/s) ultra fast data transmission, which leads to a faster data sync.(Note:Cables support fast charging,but require a USB-A QC3.0/QC2.0/AFC charger)',
  '【Universal Compatibility】The USB C Charger Cable is compatible with Samsung Galaxy S20 / S10 / S9 / S8+ / S8 / A02s / A03s,A12 A20 A21 A22 A23 A31 A32 A33 A41 A42 A50 A52 A52s 5G A71 A72 A73,M11 M21 M31 M51,M12 M22 M32 M52,iPad Pro 2018 / 2020,Sony Xperia XZ/X Compact/L1 / XZs / XA1 / X Premium, HTC 10 LG G5 G6,OnePlus 5T / 6T, Lumia 950 / 950XL,Huawei P9 P9 Plus P10 P10 Plus Honor Mate 9 Mate 9 pro Mate 10 pro Mate 10 lite and more',
  '【Premium Workmanship】Unique increased friction design allows you to easily unplug the cable from your charger,combine 250d bulletproof fiber core to build a cable so durable that will save your time and money.',
  '【Unbreakable Nylon Braided Cord】Premium nylon braided build a cable so durable that will outlast your phone.',
  "【What You Get】(2pack 3.3ft+6.6ft) USB A to USB C Cable with 18-Month free Warranty. If you have any questions, please don't to hesitate to contact us, we will give you a satisfied solution within 24 hours."])

In [7]:
list(df_items['images'].items())[0]

(0,
 [{'thumb': 'https://m.media-amazon.com/images/I/51G07yWoOBL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51G07yWoOBL.jpg',
   'variant': 'MAIN',
   'hi_res': 'https://m.media-amazon.com/images/I/611AVJMH+JL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41c+40oKkKL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41c+40oKkKL.jpg',
   'variant': 'PT01',
   'hi_res': 'https://m.media-amazon.com/images/I/61ihhPW7VCL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51y1YnwiUZL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51y1YnwiUZL.jpg',
   'variant': 'PT02',
   'hi_res': 'https://m.media-amazon.com/images/I/61UkcVETKcL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41Nvr++q39L._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41Nvr++q39L.jpg',
   'variant': 'PT03',
   'hi_res': 'https://m.media-amazon.com/images/I/611IpDcRk3L._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41QrI+i4-lL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41QrI+i4-lL.jpg',
   'variant': 'PT04',
   'hi_res': 'https://m.media-amazon.com/images/I/61FQzaPa6jL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51lezEs5DvL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51lezEs5DvL.jpg',
   'variant': 'PT05',
   'hi_res': 'https://m.media-amazon.com/images/I/71qz3TFInJL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/514a4NZS1ZL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/514a4NZS1ZL.jpg',
   'variant': 'PT06',
   'hi_res': 'https://m.media-amazon.com/images/I/71e6ARGEtZL._SL1200_.jpg'}])

# Preprocess Title And Feature

In [8]:
def preprocessed_decription(row):
    return f"{row['title']}{''.join(row['features'])}"

In [9]:
def extrect_first_large_image(row):
    return row['images'][0].get("large","")

In [10]:
df_items['description']=df_items.apply(preprocessed_decription,axis=1)
df_items['image']=df_items.apply(extrect_first_large_image,axis=1)

In [11]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,image
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51G07yWoOB...
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41bOA5-ogW...
2,All Electronics,USB C Docking Station Dual Monitor for MacBook...,3.9,1193,[【18-in-1Docking Station】With USB C Docking St...,USB C Docking Station Dual Monitor for MacBook...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ZMUIPNG,"[Electronics, Computers & Accessories, Laptop ...","{'Product Dimensions': '3.94""L x 1.18""W x 3.94...",B09SFN9NRX,NaN,NaN,NaN,https://m.media-amazon.com/images/I/416IzmVKiC...
3,Camera & Photo,[2023 Upgraded] Telescopes for Adults Astronom...,4.1,219,[🎁【2023 All New Experience】The newly upgraded ...,[2023 Upgraded] Telescopes for Adults Astronom...,169.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Good picture quality', 'url': 'htt...",HUTACT,"[Electronics, Camera & Photo, Binoculars & Sco...","{'Product Dimensions': '32.5""D x 5.5""W x 9.7""H...",B09TP3SZ7C,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41wO4J3TT0...
4,AMAZON FASHION,"Laptop Bag 15.6 Inch, Laptop Briefcase Messeng...",4.5,222,"[Leather,Mesh, Imported, Multi-pockets and Lar...","Laptop Bag 15.6 Inch, Laptop Briefcase Messeng...",24.95,[{'thumb': 'https://m.media-amazon.com/images/...,[],KPIQIU,"[Electronics, Computers & Accessories, Laptop ...",{'Product Dimensions': '16 x 2 x 12 inches; 1....,B0B5H7T7XZ,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41mwlYqT5p...

In [12]:
list(df_items['description'].items())[0]

(0,
 "RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB Type C Fast Charging Cord - Nylon Braided USB C Charger Cable for Galaxy A20/A50/S10/S9/S8+/S8, iPad Pro 2018, Sony XZ, HTC 10, OnePlus 5T, Huawei P9 etc.【Fast Charging Cord】These USB C cables provide up to a 3A charging current to greatly shorten the charging time, meets QC2.0 /3.0 fast charging protocol,Incredibly charge your phone from 0 to 80% in 50 minute. 480Mbps (40-60M/s) ultra fast data transmission, which leads to a faster data sync.(Note:Cables support fast charging,but require a USB-A QC3.0/QC2.0/AFC charger)【Universal Compatibility】The USB C Charger Cable is compatible with Samsung Galaxy S20 / S10 / S9 / S8+ / S8 / A02s / A03s,A12 A20 A21 A22 A23 A31 A32 A33 A41 A42 A50 A52 A52s 5G A71 A72 A73,M11 M21 M31 M51,M12 M22 M32 M52,iPad Pro 2018 / 2020,Sony Xperia XZ/X Compact/L1 / XZs / XA1 / X Premium, HTC 10 LG G5 G6,OnePlus 5T / 6T, Lumia 950 / 950XL,Huawei P9 P9 Plus P10 P10 Plus Honor Mate 9 Mate 9 pro Mate 10 pro Mate 10 lite and more【Premium Workmanship】Unique increased friction design allows you to easily unplug the cable from your charger,combine 250d bulletproof fiber core to build a cable so durable that will save your time and money.【Unbreakable Nylon Braided Cord】Premium nylon braided build a cable so durable that will outlast your phone.【What You Get】(2pack 3.3ft+6.6ft) USB A to USB C Cable with 18-Month free Warranty. If you have any questions, please don't to hesitate to contact us, we will give you a satisfied solution within 24 hours.")

In [13]:
list(df_items['image'].items())[0]

(0, 'https://m.media-amazon.com/images/I/51G07yWoOBL.jpg')

In [14]:
df_sample=df_items.sample(50,random_state=42)

In [15]:
data_to_embed=df_sample[["description","image","rating_number","price","average_rating","parent_asin"]].to_dict(orient="records")

In [31]:
length(data_to_embed)

NameError: name 'length' is not defined

## Embedding Function

In [27]:
from dotenv import load_dotenv
load_dotenv()
from openai import OpenAI
client = OpenAI()

In [33]:
response=client.embeddings.create(
        model="text-embedding-3-small",
        input="random  text"
    )

In [39]:
len(response.data[0].embedding)

1536

In [29]:
def create_embeddings(text,model="text-embedding-3-small"):
    response=client.embeddings.create(
        model=model,
        input=text
    )
    return response.data[0].embedding

In [30]:
quadrant_client=QdrantClient(url="http://localhost:6333/")

In [ ]:
quadrant_client.create_collection(
    collection_name="Amazon_items_collection-00",
    vectors_config=VectorParams(size=1536,distance=Distance.COSINE)
)

In [45]:

def get_embedding(text):
    response = client.embeddings.create(
        model="text-embedding-3-small",
        input=text
    )
    return response.data[0].embedding

In [46]:
points_struct = []

for i, data in enumerate(data_to_embed):
    embedding = get_embedding(data["description"])

    points_struct.append(
        PointStruct(
            id=i,
            vector=embedding,
            payload=data
        )
    )

In [48]:
points_struct

[PointStruct(id=0, vector=[-0.0003147125244140625, 0.028961181640625, -0.0189666748046875, -0.03216552734375, -0.0374755859375, -0.005435943603515625, -0.0011081695556640625, 0.0142059326171875, 0.0226287841796875, -0.017730712890625, 0.031402587890625, -0.0482177734375, -0.0278167724609375, 0.02972412109375, 0.01837158203125, -0.00643157958984375, -0.05303955078125, -0.026763916015625, -0.031646728515625, -0.0058746337890625, 0.006107330322265625, 0.051422119140625, -0.042327880859375, -0.007259368896484375, 0.0086822509765625, -0.002910614013671875, 0.03143310546875, 0.02392578125, 0.01322174072265625, -0.01024627685546875, 0.0187225341796875, 0.006591796875, 0.0015649795532226562, -0.07220458984375, -0.01384735107421875, -0.031463623046875, 0.0382080078125, -0.029815673828125, 0.0204925537109375, 0.006317138671875, 0.0185394287109375, 0.00848388671875, 0.00554656982421875, 0.00930023193359375, -0.01111602783203125, 0.0345458984375, -0.007293701171875, 0.03900146484375, -0.0191192626953125, 0.049957275390625, -0.01285552978515625, 0.057952880859375, -0.0196380615234375, 0.06781005859375, -0.01316070556640625, 0.0187530517578125, -0.014984130859375, 0.06829833984375, -0.0010519027709960938, -0.038726806640625, -0.0180816650390625, 0.011199951171875, 0.024139404296875, 0.04779052734375, -0.021148681640625, -0.015960693359375, 0.0196380615234375, 0.027313232421875, -0.01806640625, -0.007099151611328125, 0.0260009765625, -0.016937255859375, -0.03759765625, -0.0241241455078125, -0.034149169921875, 0.0238037109375, 0.00965118408203125, -0.056243896484375, 0.0246734619140625, -0.00891876220703125, -0.0159454345703125, -0.006427764892578125, -0.0194091796875, 0.0482177734375, -0.0288848876953125, -0.038238525390625, -0.07086181640625, -0.036346435546875, -0.0438232421875, 0.022003173828125, -0.0310516357421875, -0.0689697265625, 0.0218048095703125, 0.0278778076171875, -0.00969696044921875, 0.016143798828125, 0.042572021484375, 0.00437164306640625, 0.00023293495178222656, 0.0276947021484375, -0.018096923828125, -0.0229339599609375, -0.0177764892578125, -0.050445556640625, 0.0237884521484375, -0.010772705078125, -0.035980224609375, 0.02923583984375, -0.003826141357421875, 0.002941131591796875, -0.0241546630859375, 0.0253143310546875, 0.007602691650390625, 0.0066375732421875, -0.0135650634765625, 0.01448822021484375, 0.0081024169921875, -0.0435791015625, 0.032257080078125, -0.0097808837890625, 0.00037550926208496094, 0.050018310546875, 0.03839111328125, -0.05633544921875, 0.035919189453125, -0.004314422607421875, -0.0019426345825195312, -0.027923583984375, -0.00885009765625, -0.0005087852478027344, -0.0068511962890625, 0.006801605224609375, 0.06878662109375, -0.008087158203125, 0.0186920166015625, -0.048828125, -0.0245819091796875, 0.005138397216796875, 0.0025081634521484375, -0.0596923828125, 0.0231475830078125, -0.0117950439453125, 0.035675048828125, -0.0176849365234375, 0.0286407470703125, -0.01509857177734375, 0.06634521484375, -0.022674560546875, -0.05401611328125, 0.06414794921875, -0.020355224609375, 0.01422119140625, -0.0036296844482421875, 0.0291748046875, 0.055145263671875, -0.0286407470703125, 6.973743438720703e-06, 0.06390380859375, -0.048126220703125, 0.00039267539978027344, 0.00435638427734375, 0.0174102783203125, -0.001262664794921875, -0.0111846923828125, 0.0213623046875, 0.0306549072265625, 0.0099945068359375, -0.0133209228515625, -0.05609130859375, 0.01232147216796875, 0.051025390625, -0.0207061767578125, -0.0308990478515625, 0.016082763671875, 0.01837158203125, -0.042144775390625, 0.006252288818359375, -0.0016632080078125, -0.0450439453125, -0.0022411346435546875, -0.014617919921875, -0.037506103515625, -0.007781982421875, -0.025970458984375, -0.023406982421875, 0.0099639892578125, -0.0176544189453125, 0.038543701171875, 0.00650787353515625, -0.018890380859375, 0.0440673828125, -0.04052734375, -0.0174560546875, 0.021240234375, -0.0350341796875, -0.053375244140625, 0.0213623046875, 0.039703369140625, -0.031463623046875, 0.050628662109375, 0.035186767578125, -0.0123748779296875, 0.04510498046875, -0.00785064697265625, -0.044586181640625, -0.028594970703125, 0.04058837890625, -0.0115509033203125, 0.01047515869140625, -0.02947998046875, 0.0601806640625, -0.01544952392578125, -0.01546478271484375, -0.007404327392578125, 0.0004837512969970703, 0.01080322265625, -0.0251007080078125, -0.0212860107421875, 0.0159759521484375, 0.0088348388671875, -0.050628662109375, 0.031463623046875, 0.035888671875, 0.01068115234375, -0.030242919921875, -0.0167694091796875, 0.0281219482421875, -0.040618896484375, 0.0231475830078125, -0.06298828125, 0.0032291412353515625, 0.0311737060546875, 0.01490020751953125, -0.030609130859375, 0.011444091796875, 0.00492095947265625, -0.004772186279296875, -0.04107666015625, 0.03668212890625, -0.07720947265625, -0.025360107421875, -0.01629638671875, 0.01422119140625, 0.04510498046875, 0.017822265625, -0.024688720703125, -0.0311737060546875, -0.042083740234375, 0.0176239013671875, -0.0167999267578125, 0.0163726806640625, -0.0007395744323730469, 0.03485107421875, -0.004634857177734375, 0.05975341796875, 0.039794921875, 0.0323486328125, 0.010772705078125, -0.03375244140625, -0.0609130859375, 0.01708984375, -0.033416748046875, 0.0028133392333984375, -0.0179443359375, 0.01873779296875, 0.040313720703125, 0.03485107421875, -0.00896453857421875, -0.0265960693359375, 0.002414703369140625, -0.041961669921875, 0.013519287109375, -0.006671905517578125, 0.0194854736328125, 0.02398681640625, -0.0021877288818359375, -0.0267333984375, -0.042724609375, 0.005199432373046875, 0.031219482421875, -0.027191162109375, 0.040924072265625, -0.027496337890625, -0.03216552734375, 0.026153564453125, -0.029296875, -0.0185394287109375, 0.002170562744140625, -0.030517578125, -0.0166473388671875, 0.026885986328125, 0.007732391357421875, -0.0242462158203125, -0.01343536376953125, -0.00318145751953125, -0.0151214599609375, 0.0430908203125, -0.02703857421875, -0.03240966796875, -0.0189056396484375, 0.02655029296875, 0.0482177734375, -0.03399658203125, -0.0255279541015625, 0.004550933837890625, 0.07183837890625, -0.0031604766845703125, -0.0249176025390625, 0.015625, 0.00803375244140625, -0.0044097900390625, 0.08221435546875, 0.00994873046875, -0.0303192138671875, -0.0268402099609375, -0.049560546875, -0.004741668701171875, -0.00865936279296875, -0.022735595703125, -0.05401611328125, -0.006359100341796875, 0.019439697265625, 0.05010986328125, 0.001308441162109375, 0.05865478515625, 0.022186279296875, 0.0008072853088378906, -0.044464111328125, -0.024078369140625, -0.033416748046875, -0.0278472900390625, -0.0076446533203125, -0.03424072265625, -0.019378662109375, 0.009368896484375, -0.003765106201171875, 0.03607177734375, -0.04058837890625, -0.030731201171875, 0.0034046173095703125, 0.0009355545043945312, -0.00165557861328125, -0.04541015625, 0.03216552734375, 0.03271484375, -0.02301025390625, 0.0204010009765625, -0.0242919921875, -0.0166168212890625, 0.05096435546875, 0.0218658447265625, 0.004795074462890625, 0.0445556640625, -0.02020263671875, -0.0025768280029296875, -0.056182861328125, -0.0085906982421875, -0.0333251953125, -0.011749267578125, -0.00457000732421875, -0.05126953125, 0.0225067138671875, 0.022552490234375, 0.01113128662109375, 0.0265960693359375, 0.0264434814453125, -0.042755126953125, -0.0086669921875, -0.00745391845703125, -0.035919189453125, 0.00930023193359375, 0.0286407470703125, 0.0196533203125, 0.0018510818481445312, -0.037933349609375, 0.0037403106689453125, 0.0247802734375, 0.042327880859375, -0.0198974609375, 0.0144805908203125, 0.00777435302734375, 0.006298065185546875, 0.00859832763671875, -0.016937255859375, 0.005611419677734375, 0.0140838623046875, -0.037689208984375, 0.029693603515625, -0.0013151168823242188, 0.0164337158203125, -0.0012769699096679688, -0.0418701171875, 0.0093994140625, -0.048614501953125, 0.06927490234375, 0.01508331298828125, 0.049102783203125, 0.00684356689453125, 0.01617431640625, -0.0396728515625, -0.00829315185546875, -0.059234619140625, -0.024810791015625, 0.0270843505859375, 0.005828857421875, -0.041259765625, -0.002925872802734375, 0.021148681640625, 0.0212554931640625, -0.01160430908203125, 0.0164794921875, -0.0100860595703125, 0.0256805419921875, 0.034881591796875, 0.03411865234375, -0.01247406005859375, -0.043365478515625, 0.019866943359375, 0.0208587646484375, 0.0291748046875, 0.0178375244140625, -0.058013916015625, 0.005680084228515625, 0.0268707275390625, 0.0018329620361328125, -0.02099609375, -0.01181793212890625, -0.03143310546875, 0.07110595703125, -0.04632568359375, -0.03955078125, -0.0182037353515625, -0.01593017578125, -0.0482177734375, -0.03497314453125, 0.0186614990234375, -0.021636962890625, 0.0174560546875, -0.03411865234375, -0.007160186767578125, 0.02069091796875, 0.00235748291015625, 0.0038623809814453125, 0.03802490234375, -0.01468658447265625, 0.0270843505859375, -0.049896240234375, 0.0095977783203125, -0.048126220703125, -0.043731689453125, -0.015106201171875, -0.023712158203125, 0.00498199462890625, 0.033538818359375, 0.0232391357421875, 0.042572021484375, 0.0484619140625, -0.0129547119140625, -0.0087890625, 0.006988525390625, 0.00959014892578125, -0.0074005126953125, 0.04461669921875, 0.0230255126953125, -0.00908660888671875, 0.0230560302734375, 0.007640838623046875, 0.0186004638671875, 0.0355224609375, -0.00576019287109375, 0.003650665283203125, -0.057281494140625, 0.01275634765625, -0.0121917724609375, 0.015106201171875, 0.0211334228515625, 0.01425933837890625, 0.006801605224609375, -0.026397705078125, -0.0175323486328125, 0.0024623870849609375, 0.0021648406982421875, -0.035491943359375, 0.010528564453125, 0.0048980712890625, -0.02655029296875, 0.04296875, -0.0086517333984375, -0.06103515625, -0.06280517578125, -0.0173187255859375, -0.033477783203125, 0.0374755859375, -0.01177978515625, 0.01080322265625, 0.001556396484375, -0.053375244140625, 0.008697509765625, 0.0278167724609375, 0.0093231201171875, 0.04510498046875, -0.0018529891967773438, 0.0245819091796875, 0.0643310546875, -0.00036787986755371094, 0.07196044921875, 0.0278167724609375, -0.0256805419921875, 0.0205535888671875, -0.0031490325927734375, 0.01291656494140625, -0.008758544921875, -0.0166778564453125, -0.0018682479858398438, -0.00904083251953125, -0.03857421875, 0.01142120361328125, 0.074462890625, 0.0101470947265625, -0.0178680419921875, -0.042266845703125, -0.00958251953125, 0.02935791015625, -0.00347137451171875, -0.0112457275390625, -0.0183868408203125, -0.0031604766845703125, -0.07110595703125, -0.022674560546875, -0.05377197265625, -0.026641845703125, 0.01629638671875, -0.04681396484375, -0.03778076171875, -0.0208892822265625, 0.01617431640625, -0.00569915771484375, -0.007171630859375, 0.00437164306640625, 0.0018148422241210938, -0.00909423828125, 0.040008544921875, 0.00409698486328125, 0.01320648193359375, 0.019683837890625, -0.0099334716796875, -0.01837158203125, -0.023040771484375, 0.00978851318359375, 0.0079345703125, 0.04937744140625, -0.0258026123046875, 0.038848876953125, -0.00391387939453125, -0.0205841064453125, 0.02276611328125, 0.01314544677734375, -0.0033016204833984375, 0.025604248046875, 0.0184783935546875, 0.00420379638671875, 0.01226043701171875, 0.00865936279296875, 0.016571044921875, 0.0186767578125, 0.0295562744140625, 0.0181121826171875, -0.03662109375, 0.0034942626953125, 0.0251007080078125, 0.004627227783203125, 0.006488800048828125, 0.004913330078125, -0.052947998046875, 0.038360595703125, 0.0202789306640625, -0.0267333984375, 0.00801849365234375, 0.0038909912109375, 0.0153045654296875, -0.0230560302734375, -0.0251922607421875, 0.0172576904296875, 0.0120849609375, -0.00275421142578125, -0.0251922607421875, 0.01488494873046875, -0.025177001953125, -0.005115509033203125, 0.07965087890625, 0.0013885498046875, -0.021697998046875, -0.031890869140625, -0.01080322265625, -0.02545166015625, 0.004665374755859375, 0.0255126953125, 0.0011768341064453125, 0.0167388916015625, -0.0228424072265625, -0.00794219970703125, 0.002933502197265625, -0.0023956298828125, 0.006458282470703125, -0.00977325439453125, -0.0160369873046875, 0.061126708984375, 0.00534820556640625, 0.04541015625, 0.0238494873046875, 0.01229095458984375, -0.0224609375, -0.01025390625, 0.003917694091796875, -0.0268707275390625, -0.01904296875, -0.006954193115234375, -0.03057861328125, 0.0290985107421875, 0.005420684814453125, -0.037017822265625, -0.00582122802734375, 0.0286407470703125, 0.0245513916015625, -0.0159759521484375, 0.007564544677734375, -0.0310516357421875, -0.0333251953125, 0.0268707275390625, -0.0104522705078125, -0.026092529296875, 0.05560302734375, 0.004283905029296875, -0.03778076171875, -0.01081085205078125, -0.03289794921875, -0.042083740234375, 0.04498291015625, -0.0082244873046875, -0.041534423828125, 0.00809478759765625, 0.0033893585205078125, -0.006397247314453125, -0.034393310546875, 0.041046142578125, -0.01226043701171875, -0.02923583984375, -0.006359100341796875, 0.01432037353515625, 0.005977630615234375, -0.0076141357421875, 0.0186309814453125, 0.00923919677734375, 0.01094818115234375, 0.0184326171875, 0.02264404296875, -0.0264434814453125, -0.00043392181396484375, 0.00969696044921875, -0.00833892822265625, -0.0548095703125, 0.0203399658203125, 0.013519287109375, -0.022705078125, 0.00710296630859375, 0.01012420654296875, 0.0295257568359375, 0.0015354156494140625, -0.0216064453125, 0.0209503173828125, -0.0328369140625, -0.0031909942626953125, 0.00787353515625, -0.034637451171875, 0.03131103515625, -0.025634765625, -0.006740570068359375, 0.02294921875, 0.0018281936645507812, 0.032196044921875, -0.0178375244140625, -0.0199127197265625, -0.057525634765625, -0.0014057159423828125, 0.0187835693359375, -0.0278167724609375, 0.012603759765625, 0.0224609375, -0.001392364501953125, 0.0079345703125, -0.0018587112426757812, -0.011383056640625, -0.004184722900390625, 0.002285003662109375, 0.0166778564453125, 0.0011501312255859375, -0.009246826171875, -0.018218994140625, -0.01904296875, -0.0345458984375, -0.005123138427734375, 0.0018987655639648438, 0.0078582763671875, -0.047943115234375, -0.03948974609375, -0.00035071372985839844, -0.00835418701171875, -0.0083770751953125, 0.0201873779296875, 0.0007429122924804688, -0.05535888671875, -0.0019273757934570312, -0.0250091552734375, 0.022247314453125, 0.0190582275390625, -0.054656982421875, 0.00592803955078125, -0.0008115768432617188, 0.0118408203125, 0.002597808837890625, 0.00012290477752685547, 0.042755126953125, -0.026519775390625, -0.0083770751953125, 0.005657196044921875, 0.0192718505859375, -0.00490570068359375, 0.0164337158203125, -0.054107666015625, -0.01605224609375, -0.0033512115478515625, 0.0066375732421875, -0.00475311279296875, -0.00885009765625, -0.004199981689453125, 0.047454833984375, -0.0682373046875, -0.01551055908203125, -0.0193328857421875, -0.022064208984375, 0.0010166168212890625, 0.00746917724609375, 0.00487518310546875, 0.0198211669921875, 0.0144805908203125, -0.0078277587890625, 0.048858642578125, 0.02166748046875, -0.0168609619140625, -0.023681640625, 0.0027713775634765625, 0.0094757080078125, 0.00479888916015625, -0.01123809814453125, 0.0024356842041015625, -0.02117919921875, -0.002445220947265625, -0.035400390625, 0.01323699951171875, -0.016998291015625, 0.032867431640625, 0.0225372314453125, 0.0187225341796875, 0.01088714599609375, 0.0223236083984375, 0.0227813720703125, -0.0070343017578125, 0.01442718505859375, 0.0229644775390625, -0.005382537841796875, -0.0306396484375, -0.027374267578125, 0.02349853515625, -0.01183319091796875, 0.00537109375, 0.0021514892578125, -0.02716064453125, 0.0190277099609375, 0.0014925003051757812, -0.0263671875, 0.01538848876953125, -0.01898193359375, -0.034454345703125, 0.0279693603515625, -0.030120849609375, -0.049468994140625, 0.00510406494140625, 0.0231781005859375, 0.00798797607421875, -0.041229248046875, 0.04150390625, -0.048553466796875, -0.017608642578125, -0.020355224609375, 0.0283966064453125, 0.0216064453125, 0.0128631591796875, -0.021148681640625, 0.01207733154296875, -0.0013952255249023438, -0.04345703125, -0.009674072265625, -0.0175323486328125, -0.0360107421875, 0.0166778564453125, -0.0085906982421875, -0.024566650390625, 0.003932952880859375, -0.0248565673828125, -0.025238037109375, 5.9723854064941406e-05, -0.01091766357421875, -0.0306549072265625, 0.0179595947265625, 0.0285186767578125, 0.0236053466796875, -0.0018377304077148438, -0.005687713623046875, 0.00818634033203125, 0.00921630859375, 0.03204345703125, 0.003509521484375, 0.03399658203125, 0.02459716796875, 0.01065826416015625, -0.00859832763671875, 0.008697509765625, -0.025238037109375, 0.06024169921875, 0.04791259765625, 0.0187530517578125, -0.00926971435546875, 0.0259246826171875, -0.0091094970703125, -0.007091522216796875, 0.0200958251953125, -0.04486083984375, 0.0083465576171875, -0.01206207275390625, -0.00714111328125, 0.0158843994140625, -0.0384521484375, -0.048858642578125, -0.00710296630859375, -0.01450347900390625, -0.007701873779296875, -0.003582000732421875, 0.017120361328125, 0.00949859619140625, 0.04290771484375, 0.0290374755859375, -0.039031982421875, -0.004711151123046875, 0.0261688232421875, 0.04730224609375, -0.0118255615234375, 0.001422882080078125, -0.01397705078125, -0.015869140625, -0.004581451416015625, -0.025970458984375, -0.0014514923095703125, -0.02679443359375, -0.0134429931640625, 0.056549072265625, 0.00394439697265625, -0.00948333740234375, 0.005512237548828125, 0.0008687973022460938, 0.0146026611328125, -0.00811004638671875, -0.018524169921875, 0.0110931396484375, -0.0212249755859375, 0.00548553466796875, 0.0003905296325683594, 0.0208892822265625, 0.0251922607421875, -0.01312255859375, 0.0044097900390625, -0.003681182861328125, 0.0024166107177734375, -0.0087738037109375, -0.0027256011962890625, -0.00283050537109375, 0.02008056640625, -0.022613525390625, 0.019317626953125, -0.0016498565673828125, 0.018280029296875, -0.0201263427734375, 0.01556396484375, -0.01381683349609375, 0.0221710205078125, -0.049713134765625, 0.0281219482421875, 0.0189208984375, 0.016510009765625, -0.0096588134765625, 0.01068115234375, 0.0177001953125, -0.0178070068359375, -0.035400390625, 0.0219268798828125, 0.0255279541015625, 0.005390167236328125, -0.003299713134765625, -0.01029205322265625, 0.0016527175903320312, 0.01284027099609375, 0.00930023193359375, -0.03759765625, -0.0092620849609375, -0.0361328125, -0.0053558349609375, 0.00018739700317382812, -0.039520263671875, -0.00010597705841064453, 0.032440185546875, -0.03338623046875, -0.0169525146484375, 0.0012083053588867188, -0.0281219482421875, 0.007701873779296875, -0.01751708984375, -0.0292816162109375, 0.04071044921875, -0.0178985595703125, 0.034393310546875, 0.015716552734375, -0.047454833984375, 0.0007176399230957031, 0.002483367919921875, -0.00742340087890625, 0.0166015625, 0.03125, 0.03656005859375, 0.009796142578125, -0.00893402099609375, 0.0290374755859375, -0.024810791015625, -0.0180206298828125, -0.0273590087890625, 0.03900146484375, 0.0001926422119140625, -0.016326904296875, 0.0262298583984375, -0.0187225341796875, -0.01323699951171875, 0.0109710693359375, 0.003597259521484375, 0.0022754669189453125, 0.0406494140625, -0.06304931640625, 0.010711669921875, -0.01488494873046875, 0.00927734375, -0.015380859375, 0.0156707763671875, 0.040985107421875, 0.0096588134765625, 0.0104827880859375, 0.005352020263671875, -0.035369873046875, -0.0298004150390625, 0.01349639892578125, 0.005451202392578125, 0.004810333251953125, 0.052947998046875, 0.01004791259765625, -0.050018310546875, -0.0242919921875, 0.03009033203125, 0.049591064453125, -0.0216827392578125, 0.01227569580078125, 0.005344390869140625, -0.00815582275390625, 0.004650115966796875, -0.0231475830078125, -0.00209808349609375, 0.033111572265625, 0.0119171142578125, -0.0007824897766113281, -0.036407470703125, 0.0157012939453125, 0.0615234375, 0.0084075927734375, 0.025115966796875, 0.0247039794921875, -0.04949951171875, 0.024322509765625, -0.0268707275390625, -0.01058197021484375, 0.006740570068359375, -0.008949279

Write embedded data to Qadrant

In [49]:
quadrant_client.upsert(
    collection_name="Amazon_items_collection-00",
    wait=True,
    points=points_struct
    
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

simple Retriver fuction

In [66]:
def retrive_data(query, k=5):
    query_embedding = get_embedding(query)

    result = quadrant_client.query_points(
        collection_name="Amazon_items_collection-00",
        query=query_embedding,
        limit=k,
    )

    print("Inside function:", result)  # Debug

    return result

In [67]:
res = retrive_data("what kind of charging cords you offered", 5)

print("Outside function:", res)
print(type(res))

Inside function: points=[ScoredPoint(id=47, version=1, score=0.52936536, payload={'description': '5pack iPhone Charger Lightning Cables for Phone 13 13pro Max 12 Mini 11 Se 10 X Xr Xs 8 7 6 6s, Apple Certified Original Braided Cord Multi-Color Lightening Wire Fast Charging Cargador Chord-3 6 10 FtAPPLE MFI CERTIFIED - Made with original Apple MFI Chip, full support with iOS versions. High quality, pull-resistance, fast charging, and transmission.USB A TO LIGHTNING - USB-A to USB-Lightning port cable matches with USB A Wall charger. you can charge your iPhone, iPad, iPod. But not fit for android micro or type c port phones. 【Please make sure this is not a USB-C to LIGHTNING charging cord】UNIVERSAL COMPATIBILITY - Durable braided lightning cords are fully compatible with Apple iPhone 14 Pro Max, 14 Plus, 14 Pro, 14, 13 Pro Max, 13 Pro, 13, 13 mini, 12 Pro Max, 12 Pro, 12, 12 mini, SE, 11 Pro Max, 11 Pro, 11, XS Max, XS, XR, X, 8Plus, 8, 7 Plus, 7, SE, 6s Plus, 6s, 6Plus, 6; iPad 10.2 (2021), iPad 10.2 (2020), iPad 10.2 (2019), iPad 9.7 (2018), iPad 9.7 (2017); iPod nano, iPod touch, Airpods pro, etc.CONVENIENT CABLE SITS - These long Lighting cords allow you to adjust cable 3-6ft length for any situation. easy to get back seat in the car, charging far from bed or sofa, or office desk, power bank. 5pack cables offer you more convenient on traveling, office, car, power bank, several cell phones, share to families.PACKAGE INCLUDED - 5Pack-3/3/6/6/10FT USB lightening Cables(White, Blue, Green, Purple, Pink), our worry-free 1 year warranty, and 24/7 friendly customer service.', 'image': 'https://m.media-amazon.com/images/I/51VpGptP1UL.jpg', 'rating_number': 204, 'price': 13.99, 'average_rating': 4.5, 'parent_asin': 'B0BPLX388R'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=12, version=1, score=0.4839719, payload={'description': '【Apple MFi Certified】iPhone 14 13 Charger Fast Charging, 2 Pack PD 20W USB C iPhone Charger Fast Charging Block with 10FT Long Type C to Lightning Quick Charger Cable for iPhone 14 13 12 11 XS XR X 8【3 Pack 10FT Long iPhone Charger Fast Charging Cord】 The iPhone fast charger cables 10 ft MFi Certified equipped with the latest C94 terminal and MFi Chip, ensures 100% perfect compatibility with lightning devices and 480 Mbps data transfer speed. Tangle-free 10 Feet length is convenient for usage while charging and syncing at home/office/travel in bed, hotel rooms, and more.【Type C Fast Charger for iPhone】 The 10 ft iPhone Charger Fast Charging equipped with 20W PD 3.0 USB Type C power delivery wall plug, PD 3.0 Quick-Charge USB C port provides Max 20W output power. This iPhone charger 10 ft fast charging your iPhone 14 Pro Max up to 50% in just 30mins, 3X faster than the original 5W iPhone chargers, saves more than 1.5 hour for you.【Universal Compatibility】 3 Pack Long iPhone Fast Charger Block and Cable 10 ft to fast charge for iPhone 14/14 Plus/14 Pro/14 Pro Max/13/13 Mini/13 Pro/13 Pro Max/12/12 Mini/12 Pro/12 Pro Max/11/11 Pro/11 Pro Max/XS/XS Max/XR/X/8/8 Plus, iPad Pro/Air/Mini, AirPods Pro and more. This iPhone 14 charger 10 ft also charges iPhone 7/7 Plus/6s/6s Plus/6/6 Plus/SE/5s/5/5c with standard charging speed.【Safety Efficient Fast Charging】 20W Long Lightning charger for iPhone 10 ft has a multipotent safety system that ensures complete protection for your lightning devices. The UL-certified iPhone 14 Pro Max charger fast charging has built-in over-voltage protection and features a stable voltage. The 10 ft iPhone 14 charger cord built-in smart chip to match the current required by devices automatically.【What You Get】 3 Pack 20W USB-C iPhone Charger Fast Charging Blocks and 3 Pack 10FT Long MFi Certified USB C to Lightning Fast Charging Data Sync Cables. We also provide a 5-year Worry-free Warranty and lifetime-friendly customer service. Any problems with this iPhone charger 10 ft fast charging, please contact us for fast support, we will reply within 12 hours.', 'image': 'https://m.media-amazon.com/images/I/41cL3J3dPbL._AC_.jpg', 'rating_number': 103, 'price': 15.99, 'average_rating': 4.8, 'parent_asin': 'B0CFG7V2QX'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=15, version=1, score=0.44170773, payload={'description': 'Aioneus USB A to Type C Charger Cable 10ft 3Pack, Long USB C Fast Charging Cord Braided for Samsung Galaxy S22 S21 S20 S10 S9 A03s A12 A13 A20 A21 A32 A42 A50 A51 A53 A71 S10e A10e, Moto G7 G6, LG【What You Get】: Aioneus 3Pack 10ft USB C Cable (Blue,Orange,Green) with 18 months worry-free Replacement and 24/7 customer service, if you have any questions,we will resolve your issue within 24 hours【3A Fast Charging & Sync】: Aioneus 10ft USB C Charger Cord (Blue, Orange, Green) enables the cable to provide the fastest possible charging speed, up to3A(Max). Data syncing speed up to480Mbps. 56KΩ resistor provides outstandingly reliable conductivity and stability to protect your devices and charging adapters from damage.【Wide Compatible 】10ft USB C Cable for Samsung Galaxy A10e /A02s/A03s/A01/A11/A12/A13/A20/A20s/A21/A21s/A30/A31/A32/A30s/A40/A41/A42/A50/A50s /A51/A70/A71/S22/S22 Ultra /S20 FE/ S21/ S21 Ultra /S20/S20 Ultra /S21/S19/S11/S8 S9 S10 plus /S10e/Note 8 9 10 20/20Ultra/ Z Fold 3/Tab S6/S5E; Motorola g power /g stylus / g9/ g8 / g7/g7 power /g7 play/g7plus/ Z/Z3/Z4/ X4; LG Velvet /K51/G7/G8/G9/Stylo 4/5/6/V20/ V30/V40 / V50/ V60 /Rebel 4/PS5 Controller and more【Durable and Heavy Duty Nylon Braided】: Double-braided nylon fiber and a premium TPE material prevents it from breaking due to excessive use which greatly prolongs its lifespan. It has passed 10,000 bending tests and can easily withstand daily use.【 3Pack 10ft USB C Cable】: 10FT type c charger cable is suitable for most occasions, such as home, office, and car, making your life more convenient. With a extal long usb c charger cable, you can use your device in any position, like sitting, lying, or standing.', 'image': 'https://m.media-amazon.com/images/I/51MAyDKv+PL._AC_.jpg', 'rating_number': 41057, 'price': 10.99, 'average_rating': 4.5, 'parent_asin': 'B0C7Q3X76Q'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=19, version=1, score=0.39772436, payload={'description': 'Tower Power Strip with 12 Outlets 4 USB Chargers, AOFO Surge Protector Charging Station with Overload Protection, Widely Spaced Multiple Outlets 10Ft Long Extension Cord for Home, Dorm & OfficeSpace-saving unique tower design: AOFO charging station adopts a unique vertical design, and the top adopts a delicate CD pattern design, so that your power strip are not monotonous, and you do not need to worry about the large plugs blocking each other, which helps you save space and is beautiful . Choose this office supply to keep your desktop clean and beautiful.Multi-Outlet Power Strip Tower: The surge protector power strip tower has 12 widely spaced AC outlets and 4 USB ports, the multi-outlet plug tower supports a wide voltage of 100V-250V, with 10A heavy duty 15 Feet extension cord is rated at 1250W ~ 125V . The total of 4 USB ports is 5V/3.4A (Max 5V/2.4A per port) fast charge your electronic devices.Fireproof material is trusted:The main body uses PC resin material with the highest flame resistance and high quality copper conductor, and has sufficient insulation resistance and durability. Effective for preventing electric fire. it is very safe to use.10 Feet Long Extension Cord :This multi plug outlet tower power strip has a 10-foot long cord. Extension cables are flexible enough that you can reach far away outlets.Multiple Safety Protection: A breaker reset button is provided for safety of electricity use. Protects your power strips and devices in use by automatically powering them off with a temporary output overage. You can use it with confidence.', 'image': 'https://m.media-amazon.com/images/I/41Qvznkpg7L._AC_.jpg', 'rating_number': 727, 'price': 29.99, 'average_rating': 4.7, 'parent_asin': 'B0BMWYT154'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=31, version=1, score=0.3645822, payload={'description': 'SaiTech IT 4 Pack (50cm – 1.5 feet) Short USB 2.0 Extension Cable, USB 2.0 A Male to Female High Speed USB Extension Cord - BlackLENGTH - 50 cm. USB 2.0 A-Male to A-Female high-speed extension cableExtends your USB connection to your computer; for use with printers, cameras, mice, keyboards and other USB computer peripheralsConstructed with corrosion-resistant, nickel-plated connectors for optimal signal clarity and shielding to minimize interferenceFeatures shielding that provides protection against noise from electromagnetic and radio-frequency signals, keeping your signal clear with less loss of bandwidth for higher performanceTypically, the Male A connector plugs into your computer and the Female A connects to the cable you need extended. Check your device manuals to make sure this is the connector you need', 'image': 'https://m.media-amazon.com/images/I/41Uw5bF0L2L._AC_.jpg', 'rating_number': 534, 'price': 9.39, 'average_rating': 4.6, 'parent_asin': 'B0BV276QMH'}, vector=None, shard_key=None, order_value=None)]
Outside function: points=[ScoredPoint(id=47, version=1, score=0.52936536, payload={'description': '5pack iPhone Charger Lightning Cables for Phone 13 13pro Max 12 Mini 11 Se 10 X Xr Xs 8 7 6 6s, Apple Certified Original Braided Cord Multi-Color Lightening Wire Fast Charging Cargador Chord-3 6 10 FtAPPLE MFI CERTIFIED - Made with original Apple MFI Chip, full support with iOS versions. High quality, pull-resistance, fast charging, and transmission.USB A TO LIGHTNING - USB-A to USB-Lightning port cable matches with USB A Wall charger. you can charge your iPhone, iPad, iPod. But not fit for android micro or type c port phones. 【Please make sure this is not a USB-C to LIGHTNING charging cord】UNIVERSAL COMPATIBILITY - Durable braided lightning cords are fully compatible with Apple iPhone 14 Pro Max, 14 Plus, 14 Pro, 14, 13 Pro Max, 13 Pro, 13, 13 mini, 12 Pro Max, 12 Pro, 12, 12 mini, SE, 11 Pro Max, 11 Pro, 11, XS Max, XS, XR, X, 8Plus, 8, 7 Plus, 7, SE, 6s Plus, 6s, 6Plus, 6; iPad 10.2 (2021), iPad 10.2 (2020), iPad 10.2 (2019), iPad 9.7 (2018), iPad 9.7 (2017); iPod nano, iPod touch, Airpods pro, etc.CONVENIENT CABLE SITS - These long Lighting cords allow you to adjust cable 3-6ft length for any situation. easy to get back seat in the car, charging far from bed or sofa, or office desk, power bank. 5pack cables offer you more convenient on traveling, office, car, power bank, several cell phones, share to families.PACKAGE INCLUDED - 5Pack-3/3/6/6/10FT USB lightening Cables(White, Blue, Green, Purple, Pink), our worry-free 1 year warranty, and 24/7 friendly customer service.', 'image': 'https://m.media-amazon.com/images/I/51VpGptP1UL.jpg', 'rating_number': 204, 'price': 13.99, 'average_rating': 4.5, 'parent_asin': 'B0BPLX388R'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=12, version=1, score=0.4839719, payload={'description': '【Apple MFi Certified】iPhone 14 13 Charger Fast Charging, 2 Pack PD 20W USB C iPhone Charger Fast Charging Block with 10FT Long Type C to Lightning Quick Charger Cable for iPhone 14 13 12 11 XS XR X 8【3 Pack 10FT Long iPhone Charger Fast Charging Cord】 The iPhone fast charger cables 10 ft MFi Certified equipped with the latest C94 terminal and MFi Chip, ensures 100% perfect compatibility with lightning devices and 480 Mbps data transfer speed. Tangle-free 10 Feet length is convenient for usage while charging and syncing at home/office/travel in bed, hotel rooms, and more.【Type C Fast Charger for iPhone】 The 10 ft iPhone Charger Fast Charging equipped with 20W PD 3.0 USB Type C power delivery wall plug, PD 3.0 Quick-Charge USB C port provides Max 20W output power. This iPhone charger 10 ft fast charging your iPhone 14 Pro Max up to 50% in just 30mins, 3X faster than the original 5W iPhone chargers, saves more than 1.5 hour for you.【Universal Compatibility】 3 Pack Long iPhone Fast Charger Block and Cable 10 ft to fast charge for iPhone 14/14 Plus/14 Pro/14 Pro Max/13/13 Mini/13 Pro/13 Pro Max/12/12 Mini/12 Pro/12 Pro Max/11/11 Pro/11 Pro Max/XS/XS Max/XR/X/8/8 Plus, iPad Pro/Air/Mini, AirPods Pro and more. This iPhone 14 charger 10 ft also charges iPhone 7/7 Plus/6s/6s Plus/6/6 Plus/SE/5s/5/5c with standard charging speed.【Safety Efficient Fast Charging】 20W Long Lightning charger for iPhone 10 ft has a multipotent safety system that ensures complete protection for your lightning devices. The UL-certified iPhone 14 Pro Max charger fast charging has built-in over-voltage protection and features a stable voltage. The 10 ft iPhone 14 charger cord built-in smart chip to match the current required by devices automatically.【What You Get】 3 Pack 20W USB-C iPhone Charger Fast Charging Blocks and 3 Pack 10FT Long MFi Certified USB C to Lightning Fast Charging Data Sync Cables. We also provide a 5-year Worry-free Warranty and lifetime-friendly customer service. Any problems with this iPhone charger 10 ft fast charging, please contact us for fast support, we will reply within 12 hours.', 'image': 'https://m.media-amazon.com/images/I/41cL3J3dPbL._AC_.jpg', 'rating_number': 103, 'price': 15.99, 'average_rating': 4.8, 'parent_asin': 'B0CFG7V2QX'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=15, version=1, score=0.44170773, payload={'description': 'Aioneus USB A to Type C Charger Cable 10ft 3Pack, Long USB C Fast Charging Cord Braided for Samsung Galaxy S22 S21 S20 S10 S9 A03s A12 A13 A20 A21 A32 A42 A50 A51 A53 A71 S10e A10e, Moto G7 G6, LG【What You Get】: Aioneus 3Pack 10ft USB C Cable (Blue,Orange,Green) with 18 months worry-free Replacement and 24/7 customer service, if you have any questions,we will resolve your issue within 24 hours【3A Fast Charging & Sync】: Aioneus 10ft USB C Charger Cord (Blue, Orange, Green) enables the cable to provide the fastest possible charging speed, up to3A(Max). Data syncing speed up to480Mbps. 56KΩ resistor provides outstandingly reliable conductivity and stability to protect your devices and charging adapters from damage.【Wide Compatible 】10ft USB C Cable for Samsung Galaxy A10e /A02s/A03s/A01/A11/A12/A13/A20/A20s/A21/A21s/A30/A31/A32/A30s/A40/A41/A42/A50/A50s /A51/A70/A71/S22/S22 Ultra /S20 FE/ S21/ S21 Ultra /S20/S20 Ultra /S21/S19/S11/S8 S9 S10 plus /S10e/Note 8 9 10 20/20Ultra/ Z Fold 3/Tab S6/S5E; Motorola g power /g stylus / g9/ g8 / g7/g7 power /g7 play/g7plus/ Z/Z3/Z4/ X4; LG Velvet /K51/G7/G8/G9/Stylo 4/5/6/V20/ V30/V40 / V50/ V60 /Rebel 4/PS5 Controller and more【Durable and Heavy Duty Nylon Braided】: Double-braided nylon fiber and a premium TPE material prevents it from breaking due to excessive use which greatly prolongs its lifespan. It has passed 10,000 bending tests and can easily withstand daily use.【 3Pack 10ft USB C Cable】: 10FT type c charger cable is suitable for most occasions, such as home, office, and car, making your life more convenient. With a extal long usb c charger cable, you can use your device in any position, like sitting, lying, or standing.', 'image': 'https://m.media-amazon.com/images/I/51MAyDKv+PL._AC_.jpg', 'rating_number': 41057, 'price': 10.99, 'average_rating': 4.5, 'parent_asin': 'B0C7Q3X76Q'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=19, version=1, score=0.39772436, payload={'description': 'Tower Power Strip with 12 Outlets 4 USB Chargers, AOFO Surge Protector Charging Station with Overload Protection, Widely Spaced Multiple Outlets 10Ft Long Extension Cord for Home, Dorm & OfficeSpace-saving unique tower design: AOFO charging station adopts a unique vertical design, and the top adopts a delicate CD pattern design, so that your power strip are not monotonous, and you do not need to worry about the large plugs blocking each other, which helps you save space and is beautiful . Choose this office supply to keep your desktop clean and beautiful.Multi-Outlet Power Strip Tower: The surge protector power strip tower has 12 widely spaced AC outlets and 4 USB ports, the multi-outlet plug tower supports a wide voltage of 100V-250V, with 10A heavy duty 15 Feet extension cord is rated at 1250W ~ 125V . The total of 4 USB ports is 5V/3.4A (Max 5V/2.4A per port) fast charge your electronic devices.Fireproof material is trusted:The main body uses PC resin material with the highest flame resistance and high quality copper conductor, and has sufficient insulation resistance and durability. Effective for preventing electric fire. it is very safe to use.10 Feet Long Extension Cord :This multi plug outlet tower power strip has a 10-foot long cord. Extension cables are flexible enough that you can reach far away outlets.Multiple Safety Protection: A breaker reset button is provided for safety of electricity use. Protects your power strips and devices in use by automatically powering them off with a temporary output overage. You can use it with confidence.', 'image': 'https://m.media-amazon.com/images/I/41Qvznkpg7L._AC_.jpg', 'rating_number': 727, 'price': 29.99, 'average_rating': 4.7, 'parent_asin': 'B0BMWYT154'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=31, version=1, score=0.3645822, payload={'description': 'SaiTech IT 4 Pack (50cm – 1.5 feet) Short USB 2.0 Extension Cable, USB 2.0 A Male to Female High Speed USB Extension Cord - BlackLENGTH - 50 cm. USB 2.0 A-Male to A-Female high-speed extension cableExtends your USB connection to your computer; for use with printers, cameras, mice, keyboards and other USB computer peripheralsConstructed with corrosion-resistant, nickel-plated connectors for optimal signal clarity and shielding to minimize interferenceFeatures shielding that provides protection against noise from electromagnetic and radio-frequency signals, keeping your signal clear with less loss of bandwidth for higher performanceTypically, the Male A connector plugs into your computer and the Female A connects to the cable you need extended. Check your device manuals to make sure this is the connector you need', 'image': 'https://m.media-amazon.com/images/I/41Uw5bF0L2L._AC_.jpg', 'rating_number': 534, 'price': 9.39, 'average_rating': 4.6, 'parent_asin': 'B0BV276QMH'}, vector=None, shard_key=None, order_value=None)]
<class 'qdrant_client.http.models.models.QueryResponse'>

In [71]:
result.points[0]

ScoredPoint(id=47, version=1, score=0.5293168, payload={'description': '5pack iPhone Charger Lightning Cables for Phone 13 13pro Max 12 Mini 11 Se 10 X Xr Xs 8 7 6 6s, Apple Certified Original Braided Cord Multi-Color Lightening Wire Fast Charging Cargador Chord-3 6 10 FtAPPLE MFI CERTIFIED - Made with original Apple MFI Chip, full support with iOS versions. High quality, pull-resistance, fast charging, and transmission.USB A TO LIGHTNING - USB-A to USB-Lightning port cable matches with USB A Wall charger. you can charge your iPhone, iPad, iPod. But not fit for android micro or type c port phones. 【Please make sure this is not a USB-C to LIGHTNING charging cord】UNIVERSAL COMPATIBILITY - Durable braided lightning cords are fully compatible with Apple iPhone 14 Pro Max, 14 Plus, 14 Pro, 14, 13 Pro Max, 13 Pro, 13, 13 mini, 12 Pro Max, 12 Pro, 12, 12 mini, SE, 11 Pro Max, 11 Pro, 11, XS Max, XS, XR, X, 8Plus, 8, 7 Plus, 7, SE, 6s Plus, 6s, 6Plus, 6; iPad 10.2 (2021), iPad 10.2 (2020), iPad 10.2 (2019), iPad 9.7 (2018), iPad 9.7 (2017); iPod nano, iPod touch, Airpods pro, etc.CONVENIENT CABLE SITS - These long Lighting cords allow you to adjust cable 3-6ft length for any situation. easy to get back seat in the car, charging far from bed or sofa, or office desk, power bank. 5pack cables offer you more convenient on traveling, office, car, power bank, several cell phones, share to families.PACKAGE INCLUDED - 5Pack-3/3/6/6/10FT USB lightening Cables(White, Blue, Green, Purple, Pink), our worry-free 1 year warranty, and 24/7 friendly customer service.', 'image': 'https://m.media-amazon.com/images/I/51VpGptP1UL.jpg', 'rating_number': 204, 'price': 13.99, 'average_rating': 4.5, 'parent_asin': 'B0BPLX388R'}, vector=None, shard_key=None, order_value=None)