### Import Dependencise

In [8]:
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams,Distance,PayloadSchemaType,PointStruct,SparseVectorParams,Document,Prefetch,FusionQuery
from qdrant_client import models
import pandas as pd
from openai import OpenAI
import fastembed
import os

c:\Users\jaysi\Desktop\Desktop\Ai-engineering\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [46]:
import openai

In [9]:
client=OpenAI()

In [8]:
QDRANT_URL = os.getenv("QDRANT_URL", "http://localhost:6333")

### Create Quadrant Collection For Hybrid Collection

In [70]:
quadrant_client=QdrantClient(url="http://localhost:6333/")

In [ ]:
quadrant_client.create_collection(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    vectors_config={
        "text-embedding-model-3-small":VectorParams(size=1536,distance=Distance.COSINE)
    }
    ,
    sparse_vectors_config={
        "bm25":SparseVectorParams(modifier=models.Modifier.IDF)
    }
)

In [11]:
def get_embedding(text,model="text-embedding-3-small"):
    response=openai.embeddings.create(
        input=[text],
        model=model
    )
    return response.data[0].embedding

In [44]:
def get_embedding_batch(text_list,model="text-embedding-3-small",batch_size=100):
    if len(text_list)<=batch_size:
        response=openai.embeddings.create(input=text_list,model=model)
        return [embedding.embedding for embedding in response.data]

    all_embeddings=[]
    counter=1
    for i in range(0,len(text_list),batch_size):
        batch=text_list[i:i+batch_size]
        response=openai.embeddings.create(input=batch,model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        counter+=1
    
    return all_embeddings

### Preprocesse Amazon data

In [12]:
df_items=pd.read_json("C:\\Users\\jaysi\\Desktop\\Desktop\\Ai-engineering\\data\\meta_Electronics_2022_23_with_categeory_rating_100_sample_2000.jsonl",lines=True)

In [13]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,[],4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN
2,All Electronics,USB C Docking Station Dual Monitor for MacBook...,3.9,1193,[【18-in-1Docking Station】With USB C Docking St...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ZMUIPNG,"[Electronics, Computers & Accessories, Laptop ...","{'Product Dimensions': '3.94""L x 1.18""W x 3.94...",B09SFN9NRX,NaN,NaN,NaN
3,Camera & Photo,[2023 Upgraded] Telescopes for Adults Astronom...,4.1,219,[🎁【2023 All New Experience】The newly upgraded ...,[],169.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Good picture quality', 'url': 'htt...",HUTACT,"[Electronics, Camera & Photo, Binoculars & Sco...","{'Product Dimensions': '32.5""D x 5.5""W x 9.7""H...",B09TP3SZ7C,NaN,NaN,NaN
4,AMAZON FASHION,"Laptop Bag 15.6 Inch, Laptop Briefcase Messeng...",4.5,222,"[Leather,Mesh, Imported, Multi-pockets and Lar...",[],24.95,[{'thumb': 'https://m.media-amazon.com/images/...,[],KPIQIU,"[Electronics, Computers & Accessories, Laptop ...",{'Product Dimensions': '16 x 2 x 12 inches; 1....,B0B5H7T7XZ,NaN,NaN,NaN

In [14]:
def preprocessed_decription(row):
    return f"{row['title']}{''.join(row['features'])}"

In [15]:
def extrect_first_large_image(row):
    return row['images'][0].get("large","")

In [16]:
df_items['description']=df_items.apply(preprocessed_decription,axis=1)
df_items['image']=df_items.apply(extrect_first_large_image,axis=1)

In [32]:
df_items

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,image
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51G07yWoOB...
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41bOA5-ogW...
2,All Electronics,USB C Docking Station Dual Monitor for MacBook...,3.9,1193,[【18-in-1Docking Station】With USB C Docking St...,USB C Docking Station Dual Monitor for MacBook...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ZMUIPNG,"[Electronics, Computers & Accessories, Laptop ...","{'Product Dimensions': '3.94""L x 1.18""W x 3.94...",B09SFN9NRX,NaN,NaN,NaN,https://m.media-amazon.com/images/I/416IzmVKiC...
3,Camera & Photo,[2023 Upgraded] Telescopes for Adults Astronom...,4.1,219,[🎁【2023 All New Experience】The newly upgraded ...,[2023 Upgraded] Telescopes for Adults Astronom...,169.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Good picture quality', 'url': 'htt...",HUTACT,"[Electronics, Camera & Photo, Binoculars & Sco...","{'Product Dimensions': '32.5""D x 5.5""W x 9.7""H...",B09TP3SZ7C,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41wO4J3TT0...
4,AMAZON FASHION,"Laptop Bag 15.6 Inch, Laptop Briefcase Messeng...",4.5,222,"[Leather,Mesh, Imported, Multi-pockets and Lar...","Laptop Bag 15.6 Inch, Laptop Briefcase Messeng...",24.95,[{'thumb': 'https://m.media-amazon.com/images/...,[],KPIQIU,"[Electronics, Computers & Accessories, Laptop ...",{'Product Dimensions': '16 x 2 x 12 inches; 1....,B0B5H7T7XZ,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41mwlYqT5p...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Office Products,"WALI Single Monitor Stand, Adjustable Gas Spri...",4.2,210,[Compatibility: The single monitor arm fits mo...,"WALI Single Monitor Stand, Adjustable Gas Spri...",47.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'WALI Single Monitor Stand White (G...,WALI,"[Electronics, Computers & Accessories, Compute...","{'Manufacturer': 'WALI', 'Brand': 'WALI', 'Ite...",B09RTDQ8LZ,NaN,NaN,NaN,https://m.media-amazon.com/images/I/31acj+ZylJ...
1996,Industrial & Scientific,"ARESGAME CPU Air Cooler for Intel/AMD, with 5 ...",4.6,1252,[Universal Socket Compatibility: Intel LGA775/...,"ARESGAME CPU Air Cooler for Intel/AMD, with 5 ...",58.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': '4 Heat-pipes CPU Air Cooler-CR1400...,ARESGAME,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'ARESGAME', 'Power Connector Type': ...",B0B6FBGY9H,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41fIjMB-WZ...
1997,All Electronics,BenQ TH585P 1080p Home Entertainment Projector...,4.5,327,[1080P RESOLUTION: 1080p Full HD image quality...,BenQ TH585P 1080p Home Entertainment Projector...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'TH671ST - Low Input Lag', 'url': '...",BenQ,"[Electronics, Video Projectors]",{'Product Dimensions': '18.1 x 13.5 x 7 inches...,B09WF96S4C,NaN,NaN,NaN,https://m.media-amazon.com/images/I/31twaVX106...
1998,Industrial & Scientific,Meboyz 3 Pack 100W USB C to USB C Cable 10ft+6...,4.6,561,[【5A Rapid Charging】 ： The 5A/20V 100W PD tech...,Meboyz 3 Pack 100W USB C to USB C Cable 10ft+6...,13.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Highly recommend the product.', 'u...",Meboyz,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'Meboyz', 'Connector Type': 'USB Typ...",B0BN2WQ1DX,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51fnwdRm3p...
1999,AMAZON FASHION,"Hp hope Smart Backpack for Women Travel, Durab...",4.5,339,"[polyester, Made in the USA or Imported, Nylon...","Hp hope Smart Backpack for Women Travel, Durab...",79.58,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': ' Hp hope Smart Backpack for Women ...,Hp hope,"[Electronics, Computers & Accessories, Laptop ...",{'Product Dimensions': '7 x 11.8 x 16.5 inches...,B09WDPZYX7,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41iUewswGx...

In [33]:
data_to_embed=df_items[["description","image","rating_number","price","average_rating","parent_asin"]].to_dict(orient="records")

In [37]:
data_to_embed[0]['description']

"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB Type C Fast Charging Cord - Nylon Braided USB C Charger Cable for Galaxy A20/A50/S10/S9/S8+/S8, iPad Pro 2018, Sony XZ, HTC 10, OnePlus 5T, Huawei P9 etc.【Fast Charging Cord】These USB C cables provide up to a 3A charging current to greatly shorten the charging time, meets QC2.0 /3.0 fast charging protocol,Incredibly charge your phone from 0 to 80% in 50 minute. 480Mbps (40-60M/s) ultra fast data transmission, which leads to a faster data sync.(Note:Cables support fast charging,but require a USB-A QC3.0/QC2.0/AFC charger)【Universal Compatibility】The USB C Charger Cable is compatible with Samsung Galaxy S20 / S10 / S9 / S8+ / S8 / A02s / A03s,A12 A20 A21 A22 A23 A31 A32 A33 A41 A42 A50 A52 A52s 5G A71 A72 A73,M11 M21 M31 M51,M12 M22 M32 M52,iPad Pro 2018 / 2020,Sony Xperia XZ/X Compact/L1 / XZs / XA1 / X Premium, HTC 10 LG G5 G6,OnePlus 5T / 6T, Lumia 950 / 950XL,Huawei P9 P9 Plus P10 P10 Plus Honor Mate 9 Mate 9 pro Mate 10 pro Mate 10 lite and more【Premium Workmanship】Unique increased friction design allows you to easily unplug the cable from your charger,combine 250d bulletproof fiber core to build a cable so durable that will save your time and money.【Unbreakable Nylon Braided Cord】Premium nylon braided build a cable so durable that will outlast your phone.【What You Get】(2pack 3.3ft+6.6ft) USB A to USB C Cable with 18-Month free Warranty. If you have any questions, please don't to hesitate to contact us, we will give you a satisfied solution within 24 hours."

In [38]:
text_to_embed=[data["description"] for data in data_to_embed]

In [59]:
len(text_to_embed)

2000

In [ ]:
embeddings = get_embedding_batch(text_to_embed)

In [60]:
len(embedding)

1536

In [64]:
embedding

[0.037017822265625,
 -0.005466461181640625,
 -0.02996826171875,
 0.0200653076171875,
 0.0010128021240234375,
 -0.059295654296875,
 -0.005069732666015625,
 0.01007843017578125,
 0.03680419921875,
 -0.004947662353515625,
 -0.01247406005859375,
 0.023406982421875,
 -0.06396484375,
 -0.0243072509765625,
 0.006504058837890625,
 0.06024169921875,
 -0.0173492431640625,
 0.001476287841796875,
 -0.024444580078125,
 -0.02276611328125,
 -0.00363922119140625,
 0.06976318359375,
 0.0258331298828125,
 -0.03106689453125,
 0.005474090576171875,
 0.002216339111328125,
 -0.019866943359375,
 0.00975799560546875,
 0.0175628662109375,
 -0.018035888671875,
 0.00496673583984375,
 -0.030120849609375,
 0.03265380859375,
 -0.0469970703125,
 0.0210418701171875,
 0.038970947265625,
 0.00441741943359375,
 -0.0078277587890625,
 0.032196044921875,
 0.0139312744140625,
 0.040802001953125,
 0.0267486572265625,
 0.05718994140625,
 -0.07501220703125,
 0.0191192626953125,
 0.05322265625,
 -0.034149169921875,
 0.01233673095703125,
 0.01139068603515625,
 0.0173187255859375,
 -0.036224365234375,
 0.0130767822265625,
 0.0074615478515625,
 0.0318603515625,
 -0.037689208984375,
 -0.0228271484375,
 0.0174407958984375,
 -0.00719451904296875,
 0.0123138427734375,
 0.03167724609375,
 0.00588226318359375,
 -0.00775909423828125,
 -0.01499176025390625,
 0.01209259033203125,
 -0.01357269287109375,
 -0.027496337890625,
 -0.017852783203125,
 -0.0002624988555908203,
 -0.07550048828125,
 -0.01177215576171875,
 0.039581298828125,
 0.0275115966796875,
 0.0309906005859375,
 -0.03228759765625,
 -0.0162200927734375,
 0.0079193115234375,
 0.024444580078125,
 -0.0133209228515625,
 0.029144287109375,
 0.01377105712890625,
 -0.045135498046875,
 0.0112152099609375,
 -0.02642822265625,
 0.007381439208984375,
 -0.017974853515625,
 0.0325927734375,
 -0.05902099609375,
 -0.047332763671875,
 -0.045806884765625,
 -0.01412200927734375,
 0.01540374755859375,
 0.033538818359375,
 0.04083251953125,
 0.0030059814453125,
 -0.006931304931640625,
 0.0111846923828125,
 -0.0034770965576171875,
 -0.019744873046875,
 -0.026641845703125,
 0.025054931640625,
 0.03314208984375,
 0.022613525390625,
 -0.01554107666015625,
 -0.005023956298828125,
 -0.01837158203125,
 -0.01265716552734375,
 -0.031585693359375,
 -0.018646240234375,
 -0.007801055908203125,
 0.02203369140625,
 -0.10699462890625,
 -0.0006647109985351562,
 -0.030242919921875,
 -0.0018072128295898438,
 0.0128021240234375,
 -0.04998779296875,
 0.017120361328125,
 0.006053924560546875,
 -0.0009708404541015625,
 0.001316070556640625,
 -0.0254058837890625,
 0.028106689453125,
 0.0034332275390625,
 -0.029052734375,
 -0.0229644775390625,
 -0.0045166015625,
 -0.0182037353515625,
 0.0180511474609375,
 -0.0455322265625,
 -0.004749298095703125,
 -0.000919342041015625,
 -0.006805419921875,
 0.035247802734375,
 -0.03155517578125,
 0.0195159912109375,
 -0.035308837890625,
 -0.007381439208984375,
 -0.017303466796875,
 0.01629638671875,
 -0.027496337890625,
 0.0238189697265625,
 -0.029296875,
 0.0261077880859375,
 0.0194549560546875,
 -0.0129852294921875,
 0.04168701171875,
 0.036865234375,
 0.048828125,
 0.004650115966796875,
 0.11370849609375,
 -0.0284576416015625,
 -0.003086090087890625,
 0.00799560546875,
 0.020416259765625,
 0.0149688720703125,
 -0.0224761962890625,
 0.0304412841796875,
 0.059326171875,
 -0.0301971435546875,
 0.01256561279296875,
 -0.00913238525390625,
 0.042938232421875,
 -0.032989501953125,
 -0.0155181884765625,
 0.0225677490234375,
 0.038116455078125,
 0.028472900390625,
 -0.0745849609375,
 -0.08245849609375,
 -0.04937744140625,
 -0.0128021240234375,
 -0.046722412109375,
 -0.0016193389892578125,
 0.02838134765625,
 0.0364990234375,
 -0.018890380859375,
 0.004352569580078125,
 0.0214996337890625,
 0.0039825439453125,
 0.0050048828125,
 -0.0430908203125,
 -0.005710601806640625,
 -0.011260986328125,
 -0.051544189453125,
 -0.0230560302734375,
 -0.0021572113037109375,
 -0.0046844482421875,
 -0.01238250732421875,
 -0.0110931396484375,
 -0.0171661376953125,
 -0.0060577392578125,
 -0.0094757080078125,
 -0.01983642578125,
 -0.0245819091796875,
 -0.04541015625,
 -0.027557373046875,
 -0.005786895751953125,
 0.025787353515625,
 0.0011663436889648438,
 0.0024890899658203125,
 -0.01537322998046875,
 -0.0095977783203125,
 0.0167694091796875,
 -0.00312042236328125,
 -0.00917816162109375,
 0.006626129150390625,
 -0.0176239013671875,
 0.0163726806640625,
 0.0631103515625,
 -0.042877197265625,
 0.06597900390625,
 -0.0032901763916015625,
 -0.0292816162109375,
 -0.0092010498046875,
 0.0421142578125,
 -0.00920867919921875,
 -0.03436279296875,
 0.02239990234375,
 0.0025348663330078125,
 -0.034332275390625,
 -0.0340576171875,
 0.0171966552734375,
 0.004245758056640625,
 0.0157928466796875,
 0.007617950439453125,
 -0.032501220703125,
 -0.0036716461181640625,
 -0.03533935546875,
 -0.0367431640625,
 -0.037109375,
 -0.055084228515625,
 0.01288604736328125,
 -0.0160064697265625,
 -0.0154876708984375,
 0.039520263671875,
 -0.0229339599609375,
 0.032684326171875,
 -0.01091766357421875,
 -0.00504302978515625,
 0.00787353515625,
 0.01371002197265625,
 0.013214111328125,
 0.0050811767578125,
 0.0262908935546875,
 0.01142120361328125,
 -0.0292510986328125,
 -0.037384033203125,
 0.007678985595703125,
 -0.01898193359375,
 0.005756378173828125,
 0.041748046875,
 -0.0229339599609375,
 0.0200042724609375,
 -0.0185089111328125,
 0.032928466796875,
 0.0325927734375,
 -0.0240325927734375,
 0.037841796875,
 0.0265655517578125,
 -0.029052734375,
 -0.01270294189453125,
 0.0086212158203125,
 0.0219268798828125,
 0.00925445556640625,
 -0.017486572265625,
 -0.05108642578125,
 0.01416778564453125,
 0.002838134765625,
 0.0290985107421875,
 -0.04632568359375,
 0.0145721435546875,
 0.0538330078125,
 0.006374359130859375,
 0.0223388671875,
 -0.001102447509765625,
 -0.0019626617431640625,
 -0.016387939453125,
 -0.0099639892578125,
 0.0174407958984375,
 0.02276611328125,
 -0.00635528564453125,
 -0.02740478515625,
 0.0166015625,
 -0.01453399658203125,
 0.039825439453125,
 0.01959228515625,
 0.05328369140625,
 0.03448486328125,
 -0.030670166015625,
 -0.0230712890625,
 -0.005096435546875,
 -0.006195068359375,
 -0.01413726806640625,
 -0.003513336181640625,
 0.05072021484375,
 -0.0011501312255859375,
 -0.0186767578125,
 0.055755615234375,
 -0.0113067626953125,
 -0.0457763671875,
 0.0100860595703125,
 -0.0004210472106933594,
 0.02496337890625,
 -0.0024566650390625,
 -0.0274505615234375,
 0.0145111083984375,
 0.015838623046875,
 -0.036468505859375,
 -0.0305328369140625,
 0.036346435546875,
 -0.033172607421875,
 -0.017120361328125,
 0.00494384765625,
 -0.034454345703125,
 -0.03570556640625,
 -0.0333251953125,
 0.0006661415100097656,
 -0.0191650390625,
 -0.029296875,
 -0.054290771484375,
 0.0171051025390625,
 0.032379150390625,
 0.02874755859375,
 -0.0296630859375,
 0.0206298828125,
 -0.01517486572265625,
 0.044281005859375,
 0.0081939697265625,
 -0.00969696044921875,
 -0.019195556640625,
 -0.0009279251098632812,
 -0.04400634765625,
 -0.0128173828125,
 -0.061492919921875,
 0.0192413330078125,
 -0.031036376953125,
 -0.00853729248046875,
 0.0028018951416015625,
 0.000904083251953125,
 0.01233673095703125,
 0.01067352294921875,
 -0.056915283203125,
 -0.052947998046875,
 0.0234527587890625,
 0.027557373046875,
 -0.0142059326171875,
 0.08642578125,
 -0.0104217529296875,
 0.0016222000122070312,
 0.044189453125,
 0.024810791015625,
 0.0163421630859375,
 0.035400390625,
 -0.01270294189453125,
 -0.017425537109375,
 -0.03131103515625,
 0.0469970703125,
 -0.012847900390625,
 -0.0142974853515625,
 0.01001739501953125,
 0.0027065277099609375,
 0.026947021484375,
 0.0177764892578125,
 -0.012939453125,
 -0.004337310791015625,
 0.0556640625,
 -0.0248565673828125,
 0.033966064453125,
 -0.034698486328125,
 -0.01111602783203125,
 0.057861328125,
 0.04937744140625,
 0.05010986328125,
 -0.0095062255859375,
 -0.034271240234375,
 -0.004444122314453125,
 0.0112457275390625,
 0.0225067138671875,
 -0.022430419921875,
 -0.0118560791015625,
 0.02655029296875,
 0.0034332275390625,
 0.0249176025390625,
 0.016815185546875,
 0.0305328369140625,
 -0.00925445556640625,
 -0.006351470947265625,
 -0.0238189697265625,
 0.0308380126953125,
 -0.034027099609375,
 0.01105499267578125,
 0.004314422607421875,
 0.034637451171875,
 -0.024139404296875,
 0.023895263671875,
 0.0090179443359375,
 0.037994384765625,
 0.0037593841552734375,
 -0.032684326171875,
 -0.0272674560546875,
 -0.0009169578552246094,
 -0.03179931640625,
 -0.00304412841796875,
 -0.0306243896484375,
 0.01195526123046875,
 -0.032135009765625,
 0.0280609130859375,
 -0.0177459716796875,
 0.054656982421875,
 0.048980712890625,
 -0.0099334716796875,
 -0.0869140625,
 0.00901031494140625,
 -0.0175323486328125,
 0.028045654296875,
 0.003040313720703125,
 0.0154266357421875,
 0.0272674560546875,
 0.00853729248046875,
 -0.0338134765625,
 -0.002933502197265625,
 -0.0635986328125,
 -0.04510498046875,
 0.0031719207763671875,
 -0.0080413818359375,
 -0.0276336669921875,
 -0.00817108154296875,
 -0.066650390625,
 -0.047088623046875,
 -0.035064697265625,
 -0.04034423828125,
 0.0011453628540039062,
 0.05029296875,
 0.0209808349609375,
 -0.024627685546875,
 -0.0146942138671875,
 -0.005756378173828125,
 -0.0168304443359375,
 0.046112060546875,
 -0.0179595947265625,
 0.0396728515625,
 -0.031951904296875,
 -0.057098388671875,
 0.01195526123046875,
 0.0003237724304199219,
 -0.00730133056640625,
 0.0091400146484375,
 0.054107666015625,
 -0.0206146240234375,
 -0.04266357421875,
 -0.020538330078125,
 0.06280517578125,
 0.0176544189453125,
 -0.0037059783935546875,
 -0.0166778564453125,
 0.0159759521484375,
 -0.03192138671875,
 -0.04705810546875,
 -0.01239013671875,
 -0.005321502685546875,
 0.0701904296875,
 0.0362548828125,
 0.022430419921875,
 -0.014984130859375,
 0.004886627197265625,
 0.0038738250732421875,
 0.01146697998046875,
 -0.03369140625,
 0.030029296875,
 0.0257415771484375,
 -0.01384735107421875,
 0.0128631591796875,
 0.0176239013671875,
 0.0297088623046875,
 0.04034423828125,
 0.0010480880737304688,
 -0.00347900390625,
 0.02923583984375,
 -0.0311126708984375,
 -0.006366729736328125,
 -0.0088043212890625,
 0.00522613525390625,
 -0.061676025390625,
 -0.0263671875,
 -0.00675201416015625,
 -0.0005106925964355469,
 0.0274658203125,
 0.039459228515625,
 0.0239410400390625,
 -0.01085662841796875,
 -0.0183563232421875,
 -0.005756378173828125,
 0.03369140625,
 -0.009246826171875,
 -0.0196075439453125,
 -0.019775390625,
 -0.0008907318115234375,
 -0.037567138671875,
 0.0013093948364257812,
 -0.0123138427734375,
 0.0628662109375,
 -0.06842041015625,
 0.024139404296875,
 -0.0345458984375,
 0.038238525390625,
 0.00832366943359375,
 0.0259246826171875,
 -0.033477783203125,
 -0.0352783203125,
 0.0063323974609375,
 -0.05322265625,
 -0.040252685546875,
 0.0088043212890625,
 0.00420379638671875,
 -0.00604248046875,
 -0.03424072265625,
 0.037384033203125,
 0.01068878173828125,
 -0.033050537109375,
 -0.05657958984375,
 -0.0345458984375,
 0.014923095703125,
 -0.02099609375,
 -0.002429962158203125,
 -0.02685546875,
 -0.04742431640625,
 0.00223541259765625,
 -0.0888671875,
 -0.0214080810546875,
 0.019683837890625,
 -0.034515380859375,
 -0.00803375244140625,
 -0.0279998779296875,
 -0.04345703125,
 0.004581451416015625,
 0.00540924072265625,
 0.0267791748046875,
 -0.04541015625,
 -0.0111236572265625,
 0.006099700927734375,
 0.027099609375,
 0.01540374755859375,
 -0.027923583984375,
 -0.023712158203125,
 -0.0011453628540039062,
 -0.006866455078125,
 0.01296234130859375,
 -0.00447845458984375,
 -0.009368896484375,
 0.0006775856018066406,
 0.02325439453125,
 -0.0002849102020263672,
 0.02001953125,
 -0.036590576171875,
 0.0007495880126953125,
 -0.01187896728515625,
 0.004787445068359375,
 0.020843505859375,
 0.0157928466796875,
 -0.0029659271240234375,
 0.026153564453125,
 0.015655517578125,
 0.02191162109375,
 -0.0020046234130859375,
 0.0288238525390625,
 0.052398681640625,
 -0.0023365020751953125,
 -0.0152435302734375,
 -0.0284271240234375,
 -0.0274505615234375,
 -0.0074920654296875,
 -0.02001953125,
 -0.0007243156433105469,
 -0.0633544921875,
 0.040435791015625,
 0.0222930908203125,
 -0.033447265625,
 -0.0164337158203125,
 0.0022106170654296875,
 0.02471923828125,
 -0.03240966796875,
 0.005062103271484375,
 -0.004604339599609375,
 0.0206146240234375,
 -0.060302734375,
 -0.0052337646484375,
 0.037872314453125,
 -0.037567138671875,
 0.00707244873046875,
 0.052581787109375,
 -0.0103912353515625,
 -0.00992584228515625,
 -0.014556884765625,
 -0.007171630859375,
 -0.01197052001953125,
 0.017913818359375,
 -0.05230712890625,
 -0.0082550048828125,
 -0.0312042236328125,
 -0.02587890625,
 -0.0430908203125,
 -0.01354217529296875,
 0.0029201507568359375,
 0.0026302337646484375,
 -0.056854248046875,
 -0.0183258056640625,
 0.038909912109375,
 -0.020721435546875,
 0.01407623291015625,
 0.0245361328125,
 0.02423095703125,
 -0.0259552001953125,
 0.03594970703125,
 -0.00022494792938232422,
 -0.01348114013671875,
 0.06396484375,
 0.0005273818969726562,
 0.0164337158203125,
 0.0214996337890625,
 0.0051727294921875,
 -0.054931640625,
 -0.020843505859375,
 0.0210113525390625,
 0.0229949951171875,
 0.005649566650390625,
 0.013519287109375,
 -0.016448974609375,
 -0.053985595703125,
 0.0117034912109375,
 -0.0206298828125,
 -0.0184326171875,
 0.0131683349609375,
 0.0340576171875,
 -0.013214111328125,
 -0.00910186767578125,
 -0.00531005859375,
 -0.0110931396484375,
 0.00916290283203125,
 -0.00719451904296875,
 -0.016357421875,
 -0.03497314453125,
 -0.01058197021484375,
 0.027740478515625,
 -0.0430908203125,
 0.00569915771484375,
 0.0268096923828125,
 -0.011322021484375,
 -0.007503509521484375,
 -0.0022983551025390625,
 -0.02886962890625,
 0.032073974609375,
 0.01366424560546875,
 0.03167724609375,
 0.01480865478515625,
 0.005336761474609375,
 0.0283203125,
 0.004421234130859375,
 0.03424072265625,
 0.0058135986328125,
 0.011566162109375,
 -0.0304718017578125,
 0.021575927734375,
 -0.01003265380859375,
 0.00554656982421875,
 0.0162200927734375,
 -0.0027103424072265625,
 0.0179443359375,
 0.019622802734375,
 0.01277923583984375,
 0.0013103485107421875,
 0.025909423828125,
 0.005462646484375,
 0.055084228515625,
 -0.033111572265625,
 -0.0217742919921875,
 -0.0386962890625,
 -0.00792694091796875,
 -0.00099945068359375,
 0.0257720947265625,
 0.0247802734375,
 0.046051025390625,
 -0.0239105224609375,
 -0.02740478515625,
 0.01296234130859375,
 0.01166534423828125,
 0.03546142578125,
 -0.002410888671875,
 -0.01837158203125,
 0.01508331298828125,
 -0.001861572265625,
 0.01241302490234375,
 -0.0020046234130859375,
 0.00470733642578125,
 0.0135650634765625,
 0.005397796630859375,
 -0.032318115234375,
 0.00687408447265625,
 0.030609130859375,
 -0.0168609619140625,
 -0.00579833984375,
 -0.026153564453125,
 0.0265655517578125,
 -0.0015916824340820312,
 -0.031646728515625,
 -0.061065673828125,
 -0.02740478515625,
 -0.044769287109375,
 -0.040435791015625,
 0.01300811767578125,
 -0.005138397216796875,
 -0.0271453857421875,
 -0.0092010498046875,
 -0.0201416015625,
 -0.0148468017578125,
 0.03155517578125,
 -0.040618896484375,
 0.000858306884765625,
 0.023406982421875,
 -0.00860595703125,
 -0.00505828857421875,
 -0.0244140625,
 0.01209259033203125,
 0.00914764404296875,
 -0.038543701171875,
 -0.0178070068359375,
 -0.03338623046875,
 0.03564453125,
 -0.0204925537109375,
 -0.026092529296875,
 0.02838134765625,
 -0.0231170654296875,
 -0.00867462158203125,
 0.0262298583984375,
 0.0142974853515625,
 -0.01824951171875,
 -0.01055908203125,
 0.005413055419921875,
 -0.00774383544921875,
 -0.00897216796875,
 -0.045928955078125,
 -0.0116729736328125,
 -0.02288818359375,
 -0.0236663818359375,
 -0.006092071533203125,
 -0.002532958984375,
 -0.006366729736328125,
 0.00995635986328125,
 0.00531768798828125,
 -0.0169677734375,
 -0.0027370452880859375,
 -0.036468505859375,
 0.00724029541015625,
 0.00533294677734375,
 -0.0017681121826171875,
 0.0018453598022460938,
 -0.0201416015625,
 -0.01580810546875,
 0.02093505859375,
 -0.02288818359375,
 0.0029048919677734375,
 0.018310546875,
 0.050018310546875,
 0.00972747802734375,
 0.0185699462890625,
 0.019134521484375,
 0.0207672119140625,
 -0.044189453125,
 0.001239776611328125,
 -0.032623291015625,
 0.0007772445678710938,
 0.051727294921875,
 -0.0041961669921875,
 0.004550933837890625,
 0.00360870361328125,
 -0.00400543212890625,
 0.0231781005859375,
 -0.036712646484375,
 0.0013666152954101562,
 -0.007038116455078125,
 -0.007312774658203125,
 0.053497314453125,
 0.0011968612670898438,
 0.0204315185546875,
 0.04742431640625,
 -0.0164794921875,
 -0.055450439453125,
 0.00403594970703125,
 0.03619384765625,
 0.006435394287109375,
 -0.025787353515625,
 -0.00726318359375,
 -0.05517578125,
 0.00823974609375,
 -0.0181884765625,
 -0.0101776123046875,
 -0.01555633544921875,
 -0.00799560546875,
 -0.032989501953125,
 -0.017822265625,
 0.01111602783203125,
 -0.016326904296875,
 -0.0311279296875,
 -0.031951904296875,
 -0.0224761962890625,
 0.040863037109375,
 -0.004974365234375,
 -0.08160400390625,
 0.01555633544921875,
 -0.023101806640625,
 -0.0298919677734375,
 -0.02545166015625,
 -0.0235748291015625,
 0.004177093505859375,
 0.0390625,
 0.0233612060546875,
 -0.002750396728515625,
 -0.04052734375,
 0.0305633544921875,
 -0.0204315185546875,
 0.0183258056640625,
 0.01250457763671875,
 0.0099029541015625,
 0.00916290283203125,
 0.001934051513671875,
 0.001964569091796875,
 -0.033233642578125,
 0.015655517578125,
 0.0098724365234375,
 0.0150146484375,
 -0.0192718505859375,
 -0.04156494140625,
 0.0291900634765625,
 0.0251922607421875,
 -0.016754150390625,
 -0.00626373291015625,
 0.0211181640625,
 -0.025787353515625,
 0.01013946533203125,
 -0.01197052001953125,
 -0.0030117034912109375,
 -0.00281524658203125,
 -0.013092041015625,
 -0.032135009765625,
 -0.0163421630859375,
 -0.010040283203125,
 0.0186004638671875,
 -0.0017528533935546875,
 -0.0302581787109375,
 -0.038330078125,
 0.0322265625,
 0.002445220947265625,
 0.002086639404296875,
 -0.0360107421875,
 -0.0009465217590332031,
 -0.01439666748046875,
 -0.0014791488647460938,
 0.033538818359375,
 -0.00521087646484375,
 0.00814056396484375,
 -0.0204315185546875,
 -0.007518768310546875,
 -0.006740570068359375,
 0.00286865234375,
 -0.042327880859375,
 0.01422882080078125,
 0.030792236328125,
 0.041015625,
 -0.0168304443359375,
 -0.0086822509765625,
 0.0145721435546875,
 0.004909515380859375,
 0.0296478271484375,
 0.00927734375,
 -0.005764007568359375,
 -0.0113983154296875,
 -0.00029349327087402344,
 0.004108428955078125,
 0.048919677734375,
 0.0195465087890625,
 -0.002300262451171875,
 0.029144287109375,
 0.004230499267578125,
 -0.0019502639770507812,
 0.032867431640625,
 -0.019012451171875,
 0.019683837890625,
 -0.033599853515625,
 0.0184326171875,
 0.02532958984375,
 0.006435394287109375,
 0.004608154296875,
 -0.0051727294921875,
 -0.019012451171875,
 0.035675048828125,
 0.00018095970153808594,
 0.005634307861328125,
 -0.0087432861328125,
 0.0263671875,
 -0.01255035400390625,
 0.00726318359375,
 -0.00682830810546875,
 -0.0261077880859375,
 -0.01245880126953125,
 0.00811767578125,
 -0.036407470703125,
 0.04815673828125,
 -0.015380859375,
 -0.005512237548828125,
 0.026458740234375,
 0.050018310546875,
 0.0242156982421875,
 0.00765228271484375,
 0.01580810546875,
 -0.040435791015625,
 0.0135498046875,
 0.0276947021484375,
 -0.0198211669921875,
 0.0021648406982421875,
 0.0038738250732421875,
 0.0008015632629394531,
 -0.0013837814331054688,
 0.0212554931640625,
 -0.02813720703125,
 -0.0089569091796875,
 0.0253753662109375,
 -0.04400634765625,
 0.041015625,
 0.0008955001831054688,
 0.004734039306640625,
 -0.0025691986083984375,
 -0.00862884521484375,
 0.01236724853515625,
 -0.038909912109375,
 0.0181732177734375,
 0.026611328125,
 -0.0144195556640625,
 0.00514984130859375,
 0.00522613525390625,
 -0.01119232177734375,
 -0.0029544830322265625,
 0.0093841552734375,
 0.004299163818359375,
 -0.025360107421875,
 0.0036029815673828125,
 0.02838134765625,
 -0.015533447265625,
 0.01177215576171875,

In [63]:
import numpy as np
np.array(embeddings[0]).shape

(1536,)

In [62]:
len(embeddings[0])

1536

In [58]:
pointstructs=[]
i=1
for embedding,data in zip(embeddings,data_to_embed):
    if i==1:print(embedding,data)
    pointstructs.append(
        PointStruct(
            id=i,
            vector={
                "text-embedding-model-3-small":embedding,
                "bm25":Document(
                    text=data["description"],
                    model="qdrant/bm25"
                )
            },
            payload=data
        )
    )
    i+=1

[0.01305389404296875, -0.030670166015625, -0.01507568359375, 0.00897216796875, -0.046783447265625, -0.0269775390625, -0.049163818359375, 0.02447509765625, 0.061279296875, -0.033905029296875, -0.0159759521484375, -0.0028553009033203125, -0.06103515625, -0.0266265869140625, 0.03350830078125, 0.0217132568359375, -0.051116943359375, -0.0274810791015625, -0.0243377685546875, 0.0068817138671875, 0.006885528564453125, 0.022674560546875, 0.0208587646484375, 0.0187225341796875, -0.026824951171875, -0.032012939453125, -0.01806640625, 0.029083251953125, -0.0130462646484375, -0.0087127685546875, -0.044342041015625, -0.0226287841796875, 0.003875732421875, -0.0204620361328125, -0.048187255859375, 0.054962158203125, -0.01042938232421875, 0.0060577392578125, 0.038116455078125, -0.0089111328125, 0.0158538818359375, 0.0040740966796875, 0.0494384765625, -0.0297088623046875, 0.01210784912109375, -0.006237030029296875, -0.02423095703125, 0.0308837890625, 0.0144500732421875, 0.0213470458984375, -0.0219573974609375, 0.020599365234375, -0.044708251953125, 0.08349609375, -0.03173828125, 0.0204925537109375, 0.03564453125, 0.02081298828125, 0.01198577880859375, -0.002002716064453125, -0.00792694091796875, -0.0738525390625, 0.0124664306640625, -0.0016536712646484375, -0.0024089813232421875, 0.0030574798583984375, -0.025390625, 0.00713348388671875, -0.02362060546875, 0.0152740478515625, 0.0188446044921875, -0.01355743408203125, 0.040740966796875, -0.00939178466796875, 0.0340576171875, -0.01076507568359375, -0.001262664794921875, 0.01092529296875, 0.0276336669921875, 0.0277862548828125, -3.224611282348633e-05, 0.0013761520385742188, -0.045318603515625, 0.005863189697265625, -0.0020465850830078125, 0.037384033203125, -0.051666259765625, -0.00588226318359375, -0.060211181640625, 0.044830322265625, -0.029449462890625, -0.022064208984375, 0.0150299072265625, -0.0254364013671875, 0.0157623291015625, 0.04693603515625, 0.013671875, -0.01934814453125, 0.0230255126953125, 0.057373046875, 0.0156707763671875, 0.04833984375, 0.012054443359375, -0.0107574462890625, 0.00788116455078125, 0.02337646484375, 0.0164337158203125, -0.046539306640625, -0.0279693603515625, 0.0207366943359375, 0.0213623046875, 0.0296478271484375, -0.0238037109375, -5.805492401123047e-05, 0.003253936767578125, -0.032928466796875, -0.01378631591796875, -0.0013790130615234375, 0.028656005859375, -0.00864410400390625, 0.0026111602783203125, 0.0172882080078125, 0.037017822265625, -0.06793212890625, -0.022918701171875, -0.028411865234375, -0.04327392578125, 0.006481170654296875, -0.00376129150390625, 0.01317596435546875, 0.0106201171875, -0.031341552734375, 0.044342041015625, -0.0228118896484375, -0.0132598876953125, 0.00043654441833496094, -0.051025390625, 0.00994873046875, -0.005130767822265625, 0.04498291015625, 0.0262298583984375, -0.048370361328125, 0.013336181640625, 0.005176544189453125, 0.01114654541015625, -0.0011539459228515625, 0.0245513916015625, -0.004772186279296875, -0.05401611328125, 0.0357666015625, -0.0290985107421875, 0.006626129150390625, 0.0240631103515625, 0.0219573974609375, 0.0780029296875, -0.0269317626953125, 0.0041656494140625, 0.0718994140625, -0.061553955078125, 0.002532958984375, 0.042205810546875, -0.0012464523315429688, -0.045684814453125, -0.00191497802734375, -0.025238037109375, 0.03143310546875, -0.045013427734375, -0.0567626953125, -0.04345703125, -0.006069183349609375, 0.041351318359375, -0.031341552734375, -0.043670654296875, 0.01027679443359375, 0.04949951171875, 0.0029850006103515625, -0.055084228515625, 0.006160736083984375, -0.0008511543273925781, 0.0232086181640625, 0.0290374755859375, 0.002712249755859375, 0.019195556640625, -0.041229248046875, -0.042938232421875, -0.004726409912109375, 0.0118865966796875, 0.035186767578125, -0.036285400390625, 0.0360107421875, -0.01190185546875, -0.0225372314453125, -0.045989990234375, 0.060333251953125, -0.08294677734375, -0.01378631591796875, -0.006866455078125, -0.033843994140625, -0.00830078125, -0.01055145263671875, -0.01043701171875, -0.049652099609375, -0.01690673828125, -0.01259613037109375, 0.018035888671875, -0.022918701171875, -0.04022216796875, -0.01027679443359375, 0.021484375, -0.0660400390625, 0.0261688232421875, -0.00846099853515625, -0.045135498046875, -0.01465606689453125, 0.030792236328125, -0.04571533203125, 0.0006933212280273438, 0.0011835098266601562, 0.0158538818359375, -0.028076171875, -0.0263214111328125, 0.0311279296875, 0.030487060546875, 0.0254974365234375, -0.0034027099609375, 0.01032257080078125, -0.00499725341796875, -0.033966064453125, -0.0257110595703125, -0.0258636474609375, -0.00794219970703125, 0.037078857421875, -0.018280029296875, -0.029083251953125, 0.0230255126953125, 0.0022373199462890625, 0.0211944580078125, -0.041229248046875, -0.0175933837890625, -0.038604736328125, -0.0660400390625, 0.00250244140625, -0.01296234130859375, 0.0389404296875, 0.0308990478515625, -0.017822265625, -0.0001201629638671875, -0.041412353515625, 0.00391387939453125, -0.0125579833984375, 0.03656005859375, 0.01383209228515625, 0.018280029296875, -0.0216522216796875, 0.0157623291015625, -0.01160430908203125, -0.0175018310546875, -0.0230865478515625, 0.0052642822265625, -0.052032470703125, -0.044403076171875, -0.0290374755859375, -0.027587890625, 0.0255584716796875, 0.05670166015625, 0.04632568359375, -0.0175933837890625, 0.0316162109375, -0.017852783203125, -0.0033721923828125, 0.0207061767578125, -0.0033588409423828125, 0.032867431640625, -0.01110076904296875, -0.03350830078125, -0.005535125732421875, -0.002864837646484375, 0.0312042236328125, 0.006580352783203125, -0.04119873046875, 0.01502227783203125, -0.00719451904296875, -0.03265380859375, -0.034759521484375, -0.0144500732421875, 0.01194000244140625, -0.0135955810546875, 0.057830810546875, -0.01529693603515625, -0.0197601318359375, 0.02099609375, -0.051971435546875, -0.01471710205078125, 0.01386260986328125, 0.023162841796875, 0.002719879150390625, 0.00016319751739501953, 0.04742431640625, -0.061187744140625, -0.005603790283203125, 8.505582809448242e-05, 0.046295166015625, 0.033447265625, 0.0207366943359375, -0.018829345703125, -0.00347900390625, -0.038818359375, -0.034027099609375, 0.007526397705078125, 0.035552978515625, -0.0206756591796875, -0.0013418197631835938, -0.0162506103515625, -0.033843994140625, -0.0251922607421875, -0.031341552734375, -0.0009813308715820312, -0.06939697265625, -0.019378662109375, -0.03582763671875, 0.03338623046875, 0.0004143714904785156, -0.0115509033203125, 0.001987457275390625, 0.033477783203125, -0.033935546875, 0.0049896240234375, -0.006744384765625, -0.030548095703125, -0.0046234130859375, -0.01543426513671875, 0.0150909423828125, 0.046173095703125, -0.048431396484375, -0.02349853515625, 0.0279083251953125, -0.0110015869140625, -0.036865234375, -0.020751953125, -0.0090484619140625, 0.0101318359375, -0.0007462501525878906, -0.017822265625, -0.0193634033203125, -0.0036792755126953125, 0.027191162109375, 0.063720703125, 0.03326416015625, 0.02520751953125, 0.038665771484375, -0.0145263671875, 0.035797119140625, 0.0408935546875, -0.00904083251953125, 0.0210723876953125, 0.041046142578125, -0.003253936767578125, -0.07379150390625, -0.019561767578125, -0.004734039306640625, 0.0606689453125, 0.053863525390625, -0.0144805908203125, -0.0264892578125, 0.006061553955078125, 0.04534912109375, -0.05615234375, 0.021697998046875, -0.0181884765625, -0.0313720703125, 0.0171966552734375, 0.048492431640625, 0.02447509765625, 0.05615234375, -0.018035888671875, 0.013641357421875, -0.0007796287536621094, 0.041900634765625, 0.01007843017578125, -0.023101806640625, 0.0198974609375, 0.01166534423828125, 0.0194854736328125, 0.00794219970703125, 0.046173095703125, -0.00537872314453125, -0.040924072265625, -0.00848388671875, 0.041046142578125, -0.0142974853515625, 0.03497314453125, 0.0151824951171875, 0.028289794921875, -0.04583740234375, 0.0416259765625, 0.05194091796875, 0.046905517578125, -0.0075225830078125, 0.0174407958984375, -0.01241302490234375, 0.00136566162109375, -0.0657958984375, 0.01251220703125, 0.027099609375, -0.019500732421875, -0.01300811767578125, -0.021728515625, -0.00313568115234375, 0.04168701171875, 0.01526641845703125, 0.031585693359375, -0.007404327392578125, 0.01885986328125, 0.0171356201171875, 0.0256805419921875, 0.038299560546875, -0.03369140625, 0.0242919921875, 0.0246734619140625, -0.00958251953125, 0.0360107421875, -0.0246429443359375, -0.0228424072265625, 0.05157470703125, -0.028076171875, 0.0203399658203125, 0.034088134765625, 0.023040771484375, 0.007312774658203125, -0.046539306640625, -0.01291656494140625, -0.00592803955078125, 0.01303863525390625, -0.00983428955078125, -0.0291290283203125, -0.0112762451171875, -0.02459716796875, 0.033111572265625, -0.0169525146484375, -0.002437591552734375, -0.04046630859375, 0.0159149169921875, -0.0213470458984375, -0.0038909912109375, 0.028564453125, 0.035125732421875, -0.044769287109375, 0.0859375, -0.0050048828125, 0.01177978515625, -0.048553466796875, 0.0498046875, -0.0360107421875, 0.01666259765625, -0.06353759765625, 0.0247039794921875, 0.002040863037109375, -0.0104217529296875, -0.036163330078125, 0.0026149749755859375, 0.0050201416015625, -0.0004508495330810547, 0.01541900634765625, -0.0418701171875, -0.0010862350463867188, -0.037933349609375, -0.0066986083984375, 0.0278167724609375, 0.05902099609375, -0.00818634033203125, 0.0175933837890625, 0.004833221435546875, 0.0011720657348632812, 0.048614501953125, 0.01302337646484375, -0.00870513916015625, 0.0275115966796875, 0.032867431640625, -0.033172607421875, -0.0260772705078125, -0.052093505859375, -0.016143798828125, -0.042388916015625, 0.00746917724609375, 0.0294952392578125, 0.0223541259765625, 0.0648193359375, -0.0258026123046875, -0.034149169921875, -0.0006799697875976562, -0.04949951171875, -0.016998291015625, 0.0322265625, -0.0052490234375, -0.01480865478515625, 0.0134429931640625, -0.06744384765625, -0.0011386871337890625, -0.01520538330078125, -0.003971099853515625, 0.04034423828125, -0.006031036376953125, 0.07598876953125, -0.036895751953125, 0.0171051025390625, 0.001678466796875, 0.027252197265625, 0.0133819580078125, -0.00881195068359375, 0.03228759765625, -0.0187530517578125, -0.0160064697265625, 0.006793975830078125, 0.008758544921875, -0.0293731689453125, -0.0177459716796875, 0.03167724609375, 0.034820556640625, -0.0189361572265625, -0.00450897216796875, -0.01532745361328125, -0.0197906494140625, 0.068115234375, -0.03173828125, -0.0224761962890625, -0.004856109619140625, -0.00262451171875, -0.06353759765625, -0.04547119140625, -0.0221405029296875, 0.0146331787109375, -0.026947021484375, -0.0419921875, -0.0225982666015625, -0.0007033348083496094, -0.0030155181884765625, 0.0018520355224609375, -0.0147857666015625, 0.0017061233520507812, 0.0117340087890625, 0.00921630859375, -0.035400390625, -0.002239227294921875, -0.016510009765625, 0.0019931793212890625, -0.0162811279296875, 0.0082550048828125, 0.0032939910888671875, 0.01548004150390625, 0.007312774658203125, 0.036468505859375, -0.005992889404296875, 0.0416259765625, -0.0037212371826171875, 0.0172271728515625, 0.0172882080078125, 0.0169830322265625, 0.02008056640625, 0.0101165771484375, -0.0076446533203125, 0.0250244140625, -0.002773284912109375, 0.0226898193359375, 0.0080718994140625, 0.0224456787109375, 0.041656494140625, -0.0040283203125, -0.0438232421875, -0.0189361572265625, 0.0226593017578125, 0.0278778076171875, 0.0024566650390625, 0.005550384521484375, 0.0006709098815917969, 0.031463623046875, 0.0177154541015625, -0.0296173095703125, -0.001811981201171875, -0.044586181640625, -0.017120361328125, -0.045501708984375, 0.007404327392578125, -0.01235198974609375, 0.0640869140625, -0.04486083984375, -0.01080322265625, 0.038055419921875, -0.0195159912109375, -0.01059722900390625, 0.04296875, -0.0075836181640625, -0.001312255859375, -0.0248260498046875, -0.008514404296875, 0.01462554931640625, 0.01409912109375, -0.044647216796875, -0.007076263427734375, 0.0228424072265625, 0.0176239013671875, 0.0132904052734375, -0.0013608932495117188, -0.0251922607421875, 0.00493621826171875, -0.041595458984375, -0.0198974609375, -0.0032749176025390625, -0.0169830322265625, 0.02166748046875, 0.02325439453125, 0.0210723876953125, 0.0009222030639648438, -0.00719451904296875, -0.012603759765625, 0.0301055908203125, 0.034210205078125, -0.0100250244140625, 0.0290985107421875, 0.0227203369140625, 0.0025691986083984375, 0.01184844970703125, -0.01485443115234375, 0.034210205078125, 0.031585693359375, 0.021728515625, 0.036224365234375, -0.0291595458984375, -0.00428009033203125, -0.00044989585876464844, -0.03155517578125, -0.0017461776733398438, -0.00847625732421875, 0.000995635986328125, -0.03399658203125, -0.0135498046875, 0.029571533203125, -0.0163726806640625, 0.006145477294921875, -0.0193634033203125, -0.005832672119140625, -0.0050201416015625, 0.026641845703125, 0.010009765625, -0.01381683349609375, 0.01042938232421875, 0.0224151611328125, -0.00304412841796875, -0.012451171875, 0.01058197021484375, 0.0244293212890625, 0.0133819580078125, -0.0080718994140625, 0.034149169921875, 0.0120849609375, 0.01035308837890625, 0.00740814208984375, -0.01535797119140625, -0.0192108154296875, -0.01169586181640625, 0.028778076171875, -0.0006265640258789062, -0.01971435546875, -0.01036834716796875, 0.0209808349609375, -0.035125732421875, -0.010284423828125, 0.051666259765625, 0.04644775390625, -0.0318603515625, -0.0186767578125, 0.0178070068359375, 0.05084228515625, 0.00384521484375, 0.006443023681640625, -0.0009365081787109375, -0.038787841796875, 0.01629638671875, 0.0020542144775390625, 0.0260772705078125, -0.027069091796875, -0.0148468017578125, -0.00911712646484375, -0.056304931640625, 0.013946533203125, 0.05462646484375, 0.016632080078125, 0.0032558441162109375, -0.0089111328125, 0.00296783447265625, 0.0260162353515625, 0.00936126708984375, -0.0256195068359375, 0.007404327392578125, 0.0058135986328125, 0.0025730133056640625, -0.03167724609375, -0.0036373138427734375, 0.01263427734375, -0.0017614364624023438, 0.01544952392578125, -0.0146942138671875, -0.031890869140625, -0.01142120361328125, 0.002353668212890625, -0.07757568359375, -0.0166168212890625, -0.045867919921875, -0.022003173828125, -0.001918792724609375, -0.027069091796875, -0.006954193115234375, 0.01389312744140625, -0.053131103515625, -0.0035552978515625, 0.01056671142578125, -0.040863037109375, -0.00922393798828125, 0.035186767578125, -0.007366180419921875, -0.023223876953125, -0.01222991943359375, -0.008697509765625, 0.00389862060546875, 0.007511138916015625, -0.02716064453125, -0.042022705078125, 0.0207977294921875, -0.003986358642578125, -0.045562744140625, 0.01399993896484375, -0.0001341104507446289, 0.006130218505859375, -0.0025653839111328125, 0.00800323486328125, -0.00865936279296875, 0.03521728515625, -0.0280303955078125, 0.0257110595703125, -0.04376220703125, -0.0184478759765625, 0.0014123916625976562, -0.0023708343505859375, -0.046142578125, 0.01442718505859375, 0.018035888671875, 0.0147857666015625, -0.00936126708984375, -0.0037288665771484375, 0.006511688232421875, -0.00894927978515625, 0.004833221435546875, 0.003803253173828125, 0.0017118453979492188, -0.0007624626159667969, -0.039398193359375, -0.047760009765625, 0.031951904296875, 0.024810791015625, 0.0104522705078125, -0.0006494522094726562, -1.1563301086425781e-05, 0.03472900390625, 0.0170135498046875, 0.055511474609375, 0.0247039794921875, 0.005130767822265625, -0.026580810546875, 0.00450897216796875, 0.0050506591796875, 0.033294677734375, -0.004840850830078125, 0.0092010498046875, -0.01456451416015625, 0.02435302734375, -0.0109100341796875, 0.0019006729125976562, -0.0246734619140625, -0.019439697265625, 0.041961669921875, -0.000835418701171875, 0.016387939453125, -0.002593994140625, 0.00830841064453125, 0.01678466796875, -0.0152130126953125, -0.0293121337890625, -0.0179901123046875, 0.00565338134765625, -0.00817108154296875, 0.0194549560546875, 0.00954437255859375, -0.024658203125, 0.0235137939453125, 0.0292816162109375, -0.003292083740234375, -0.00452423095703125, -0.0126953125, -0.023681640625, 0.0013227462768554688, -0.007080078125, 0.028076171875, -0.040252685546875, -0.042510986328125, -0.0311279296875, 0.0142669677734375, 0.033538818359375, -0.0170135498046875, 0.080810546875, 0.0066375732421875, -0.0216522216796875, 0.00676727294921875, 0.0224151611328125, 0.01134490966796875, 0.024871826171875, 0.004253387451171875, 0.0182952880859375, -0.005367279052734375, 0.029754638671875, -0.0281829833984375, 0.016693115234375, -0.01477813720703125, 0.03826904296875, 0.0030155181884765625, -0.0021114349365234375, -0.01274871826171875, -0.0240478515625, 0.01995849609375, 0.00334930419921875, -0.01702880859375, 0.0262908935546875, 0.0215301513671875, 0.01160430908203125, -0.00794219970703125, -0.018951416015625, 0.013427734375, 0.03729248046875, -0.040924072265625, -0.0258941650390625, 0.0012187957763671875, -0.009796142578125, 0.0257415771484375, -0.048492431640625, 0.0026531219482421875, -0.0127410888671875, -0.0367431640625, -0.0153961181640625, -0.0236968994140625, 0.005977630615234375, 0.02386474609375, 0.00386810302734375, -0.01019287109375, 0.0164031982421875, -0.01129913330078125, 0.0076904296875, -0.0016679763793945312, -0.0006809234619140625, -0.01507568359375, -0.005832672119140625, 0.0100250244140625, -0.0195770263671875, 0.007724761962890625, 0.04302978515625, -0.0143890380859375, -0.05303955078125, -0.006702423095703125, 0.030181884765625, -0.037933349609375, 0.00041961669921875, 0.018463134765625, -0.0008134841918945312, 0.0206451416015625, -0.013427734375, -0.0023288726806640625, 0.0148162841796875, -0.0035858154296875, 0.01049041748046875, -0.02392578125, 0.049652099609375, 0.00982666015625, 0.032012939453125, -0.00018978118896484375, 0.004047393798828125, -0.00537109375, 0.010986328125, 0.002292633056640625, 0.0241851806640625, 0.0196533203125, -0.015625, 0.0333251953125, -0.00308990478515625, 0.005199432373046875, 0.03961181640625, -0.04302978515625, -0.0006222724914550781, -0.026092529296875, -0.0245361328125, -0.0054168701171875, 0.01415252685546875, -0.0307769775390625, 0.0369873046875, -0.01551055908203125, -0.056732177734375, -0.0338134765625, 0.004695892333984375, -0.0487060546875, 0.007724761962890625, -0.00666046142578125, 0.0050201416015625, 0.002841949462890625, 0.034423828125, 0.055389404296875, 0.018585205078125, 0.0258636474609375, -0.02764892578125, -0.02496337890625, 0.028533935546875, -0.0020599365234375, -0.002780914306640625, 0.00746917724609375, -0.0307769775390625, 0.0048675537109375, -0.0164337158203125, -0.0167236328125, 0.0195159912109375, -0.0194244384765625, -0.039306640625, 0.0274810791015625, 0.006298065185546875, 0.00311279296875, 0.01291656494140625, -0.002735137939453125, 0.01120758056640625, -0.0166015625, 0.0191802978515625, 0.002655029296875, 0.0192108154296875, 0.0262908935546875, -0.02001953125, -0.00870513916015625, 0.0023822784423828125, -0.0187835693359375, 0.04986572265625, 0.022613525390625, -0.025848388671875, 0.0247802734375, 0.01470184326171875, -0.01052093505859375, 0.00667572021484375, 0.0099029541015625, -0.01486968994140625, -0.02349853515625, -0.0089263916015625, -0.0289764404296875, -0.034759521484375, 0.0195159912109375, -0.0224761962890625, -0.017608642578125, 0.022796630859375, 0.0015411376953125, 0.0391845703125, 0.0333251953125, 0.01137542724609375, 0.006191253662109375, 0.01001739501953125, 0.00855255126953125, 0.0277099609375, 0.0008754730224609375, 0.00682830810546875, 0.0753173828125, -0.00421905517578125, -0.0109710693359375, -0.007598876953125, -0.00449371337890625, -0.0176544189453125, -0.0186767578125, -0.01216888427734375, 0.0294647216796875, -0.00841522216796875, 0.0018453598022460938, 0.04962158203125, 0.01385498046875, 0.01418304443359375, 0.0225677490234375, -0.00858306884765625, -0.042816162109375, -0.0006275177001953125, -0.044403076171875, -0.018463134765625, 0.047027587890625, 0.00458526611328125, 0.00616455078125, 0.0439453125, 0.0145416259765625, 0.00947570800781

In [ ]:
pointstructs

In [10]:
quadrant_client.upsert(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    points=pointstructs[0:500],
    wait=True
)

NameError: name 'quadrant_client' is not defined

In [24]:
quadrant_client.upsert(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    points=pointstructs[500:1000],
    wait=True
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

In [25]:
quadrant_client.upsert(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    points=pointstructs[1000:1500],
    wait=True
)

UpdateResult(operation_id=3, status=<UpdateStatus.COMPLETED: 'completed'>)

In [34]:
quadrant_client.upsert(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    points=pointstructs[1500:2000],
    wait=True
)

UpdateResult(operation_id=5, status=<UpdateStatus.COMPLETED: 'completed'>)

### Hybrid Retrival

In [11]:
def get_embedding(text,model="text-embedding-3-small"):
    response=client.embeddings.create(
        model=model,
        input=text
    )
    return response.data[0].embedding

In [14]:
qdrant_client=QdrantClient(url="http://localhost:6333/")
def get_only_dense(query):
    query_embedding = get_embedding(query)

    dense_result = quadrant_client.query_points(
        collection_name="Amazon-items-collection-02-hybrid-serach",
        query=query_embedding,
        using="text-embedding-model-3-small",
        limit=10
    )

    for point in dense_result.points:
        print(point.score, point.payload["description"])

In [84]:
get_only_dense("can i get some tablet")

0.425358 ALZHIJ Portable Tablet Holder Stand - Aluminum Alloy Desktop Stand Adjustable Angle&Height Tablet Stand Holder Creative Tablet Stand Compatible with Various Tablet UP to 12IN Wide (Grey)😃MADE OF HIGH-QUALITY MATERIALS:The high-quality aluminum alloy material achieves the perfect performance of the tablet holder for bed, making the tablet wear-resistant and scratch-resistant, and has excellent corrosion resistance. The superb anodizing process increases the color and luster of the table stand and makes it richer in texture.😃EXQUISITE APPEARANCE DESIGN:The personalized smiley face design can not only be a better decoration for this tablet stand for desk, but also provide a long-lasting heat dissipation effect for the tablet during use, making your tablet run more efficiently. The tablet stand for bed is designed with multiple non-slip silicone pads to protect the tablet from damage at all times.😃180°FREELY ADJUSTABLE ANGLE:The tablet floor stand adopts a stable dual-axis mechanism design, which is firm and not easy to shake. The angle and height can be adjusted arbitrarily, giving you a perfect experience. Lightweight and portable adjustable stand, completely bid farewell to the troubles of traditional stand that are too heavy and make your life more convenient.😃A WIDE RANGE OF APPLICATIONS:A tablet stand that integrates practical, beautiful, portable and other elements into one. It has a wide range of applications and can be compatible with various tablet up to 15.6 inches wide. The adjustable tablet stand can be used for work, travel, watching drama, and study, giving you a perfect experience.😃OUR GURANTEE FOR YOU:Everything I do is based on customer satisfaction. If you are not completely satisfied with the purchased product or the product is damaged or broken in transit, please contact us in time. We will solve your problem as quickly as possible!
0.41469824 CUPEISI 10 inch Tablet, Android 11 Tablets, 64GB ROM+2GB RAM, Quad-Core Processor Tablet PC, 1280 * 800 IPS HD Display, 2MP+8MP Dual Camera, 6000mAh Tableta.[HIGH PERFORMANCE ANDROID TABLET ] - CUPEISI YQ10S tablets comes with Android 11 OS, 2GB RAM, 64 GB ROM, the powerful and energy-saving Quad-core Processor enables quicker app launch, smoother videos, you can enjoy better overall performance experience. In addition, it includes a Micro SD card slot (can be added a expanded 256 GB TF Card Max, NOT included), making it easy to store Pictures videos, files etc. There is NO extra bloatware installed. Note: This tablet can't add a SIM Card.[LONG-LASTING ENTERTAINMENT] - CUPEISI 10 inch tablet features android 11, GMS Certified, you can download thousands of apps, such as, Netflix, YouTube, Skype, and more popular apps. The large battery and low-power CPU enhance your experience and allow you to enjoy up to 8 hours of mixed reading, watching TV shows, surfing the web, playing light games and more. It is a really good companion for your leisure and entertainment. Large IPS Touchscreen will be a plus.[LOW BLOATWARE & DUAL CAMERA] - With Front 2.0 MP & Rear 8.0 MP camera, which would bring your photos and videos to life. CUPEISI YQ10S 10'' tablet rivals most of the 10 inch tablet and it is convenient for taking photos, capturing and sharing those special moments with your friends and family. CUPEISI tablet meets your basic daily needs, such as watching videos, Live and reading. A good tablet for your choise, very Low bloatware, No ads![BRILLIANT IPS DISPLAY ] - CUPEISI 10 inch tablet PC adopts a 1280 x 800 brilliant HD IPS display. This android tablet has a sharper hierarchy of images and richer colors, and provides shocking performance of visual experience. With the Eye Health mode, an extra feature filters out blue light to relieve visual fatigue, and optimizes the backlight for a more comfortable reading experience.[WARRANTY & SUPPORT] - CUPEISI Tablet PC comes with 1-year worry-free guarantee - If it is the tablet quality issue, return it and we’ll replace it for free. CUPEISI team focuses on the customer's pleasant shopping experience and provides reliable customer service. Please do not hesitate to contact us if you have any problem, we will give you on-time TECH SUPPORT and the better customer service. Looking foward to hearing from you(CS email).
0.39687455 ATOZEE Tablet 10 Inch Tablet, Android 11 Tablets, 64GB and 512GB Expand Tableta, Quad-Core Processor 2GB RAM 8MP Camera WiFi GPS FM Tablet Computer, 10.1 in HD Display Long Battery Life Tabletas【64GB Tablet】 The tablet comes with 64GB of built-in storage and up to 512GB of expandable microSD card storage for more space, you can download various ebooks, songs, photos or movies.【Excellent Performance】 This Google tablet AT10 featuring with powerful Quad-core 1.5GHz CPU, 2GB RAM and newest Android 11.0 operating system, with 10.0" capacitive touch, five point cap-touch G+G, ensure a more fluently action for movie and game.【Enjoy Video and Music】 ATOZEE tablet benefit from 1280*800 IPS high-definition touch screen and 178-degree wide viewing angle, the 10.1-inch tablet gives a more vivid display and excellent picture quality. Capture photos and videos with the front 2MP and rear 8MP cameras to share moments with friends and family. Dual-box speakers provide you with an excellent audio-visual experience.【Smooth Operation】 The high-performance tablet ensures smooth web browsing and video playback. The new GMS certified Android 11.0 operating system eliminates unwanted ads. Enjoy full access to Google services and applications such as Gmail, Youtube, Google Drive, Play Store and more.【Long Battery Life】 The 6000mAh rechargeable battery and low-power CPU enable up to 8 hours of mixed use on the go, perfect for long commutes and travel. Equipped with 5V2A charging brick and type C cable.
0.39450377 Universal 7 8 Inch Android Tablet Case, Universal Tablet Case Cover for 7 8 Inch Tablet, Nannxiebky Multi-Angle Viewing Stand Case for 7.0-8.5 Inch Tablet, Bird FlowerNannxiebky 8 inch tablet case, Such as compatible with Samsung Galaxy Tab A/S2/E 8.0 inch tablet case, Galaxy Tab A 8.4 inch tablet case, also compatible with LECTRUS AEEZO AOYODKG CWOWDEFU Pritom 8 inch Android tablet case(No back camera opening, not support auto sleep/wake Function).Tablet case for 8 inch tablet, compatible with Drangon Touch Y80 tablet case / MatrixPad S8 tablet case / Winnovo T8 tablet case / TECLAST P80 P80H P80X MIX 8 tablet case / Onn 8 inch tablet case.(No back camera opening, not support auto sleep/wake Function).Nannxiebky 7 inch tablet case, Such as samsung galaxy Tab 7.0 inch tablet case, walmart Onn 7 inch tablet case, also compatible with MatrixPad Dragon Touch Contixo Pritom qunyiCO AEEZO TOPELOTEK Haehne HAOQIN Winnovo ZONKO 7 inch tablet case. (No back camera opening, not support auto sleep/wake Function)Interior card slots and document pocket are designed for carrying your credit card / business cards/ some notes or bills while on the go.Multi-Angle viewing stand function for watching, you could attach the magnet closure to the back and make it keep away from screen.
0.38994595 G-TiDE Kids Tablet, 7 inch Tablet for Kids, 32GB+2GB Kids Learning Tablet, 5MP Dual Camera HD, Parental Control App- KLAP, Toddler Tablet Case, WiFi Tablets Shoulder Straps, Pink🤗【Explore More Fun on Klap】G-TiDE Klap kids tablet is designed for learning and playing. This tablet for kids offers various creative contents such as brain training, painting, gaming, kids TV, etc. Learning while playing is better for kids to know the world. With a 32GB bigger storage, which can be extended to 128GB (micro SD card not included), this kids tablet is perfect for children aged 3-7 years old. You could get more educational apps from Google Play Store (GMS).🤗【Kids-proof Case & Eye-protection Screen】G-TiDE's exclusive kids tablet case is made of impact-resistant EVA material. When your kid is playing outdoors with the tablet or accidentally dropping the tablet on the ground at home, it protects the kids tablet from bumps and minor drops. This kids tablet comes with an adjustable shoulder strap, so your little one can take their tablet wherever they go. With a 270° adjustable stand, you can place it at the distance that suits your kids best.🤗【Amazing Experience on Klap Kids Tablet】G-TiDE Klap kids tablet offers an amazing experience with its learning & playing App - Klap. This app offers various creative content such as brain training, painting, gaming, kids TV etc. Learning while playing is better for kids to gain more knowledge. When there are more children, they can also watch kid's TV and play two-player games, they can also learn from each other. This kids tablet is perfect for children aged 3-7 years old and has a storage capacity of 32GB, which can be expanded up to 128GB(micro SD card not included). You can download more apps from Google Play Store, like YouTube Kids, Netflix, and other popular apps for kids tablets.🤗【Easy Parental Controls】KLAP has parental controls that allow you to create over 20 different children's accounts and customize learning content and time limits according to their individual needs. It also includes features such as a child lock, remote video control, content filtering, a one-button lock screen, and alarm setting to ensure your children can safely browse websites. When you're busy working and don't have time to supervise your children, you can set content and time limits for them to play.🎁【Perfect Gift For Kids】G-TiDE S1 provides endless online age-appropriate content, ensuring safe browsing for kids aged 3-7 years old. It offers an easy and fun way for kids to learn and play. This makes it the perfect gift for your child for Christmas and birthdays. We offer a 12-month worry-free guarantee, and you can find our official mailbox on the package's back for any service-related inquiries. Please don't hesitate to contact us if you have any questions about our tablets. G-TiDE is always by your side.
0.38850462 Tablet 10 inch Latest 128 GB ROM Android 11 Q10PRO Tablets:4GB RAM|5G/4G Wi-Fi|Octa-Core|8000mAh|Bluetooth|Google Certified Tablet with Keyboard, Mouse, Earphones etc./Support Split Screen-Green【High Performance & storage】 Facetel Q10 Tablet has a built-in 4GB running memory，enjoy smooth multitasking and switching. between applications. 128GB storage capacity, includes a micro SD card slot, (MicroSD can be expanded to 128GB), allows you to store all your files,meet your daily entertainment and work needs.【Split Screen & Fast Runnung】The Q10PRO with the latest Android 11 and is Google certified, so there's no need to worry about app compatibility. Pre-installed with Google Play, you can freely download any app from the store, games, music, beauty, email, weather, social apps and more.It also supports 2.4G & 5G WiFi and application split screen, giving you a high-speed internet connection, Two Apps for use on the same screen and video playback experience.【Powerful battery life】8000mAh battery combined with SC610 1.6 GHz Octa-Core processor, lower power consumption, audio and video entertainment, games and learning, office meetings, fearless use of any scene, can be continuous 720 hours of standby, 20 hours of calls, 24 hours of MP3 music, 6-8 hours of online video, and with Type-c charging cable, so you can use the tablet with confidence.【Crisp G+G Ips Display & Dual Speakers】 Featuring 1280 x 800 HD IPS display with dual speakers, 5MP front and 8MP rear, the display presents a bright display that will give you the HD experience whether you are watching videos, reading e-books, or playing games, a very pleasant visual and auditory experience for the user.while the G+G glass screen is highly transparent and scratch resistant, making your tablet more durable.(There is a new protective film placed in the Tablet pack)【Lightweight, portable & colorful design】The 10.1-inch tablet has a thin and light design with a more sturdy and beautiful metal frame, which is suitable for carrying around and can give a quality experience whether you are working or traveling.Currently there are two tablet colors for you to choose from: elegant green and temperamental black. We have a professional service team with a 24-month worry-free warranty and friendly customer service, if you have any questions, please contact us through Amazon, we will help you solve the problem and give you a satisfactory solution.
0.38701707 Blackview Tab 5 Tablets, 2023 Latest Tablet Android 12, Quad-Core 5GB(3+2) RAM 64GB ROM up to 1TB TF, 8 inch Tablet HD+ IPS 1280*800, Android Tablet 5580mAh Big Battery, Dual BOX Speakers WiFi, Blue【1280*800 IPS 8 Inch Tablet】The Blackview Tab 5 uses an HD+ screen, which is better and more eye friendly than other tablets that use 1024 x 600 resolution display. Enjoy your favorite apps like Netflix, Facebook, Hulu, Instagram, TikTok, and more through Google Play. It can gives you an ideal vision for productivity tasks, reading and entertainment.【Enhanced Performance Tablet】📢📢📢Blackview has exclusive technology that can 🔸expand 3GB RAM to 5GB (2GB virtual memory)🔸on this android tablet, greatly improving the performance and speed, and no longer stuttering when running several apps at once. It also has an TF card slot that can be plugged into 1TB of expanded memory, with the 64GB ROM, this tablet can store lots of music, pictures, videos.【Latest Android 12 tablet+DOKE O_P 3.0 GO】Android 12 has enhanced security and privacy features, as well as optimized the notification bar settings and Hotkeys for greater security and convenience. DOKE OS_P 3.0 GO is designed for blackview tablets. It makes the interface more beautiful based on Android 12, adding split screen, screen shot, screen recoard,dark theme, etc.【5580mAh All day Battery Life Google Tablet】Extend your joy with extended battery life. Blackview Tab 5 never runs out of battery to enjoy reading, browsing the web, watching videos, and listening to music at home and on-the-go. We also added a power-saving mode, so it can lasts longer than other tablets which have 3500-5000mah batteries.【Great fit for Family】Blackview Tab 5 tablet has parental controls mode, parents can create child profiles to limit screen time, set educational goals, and manage content with easy-to-use parental controls. It's Google GMS Certified, so it's also a great gift for your parents, Keep in touch with them through this android tablet. Father‘s day gift【2 years Warranty】This android 8 inch tablet have 2 years guarantee policy and 30 days free return. In the unlikely event that the product is defective, please contact us through your Amazon purchase history. We will do our best to satisfy our customers.
0.38662246 TCL Android 11 Tablet TAB 8V, Up to 512GB, Portable 8 Inch Tablets, HD Display Touch Screen, 4080mAh Battery, 5G Wi-Fi Gaming Tablet with 5MP Camera Small Cheap Tableta for Kids, Adults👍【Just Right for Holding &Pockets Tablet】—Weighing just 310g, Lighter than the weight of an apple, Suitable as Pockets Tablet. TCL TAB 8V tablet is an idea for people on the go so you can easily hold it with one hand and keep hands from getting tired, even playing for hours.⚙【Android 11 Operating System】—Android 11 tablets has enhanced security and privacy features, as well as optimized the notification bar settings and Hotkeys for greater security and convenience.💾【512GB for Record Your Fun】—Tableta with 64 GB of internal storage (up to 512 GB of expandable storage with microSD, sold separately). Enjoy your favorite apps through the Google Play Store.⚡【4080mAh Long-lasting Tablet】—Long-lasting Battery Tab supports 10 hours of online video streaming or 6 hours of online game play. Power for All Day Fun🖥【See Brighter Colors】—See 16 million colors on a compact 8" HD 800x1280 Pixels screen with thin 9.8mm bezels. 3 types of eye protection modes (dedicated modes and features optimize brightness and E-book reading modes) allow you to switch freely according to your needs.
0.3850177 Tablet 64GB 10 Inch Tablet, Android 11 Tablets, 6000mAh Battery Quad Core HD Touch Screen Tableta Computer, with WiFi BT Google Play Android Tabletas. Black.Tablet Parameter - 64GB Storage, 2GB RAM Quad Core1.5GHZ, 10.1 IN HD Display, Dual Cameras，6000mAh Battery, Android 11.0, Wifi BT.64GB Large storage - Our 10.1 inch android tablet comes with 2GB RAM and 64GB ROM which is expandable up to 512GB using the microSD slot. You can download your favorite ebooks, games, shows and blockbuster movies. It has plenty of space and works great for the office or as a gift.Long battery life - 10.1 Inch Tablet With a 6000mAh Ultra-large battery, up to 8 hours of reading, browsing the web, watching the video, and listening to music. It's ready for daily life as well as travel.Android 11 & High-performance CPU - The tablet is equipped with a high-performance quad-core CPU and adopts the Android 11 artificial intelligence system, all functions have been enhanced, and the operation is faster. You can feel the smooth operation, and the 10-inch high-definition screen is perfect for watching videos, learning tools and reading e-books.PERFECT GIFT AND AFTER SERVICE - This is a perfect gift, this tablet is suitable for all age groups, seniors can use it to watch TV, children can use it to play games and study, office workers can use it to participate in video conferences middle. We offer 1 year of ultimate after-sales service, you can contact the seller on Amazon with any questions you have, and we promise a response within 24 hours.
0.38353503 ROWT Tablet for Kids 10 inch Kids Tablet 2GB RAM 32GB ROM Android 11 6000mAh Wi-Fi, Bluetooth, Kid-Proof Case(Blue)【Kids' Safety & Parental Controls】Looking for a safe tablet that's easy for your kids to use? This 10-inch tablet for kids is GMS-certified, has password protection, a content filter, and a one-button lock screen, making it easier for parents to keep an eye on their kids activities and learning.【Creative Educational Content】Our kids tablet provides access to a range of age-appropriate creative kids content such as drawing, educational games, eBooks, learning videos, math tools, and much more! Learning through play is best for kids to understand the world.【Powerful Configuration & Full Access to Google】This Android 11 kids tablet has an HD 1280x800 IPS touchscreen, 1.6 GHz Quad-Core processor, 2GB RAM & 32GB ROM storage, dual cameras, and a large battery with 6000mAh capacity. You have full access to Google Play to download the latest apps such as Gmail, Disney+, Youtube, and many more.【10.1" Large Screen + Eye Protection】This kids tablet is designed with a 10.1-inch large HD screen. The screen is designed to produce less glare and provide more clarity and brightness. It helps protect your eyes by reducing damage from blue light, letting your child be safer and more comfortable while using the tablet.【Durable Kid-proof Case】Designed to be easy to use, this 10-inch large yet portable kids tablet includes a protective case with a built-in stand to protect the kids tablet from scratches and bumps. This kids tablet is a great gift for birthdays, Christmas, holidays, and more.

In [85]:
def get_only_Bm25(query):
    query_embedding = get_embedding(query)
    
    bm25_result = qdrant_client.query_points(
    collection_name="Amazon-items-collection-02-hybrid-serach",
    query=Document(
        text="can i get some tablet",
        model="qdrant/bm25"
    ),
    using="bm25",
    limit=10
   )
    for point in bm25_result.points:
      print(point.score, point.payload["description"])

In [86]:
get_only_Bm25("can i get some tablet")

5.8474283 Android Tablet 10.1 Inch, Tablet with Keyboard, 2 in 1 Tablets 64GB Memory 4G RAM 128GB Expandable, 5G WiFi Tablet, Android 11, 13MP Camera, Large Battery, Tablet with Case, Keyboard, Mouse, StylusAndroid 11.0 Standard OS Google Tablet: 2022 Newest android tablet runs the latest android 11.0 OS, which is easier when set up and operate. Google base can better protect your privacy and compatible with more apps in pre-installed google play store. Get yourself a wonderful tablet and all your favourite apps on it.WiFi tablet Support Dual band 2.4+5Ghz: 5G WiFi tablet support not only 5Ghz Wifi but also 2.4Ghz wifi meet anyone needs. No restrictions on any usage environment, whether you live in a hotel/apartment with only 5Ghz WiFi, or in your home with 2.4Ghz wifi, it can be easily connected, provides the best speed when using this tablet.Tablet 64GB Storage 128GB Micro SD Expandable: 2 in 1 android 11 tablet has a 1.6 GHz high-efficiency Quad-core processor, 4GB RAM+64GB ROM, fast and responsive. 128GB expandable by Micro SD Card. 6000mAh battery provide a long using time and standby time. 5V 2A charger with USB-C cable can charge faster.Tablet with all the accessories you need: Tablet with Keyboard, Mouse, Tablet Case and Stylus, OTG. Wireless Keyboard and Mouse connect with Bluetooth, get rid of the shackles of wire, you can use it in anywhere. The custom case can all around protect your tablet and provide a sturdy stand.ZONKO Lifetime Tech-support: Tablets with a exact touch-screen, the screen clarity is super crisp. It is suitable big tablet for children or your parents and your friends as a ideal Christmas gift to surf the internet, browse emails, read e-books and watch videos. We offer lifetime technical support and 365-days warranty. Feel free to contact us if you got any problem.
5.5361414 ASWINN Tablet Floor Stand, Adjustable Universal 360-degree Rotatable Metal Tablet Holder, Ipad Stand Floor for iPad/iPhoneX/iPad Pro or Other 4.5~12.9 Inches Devices (Black)【Free Your Hands】: With this flexible robots arm tablet floor stand, you can find a more comfortable way to use iPad & iPhone in bed or sofa in winter. Release your hands while make your leisure time more enjoyable，the best Christmas gift or New Year gifts for wife,husband,elders,friend or colleague.【Versatile Robots arm iPad floor Stand】This ergonomic robots arm tablet holder suits most tablets and phones. you can easily get your desired angle to meet your needs at different angles and positions. Except for watching movies, you are also allowed to use your iPad for visual presentations, like reading sheet music, watching videos, zoom calls, online teaching, public speaking, reading e-books, giving performances, etc.【Wide Compatibility】It works with various tablets and mobile devices ranging from 4.5 to 12.9 inches, including iPad mini, iPad, iPad Air, iPad Pro 12.9'', and many other tablets. For smartphones like iPhone7, 7plus, 8, 8plus, x, XR, xs, xs max, iPhone 11, 12, 13,14 series.Galaxy Tab,Fire 7, Fire HD 8, Fire HD 10, N- Switch and etc.【360 degree rotation and height adjustable】 - The tablet floor stand can be rotated 360 degree, making it easy to switch your tablet from portrait mode to landscape mode. The height can be adjusted in a range of 27-62 inches, makes this iPad floor stand easy to suit all of your viewing postures, such as lying, sitting, standing and so on.【Strong Stability】Heavy duty base makes the stand more stable and reliable than others. The carbon steel and reinforced base guarantee the longer service life (Please keep the arm and base in the same direction, otherwise press the base with a heavy object). ASWINN tablet floor stand provides safe and secure support for your device.【Three Year Warranty】If there are some missing parts when you receive the product, please contact us directly for replacement. We provide high quality service,if you don't love it, you can get a full refund,total risk-free purchase,we provide three year warranty.
5.532309 COOPERS 7 inch Kids Tablet Android 11 Tablet for Kids, 2GB RAM + 32GB ROM Toddler Tablet PC for Children, IPS Touch Screen, Dual Camera, Dual Speaker, WiFi Computer Tablet, Light Blue✿【Good Kids tablet】This 7 inch tablet for kids with silm body and lightweight, it is easy to hold by children. Also the special design can protect the tablet well when dropping.✿【Parental Control】Toddlers Tablet with parent mode can add or block apps. Set screen time limits. This tablet come with iwawa app. kids can get access to fun and educational games and videos.✿【Powerful Tablets】Equipmented with quad core CPU, Android 11.0 System, 32GB Big Storage, 1024*600 IPS Screen offer a clear view. Runs Kinds of apps and game for kids smoothly.✿【Long Lasting】Tablet for kids built with large capacity battery. For mixed use up to 6 hours. You can enjoy happy parent-child time with your kids.✿【Best Gift】This high performance Children tablet is designed specially for kids. Best gift choice for Christmas, New Year, Easter, Birthday and school supplies. Pacakge come with 1* tablet, 1* charger, 1* cable
5.486265 All-New Fire HD 8 Tablet Case, Fire Tablet 8 &8 Plus Case for Kids (Compatible 2022 & 2020 Release) - Auorld Kid-Proof Light-Weight Case for Fire HD 8 inch Tablet, BlueTablet 8 Kids Case design specifically for all-new 8 inch Tablet and 8 Plus Tablet(12th/10th Generation, 2022/2020 Release), NOT fit for other models.Made with dense heavy duty EVA foam, material can withstand considerable wear and tear and provide extreme shock protection. Super lightweight and durable hazard free safe material perfect for kids and grownups alikePRECISE OPENINGS-Cutouts for easy access to all-new 8 inch tablet & 8 plus tablet buttons, ports, speakers and rear-camera. When installing, remove the black frame first.Raised screen bezel edges for extra protection when fallSpecial rear pattern with raised supports for grip and drop protection in a honey comb design. Anti-slip side grip feature with ergonomic grip supportsWhat You Get: 1x tablet case,friendly customer service. Accessory: the tablet don't be included, NO screen protector included
5.3858404 All-New 10and 10 Plus 2021 Tablet Case for Kids, Ubearkk Adult & Kids Friendly Light Weight Shock Proof Kid-Proof Back Cover Compatible 101h Generation 2021 ModelCompatibility- Designed for All-New ＨＤ 10 & ＨＤ 10 Plus Tablet & ＨＤ 10 Kids Pro Tablet Latest model(Only compatible with 11th Generation, 2021 Release). NOT Fit for other generations.Kids-proof Case-Made with dense heavy duty EVA foam material can withstand considerable wear and tear and provide extreme shock protection. Super light weight and durable hazard free safe material perfect for kids and grownups alike.Built-in Kickstand - Designed with a foldable kick-stand on the back of the case, allows you to set up multiple angles and gives you the hands-free convenience when watching videos and movies.Precise cutouts- Full access to all ports, buttons, and cameras, speakers and rear-camera without removing the tablet case.What You Get- Tablet case x 1.(The tablet is not included, and NO screen protector included). If you encounter any problems, please feel free to contact us.
5.3329716 TCL Android 11 Tablet TAB 8V, Up to 512GB, Portable 8 Inch Tablets, HD Display Touch Screen, 4080mAh Battery, 5G Wi-Fi Gaming Tablet with 5MP Camera Small Cheap Tableta for Kids, Adults👍【Just Right for Holding &Pockets Tablet】—Weighing just 310g, Lighter than the weight of an apple, Suitable as Pockets Tablet. TCL TAB 8V tablet is an idea for people on the go so you can easily hold it with one hand and keep hands from getting tired, even playing for hours.⚙【Android 11 Operating System】—Android 11 tablets has enhanced security and privacy features, as well as optimized the notification bar settings and Hotkeys for greater security and convenience.💾【512GB for Record Your Fun】—Tableta with 64 GB of internal storage (up to 512 GB of expandable storage with microSD, sold separately). Enjoy your favorite apps through the Google Play Store.⚡【4080mAh Long-lasting Tablet】—Long-lasting Battery Tab supports 10 hours of online video streaming or 6 hours of online game play. Power for All Day Fun🖥【See Brighter Colors】—See 16 million colors on a compact 8" HD 800x1280 Pixels screen with thin 9.8mm bezels. 3 types of eye protection modes (dedicated modes and features optimize brightness and E-book reading modes) allow you to switch freely according to your needs.
5.3119125 iFongsh Tablet Stand Tripod, 80'' Tablet Stand Floor, Adjustable Gooseneck Tablet Stand with Tablet and Phone Holder Compatible with iPad Pro 12.9, Mini, Air, iPhone, All 4.7"-13" Tablet and Phone【More Usage Scenarios】iFongsh tablet holder makes it easier for you to use your tablet in various places, freeing your hands. Perfect for online meetings, presentations, lectures, reading, video chatting, learning, drawing, video editing. You can also use it in bedroom, living room, kitchen, bathroom, office, classroom, seminar, camping, indoor and outdoor.【Height Adjustable & Extendable】The stable tablet floor stand can meet your various use heights, whether sitting, lying, or standing, you can use your tablet comfortably. The tablet tripod with 4-section telescopic pole can be used in 15.5'' between 80'' Adjust freely. You can easily get the desired angle to suit your needs in different angles and positions.【Wide Compatibility】The tablet stand comes with a tablet holder and phone holder. The tablet holder is compatible with iPad Pro 12.9, iPad Mini, iPad Air, All Width Between 5.2"-8.5" Tablet. The phone holder is compatible withall phones and power banks for all widths between 2 '' to 3.2'' . Two holder hold your phone and tablet securely.【360° rotation & Flexible Angle Adjustment】The back of the tablet holder is equipped with an angle adjustment ball to easily tilt left and right and rotate 360 degrees for portrait and landscape viewing when in use. The sturdy and flexible gooseneck hose attached to the tablet holder can be easily adjusted to any angle, so you can comfortable use your tablet while you are standing, sitting or lying down【Hight Quailty & Upgraed Materials】iFongsh tablet stand consists of an aluminum alloy tripod. The top of the tripod is equipped with a universal 1/4 screw, which can be adapted to cameras, ring lights, etc. Package Inlueds: 1* Tripod, 1* Gooseneck Hose, 1* Tablet Holder, 1* Phone Holder, 1* Carrying Bag.
5.157914 TECLAST Android 12 Tablet 10 inch, Tablets P30S 4GB RAM+64GB ROM(TF 1TB), 8-Core Processor 2.0GHz, 2.4G&5G WiFi Tablet, Face Recognition, Dual Cameras, BT5.0, GPS, Google GMS Certified【Latest Android 12 Tablet + GMS Certification】Google tablet with latest Android 12 have new features such as split-screen support, device control, and screen record ect, and it can run multiple software smoothly at the same time. The 10 inch tablet PC is GMS certified by Google and get rid of unexpected ads and download richs apps from Google Play, such as Netflix, YouTube, Facebook, Twitter, etc.【Octa-Core+4GB+64GB】Android 12 Tablet adopts Octa-Core CPU "MT8183" developed by MediaTek, It is equipped with four high-performance cores of A73 architecture up to 2.0 GHz, and various enhancements enable nimber operation and faster processing. Equipped with 4GB LPDDR4X and 64GB of storage space, you can run multiple software smoothly at the same time!【Colorful Lightweight Tablet】The 10 inch tablet have blue metal body design and a thin 520g lightweight body of only 9mm, it is compact and easy to carry when traveling on business trips and trips. Adopts IPS Display, presenting a bright display with Vivid Colors for a more True-to-life Viewing experience, Brings you a Crisper and Brighter image.【Dual WiFi + Face Recognition】 The Android tablet support 2.4&5GHz dual band WiFi connection, can achieve stable connection and high-speed communication. In addition to PIN password unlocking, the tablet also supports face unlocking, which is more convenient and simple. It also supports GPS and the Global Navigation System to provide faster and more accurate directional navigation. (WIFI is required when using the car navigation system).【Dual Cameras + Bluetooth 5.0】Android Tablet 10 inch Tablet with Front 2.0 Mega pixel, Back 5.0 Mega pixel camera with Flash Light. Support Bluetooth 5.0 connectivity works with all your favorite accessories (keyboard).
5.0990763 JSAUX Tablet Pillow Stand, Tablet Stand Holder Dock for Lap, Bed and Desk Compatible with iPad Pro 11 10.5 9.7 10.2 Air Mini, Kindle, Tablets, Phones, E-Reader, Books and More 4-11'' devices Navy Blue【Tablet Pillow Stand】JSAUX tablet pillow stand is perfect for Reading, watching videos&photos or typing while lying in bed, or sitting on sofa or rug. It holds your device well and make your life wonderful.【Compatibility】Compatible with iPad mini 2 3 4 5 6, iPad 2017, 2018, 2019, 2020, 2021, iPad Pro 2016,2017, iPad Pro 11-inch, iPad Air 2013, 2014, 2019, 2020, 2022 (1st - 5th generation), Samsung Galaxy Tab S6 Lite, S7, S8, A7, A7 Lite, A8, A8.4, e-readers, Kindle, Kindle Paperwhite, Kindle Oasis, Kindle Scribe, Fire, Fire Plus, Fire Kids, Fire Kids Pro, smartphones and more 4-11 inches devices.【Multi-angle Viewing】The soft and skin-friendly iPad holder has multi angle adjustments. With the combination of hook and loop strips & deeper grooves, you can freely adjust to a comfortable viewing angle.【Considerate Details】JSAUX tablet stand holder dock provides more considerate details design. The mesh net pocket can be used to put the charging cable and charger. The pencil holder for your pencil fixing. Removable and washable soft case with bottom invisible zipper.【What You Get】We provide this tablet holder with an 18-Month worry-free period and 24/7 friendly client consultation, if you have any questions, we will resolve your issue within 24 hours.
5.037449 Tablet Shoulder Sleeve Bag for 11 inch iPad Pro,10.9 inch iPad Air 4,10.2 in iPad, Tablet Sleeve Carrying Case (10.9inch)【Dimension & Compatible】Internal dimensions:11"x8"x2.5",iPad bag perfectly fit 11" iPad Pro 1st/2nd/3rd generation (2018-2021 Model)/ 10.9" iPad Air 4 /10.5 inch Pad Air/ iPad Pro with Magic/Smart Keyboard Folio or Logitech Slim Folio Pro Case, Microsoft Surface Go 3/2/1; 10.2" iPad, 9.7"11" iPad Pro/ iPad Air/iPad, iPad Mini 5/4/3/2/1 with cover on it, 10.1 Samsung Galaxy Tablet, Fire 7/Fire HD 8/All-new Fire HD 10/Introducing Fire HD 10 Productivity Bundle【Splash-proof & Perfect Protection】The tablet sleeve is made of high-quality polyester external and soft inner lining,which is not only splash-proof but also protect your tablet and accessories from drops, bumps and scratches.【Large Capacity】The large number of inner compartments design can enough iPads, books and daily necessities(mobile phones,umbrella,wallet, passport,etc.).Three external pocket storage accessories(chargers, cables, power bank, USB drives, etc.).【Different Applications】Fashion and Lightweight Design meet all your requirements for daily use at work, business trip, go to school, business meeting or speech etc.【What You Get】11 inch tablet shoulder bag, our worry-free 24-month warranty and friendly customer service.

In [19]:
def get_both_denceandBM25(query,k=20):
    query_embedding = get_embedding(query)
    result = qdrant_client.query_points(
        collection_name="Amazon-items-collection-02-hybrid-serach",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-model-3-small",
                limit=20
            ),
            Prefetch(
                query=Document(
                    text=query,
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=20
            )

        ],
        query=FusionQuery(fusion="rrf"),
        limit=20
    )

    return result

In [20]:
result=get_both_denceandBM25("can i get some Tablet")

In [25]:
for point in result.points:
    print(point.payload['description'])

Android Tablet 10.1 Inch, Tablet with Keyboard, 2 in 1 Tablets 64GB Memory 4G RAM 128GB Expandable, 5G WiFi Tablet, Android 11, 13MP Camera, Large Battery, Tablet with Case, Keyboard, Mouse, StylusAndroid 11.0 Standard OS Google Tablet: 2022 Newest android tablet runs the latest android 11.0 OS, which is easier when set up and operate. Google base can better protect your privacy and compatible with more apps in pre-installed google play store. Get yourself a wonderful tablet and all your favourite apps on it.WiFi tablet Support Dual band 2.4+5Ghz: 5G WiFi tablet support not only 5Ghz Wifi but also 2.4Ghz wifi meet anyone needs. No restrictions on any usage environment, whether you live in a hotel/apartment with only 5Ghz WiFi, or in your home with 2.4Ghz wifi, it can be easily connected, provides the best speed when using this tablet.Tablet 64GB Storage 128GB Micro SD Expandable: 2 in 1 android 11 tablet has a 1.6 GHz high-efficiency Quad-core processor, 4GB RAM+64GB ROM, fast and responsive. 128GB expandable by Micro SD Card. 6000mAh battery provide a long using time and standby time. 5V 2A charger with USB-C cable can charge faster.Tablet with all the accessories you need: Tablet with Keyboard, Mouse, Tablet Case and Stylus, OTG. Wireless Keyboard and Mouse connect with Bluetooth, get rid of the shackles of wire, you can use it in anywhere. The custom case can all around protect your tablet and provide a sturdy stand.ZONKO Lifetime Tech-support: Tablets with a exact touch-screen, the screen clarity is super crisp. It is suitable big tablet for children or your parents and your friends as a ideal Christmas gift to surf the internet, browse emails, read e-books and watch videos. We offer lifetime technical support and 365-days warranty. Feel free to contact us if you got any problem.
ALZHIJ Portable Tablet Holder Stand - Aluminum Alloy Desktop Stand Adjustable Angle&Height Tablet Stand Holder Creative Tablet Stand Compatible with Various Tablet UP to 12IN Wide (Grey)😃MADE OF HIGH-QUALITY MATERIALS:The high-quality aluminum alloy material achieves the perfect performance of the tablet holder for bed, making the tablet wear-resistant and scratch-resistant, and has excellent corrosion resistance. The superb anodizing process increases the color and luster of the table stand and makes it richer in texture.😃EXQUISITE APPEARANCE DESIGN:The personalized smiley face design can not only be a better decoration for this tablet stand for desk, but also provide a long-lasting heat dissipation effect for the tablet during use, making your tablet run more efficiently. The tablet stand for bed is designed with multiple non-slip silicone pads to protect the tablet from damage at all times.😃180°FREELY ADJUSTABLE ANGLE:The tablet floor stand adopts a stable dual-axis mechanism design, which is firm and not easy to shake. The angle and height can be adjusted arbitrarily, giving you a perfect experience. Lightweight and portable adjustable stand, completely bid farewell to the troubles of traditional stand that are too heavy and make your life more convenient.😃A WIDE RANGE OF APPLICATIONS:A tablet stand that integrates practical, beautiful, portable and other elements into one. It has a wide range of applications and can be compatible with various tablet up to 15.6 inches wide. The adjustable tablet stand can be used for work, travel, watching drama, and study, giving you a perfect experience.😃OUR GURANTEE FOR YOU:Everything I do is based on customer satisfaction. If you are not completely satisfied with the purchased product or the product is damaged or broken in transit, please contact us in time. We will solve your problem as quickly as possible!
ASWINN Tablet Floor Stand, Adjustable Universal 360-degree Rotatable Metal Tablet Holder, Ipad Stand Floor for iPad/iPhoneX/iPad Pro or Other 4.5~12.9 Inches Devices (Black)【Free Your Hands】: With this flexible robots arm tablet floor stand, you can find a more comfortable way to use iPad & iPhone in bed or sofa in winter. Release your hands while make your leisure time more enjoyable，the best Christmas gift or New Year gifts for wife,husband,elders,friend or colleague.【Versatile Robots arm iPad floor Stand】This ergonomic robots arm tablet holder suits most tablets and phones. you can easily get your desired angle to meet your needs at different angles and positions. Except for watching movies, you are also allowed to use your iPad for visual presentations, like reading sheet music, watching videos, zoom calls, online teaching, public speaking, reading e-books, giving performances, etc.【Wide Compatibility】It works with various tablets and mobile devices ranging from 4.5 to 12.9 inches, including iPad mini, iPad, iPad Air, iPad Pro 12.9'', and many other tablets. For smartphones like iPhone7, 7plus, 8, 8plus, x, XR, xs, xs max, iPhone 11, 12, 13,14 series.Galaxy Tab,Fire 7, Fire HD 8, Fire HD 10, N- Switch and etc.【360 degree rotation and height adjustable】 - The tablet floor stand can be rotated 360 degree, making it easy to switch your tablet from portrait mode to landscape mode. The height can be adjusted in a range of 27-62 inches, makes this iPad floor stand easy to suit all of your viewing postures, such as lying, sitting, standing and so on.【Strong Stability】Heavy duty base makes the stand more stable and reliable than others. The carbon steel and reinforced base guarantee the longer service life (Please keep the arm and base in the same direction, otherwise press the base with a heavy object). ASWINN tablet floor stand provides safe and secure support for your device.【Three Year Warranty】If there are some missing parts when you receive the product, please contact us directly for replacement. We provide high quality service,if you don't love it, you can get a full refund,total risk-free purchase,we provide three year warranty.
CUPEISI 10 inch Tablet, Android 11 Tablets, 64GB ROM+2GB RAM, Quad-Core Processor Tablet PC, 1280 * 800 IPS HD Display, 2MP+8MP Dual Camera, 6000mAh Tableta.[HIGH PERFORMANCE ANDROID TABLET ] - CUPEISI YQ10S tablets comes with Android 11 OS, 2GB RAM, 64 GB ROM, the powerful and energy-saving Quad-core Processor enables quicker app launch, smoother videos, you can enjoy better overall performance experience. In addition, it includes a Micro SD card slot (can be added a expanded 256 GB TF Card Max, NOT included), making it easy to store Pictures videos, files etc. There is NO extra bloatware installed. Note: This tablet can't add a SIM Card.[LONG-LASTING ENTERTAINMENT] - CUPEISI 10 inch tablet features android 11, GMS Certified, you can download thousands of apps, such as, Netflix, YouTube, Skype, and more popular apps. The large battery and low-power CPU enhance your experience and allow you to enjoy up to 8 hours of mixed reading, watching TV shows, surfing the web, playing light games and more. It is a really good companion for your leisure and entertainment. Large IPS Touchscreen will be a plus.[LOW BLOATWARE & DUAL CAMERA] - With Front 2.0 MP & Rear 8.0 MP camera, which would bring your photos and videos to life. CUPEISI YQ10S 10'' tablet rivals most of the 10 inch tablet and it is convenient for taking photos, capturing and sharing those special moments with your friends and family. CUPEISI tablet meets your basic daily needs, such as watching videos, Live and reading. A good tablet for your choise, very Low bloatware, No ads![BRILLIANT IPS DISPLAY ] - CUPEISI 10 inch tablet PC adopts a 1280 x 800 brilliant HD IPS display. This android tablet has a sharper hierarchy of images and richer colors, and provides shocking performance of visual experience. With the Eye Health mode, an extra feature filters out blue light to relieve visual fatigue, and optimizes the backlight for a more comfortable reading experience.[WARRANTY & SUPPORT] - CUPEISI Tablet PC comes with 1-year worry-free guarantee - If it is the tablet quality issue, return it and we’ll replace it for free. CUPEISI team focuses on the customer's pleasant shopping experience and provides reliable customer service. Please do not hesitate to contact us if you have any problem, we will give you on-time TECH SUPPORT and the better customer service. Looking foward to hearing from you(CS email).
TCL Android 11 Tablet TAB 8V, Up to 512GB, Portable 8 Inch Tablets, HD Display Touch Screen, 4080mAh Battery, 5G Wi-Fi Gaming Tablet with 5MP Camera Small Cheap Tableta for Kids, Adults👍【Just Right for Holding &Pockets Tablet】—Weighing just 310g, Lighter than the weight of an apple, Suitable as Pockets Tablet. TCL TAB 8V tablet is an idea for people on the go so you can easily hold it with one hand and keep hands from getting tired, even playing for hours.⚙【Android 11 Operating System】—Android 11 tablets has enhanced security and privacy features, as well as optimized the notification bar settings and Hotkeys for greater security and convenience.💾【512GB for Record Your Fun】—Tableta with 64 GB of internal storage (up to 512 GB of expandable storage with microSD, sold separately). Enjoy your favorite apps through the Google Play Store.⚡【4080mAh Long-lasting Tablet】—Long-lasting Battery Tab supports 10 hours of online video streaming or 6 hours of online game play. Power for All Day Fun🖥【See Brighter Colors】—See 16 million colors on a compact 8" HD 800x1280 Pixels screen with thin 9.8mm bezels. 3 types of eye protection modes (dedicated modes and features optimize brightness and E-book reading modes) allow you to switch freely according to your needs.
ATOZEE Tablet 10 Inch Tablet, Android 11 Tablets, 64GB and 512GB Expand Tableta, Quad-Core Processor 2GB RAM 8MP Camera WiFi GPS FM Tablet Computer, 10.1 in HD Display Long Battery Life Tabletas【64GB Tablet】 The tablet comes with 64GB of built-in storage and up to 512GB of expandable microSD card storage for more space, you can download various ebooks, songs, photos or movies.【Excellent Performance】 This Google tablet AT10 featuring with powerful Quad-core 1.5GHz CPU, 2GB RAM and newest Android 11.0 operating system, with 10.0" capacitive touch, five point cap-touch G+G, ensure a more fluently action for movie and game.【Enjoy Video and Music】 ATOZEE tablet benefit from 1280*800 IPS high-definition touch screen and 178-degree wide viewing angle, the 10.1-inch tablet gives a more vivid display and excellent picture quality. Capture photos and videos with the front 2MP and rear 8MP cameras to share moments with friends and family. Dual-box speakers provide you with an excellent audio-visual experience.【Smooth Operation】 The high-performance tablet ensures smooth web browsing and video playback. The new GMS certified Android 11.0 operating system eliminates unwanted ads. Enjoy full access to Google services and applications such as Gmail, Youtube, Google Drive, Play Store and more.【Long Battery Life】 The 6000mAh rechargeable battery and low-power CPU enable up to 8 hours of mixed use on the go, perfect for long commutes and travel. Equipped with 5V2A charging brick and type C cable.
COOPERS 7 inch Kids Tablet Android 11 Tablet for Kids, 2GB RAM + 32GB ROM Toddler Tablet PC for Children, IPS Touch Screen, Dual Camera, Dual Speaker, WiFi Computer Tablet, Light Blue✿【Good Kids tablet】This 7 inch tablet for kids with silm body and lightweight, it is easy to hold by children. Also the special design can protect the tablet well when dropping.✿【Parental Control】Toddlers Tablet with parent mode can add or block apps. Set screen time limits. This tablet come with iwawa app. kids can get access to fun and educational games and videos.✿【Powerful Tablets】Equipmented with quad core CPU, Android 11.0 System, 32GB Big Storage, 1024*600 IPS Screen offer a clear view. Runs Kinds of apps and game for kids smoothly.✿【Long Lasting】Tablet for kids built with large capacity battery. For mixed use up to 6 hours. You can enjoy happy parent-child time with your kids.✿【Best Gift】This high performance Children tablet is designed specially for kids. Best gift choice for Christmas, New Year, Easter, Birthday and school supplies. Pacakge come with 1* tablet, 1* charger, 1* cable
G-TiDE Kids Tablet, 7 inch Tablet for Kids, 32GB+2GB Kids Learning Tablet, 5MP Dual Camera HD, Parental Control App- KLAP, Toddler Tablet Case, WiFi Tablets Shoulder Straps, Pink🤗【Explore More Fun on Klap】G-TiDE Klap kids tablet is designed for learning and playing. This tablet for kids offers various creative contents such as brain training, painting, gaming, kids TV, etc. Learning while playing is better for kids to know the world. With a 32GB bigger storage, which can be extended to 128GB (micro SD card not included), this kids tablet is perfect for children aged 3-7 years old. You could get more educational apps from Google Play Store (GMS).🤗【Kids-proof Case & Eye-protection Screen】G-TiDE's exclusive kids tablet case is made of impact-resistant EVA material. When your kid is playing outdoors with the tablet or accidentally dropping the tablet on the ground at home, it protects the kids tablet from bumps and minor drops. This kids tablet comes with an adjustable shoulder strap, so your little one can take their tablet wherever they go. With a 270° adjustable stand, you can place it at the distance that suits your kids best.🤗【Amazing Experience on Klap Kids Tablet】G-TiDE Klap kids tablet offers an amazing experience with its learning & playing App - Klap. This app offers various creative content such as brain training, painting, gaming, kids TV etc. Learning while playing is better for kids to gain more knowledge. When there are more children, they can also watch kid's TV and play two-player games, they can also learn from each other. This kids tablet is perfect for children aged 3-7 years old and has a storage capacity of 32GB, which can be expanded up to 128GB(micro SD card not included). You can download more apps from Google Play Store, like YouTube Kids, Netflix, and other popular apps for kids tablets.🤗【Easy Parental Controls】KLAP has parental controls that allow you to create over 20 different children's accounts and customize learning content and time limits according to their individual needs. It also includes features such as a child lock, remote video control, content filtering, a one-button lock screen, and alarm setting to ensure your children can safely browse websites. When you're busy working and don't have time to supervise your children, you can set content and time limits for them to play.🎁【Perfect Gift For Kids】G-TiDE S1 provides endless online age-appropriate content, ensuring safe browsing for kids aged 3-7 years old. It offers an easy and fun way for kids to learn and play. This makes it the perfect gift for your child for Christmas and birthdays. We offer a 12-month worry-free guarantee, and you can find our official mailbox on the package's back for any service-related inquiries. Please don't hesitate to contact us if you have any questions about our tablets. G-TiDE is always by your side.
Tablet 10 inch Latest 128 GB ROM Android 11 Q10PRO Tablets:4GB RAM|5G/4G Wi-Fi|Octa-Core|8000mAh|Bluetooth|Google Certified Tablet with Keyboard, Mouse, Earphones etc./Support Split Screen-Green【High Performance & storage】 Facetel Q10 Tablet has a built-in 4GB running memory，enjoy smooth multitasking and switching. between applications. 128GB storage capacity, includes a micro SD card slot, (MicroSD can be expanded to 128GB), allows you to store all your files,meet your daily entertainment and work needs.【Split Screen & Fast Runnung】The Q10PRO with the latest Android 11 and is Google certified, so there's no need to worry about app compatibility. Pre-installed with Google Play, you can freely download any app from the store, games, music, beauty, email, weather, social apps and more.It also supports 2.4G & 5G WiFi and application split screen, giving you a high-speed internet connection, Two Apps for use on the same screen and video playback experience.【Powerful battery life】8000mAh battery combined with SC610 1.6 GHz Octa-Core processor, lower power consumption, audio and video entertainment, games and learning, office meetings, fearless use of any scene, can be continuous 720 hours of standby, 20 hours of calls, 24 hours of MP3 music, 6-8 hours of online video, and with Type-c charging cable, so you can use the tablet with confidence.【Crisp G+G Ips Display & Dual Speakers】 Featuring 1280 x 800 HD IPS display with dual speakers, 5MP front and 8MP rear, the display presents a bright display that will give you the HD experience whether you are watching videos, reading e-books, or playing games, a very pleasant visual and auditory experience for the user.while the G+G glass screen is highly transparent and scratch resistant, making your tablet more durable.(There is a new protective film placed in the Tablet pack)【Lightweight, portable & colorful design】The 10.1-inch tablet has a thin and light design with a more sturdy and beautiful metal frame, which is suitable for carrying around and can give a quality experience whether you are working or traveling.Currently there are two tablet colors for you to choose from: elegant green and temperamental black. We have a professional service team with a 24-month worry-free warranty and friendly customer service, if you have any questions, please contact us through Amazon, we will help you solve the problem and give you a satisfactory solution.
All-New Fire HD 8 Tablet Case, Fire Tablet 8 &8 Plus Case for Kids (Compatible 2022 & 2020 Release) - Auorld Kid-Proof Light-Weight Case for Fire HD 8 inch Tablet, BlueTablet 8 Kids Case design specifically for all-new 8 inch Tablet and 8 Plus Tablet(12th/10th Generation, 2022/2020 Release), NOT fit for other models.Made with dense heavy duty EVA foam, material can withstand considerable wear and tear and provide extreme shock protection. Super lightweight and durable hazard free safe material perfect for kids and grownups alikePRECISE OPENINGS-Cutouts for easy access to all-new 8 inch tablet & 8 plus tablet buttons, ports, speakers and rear-camera. When installing, remove the black frame first.Raised screen bezel edges for extra protection when fallSpecial rear pattern with raised supports for grip and drop protection in a honey comb design. Anti-slip side grip feature with ergonomic grip supportsWhat You Get: 1x tablet case,friendly customer service. Accessory: the tablet don't be included, NO screen protector included
All-New 10and 10 Plus 2021 Tablet Case for Kids, Ubearkk Adult & Kids Friendly Light Weight Shock Proof Kid-Proof Back Cover Compatible 101h Generation 2021 ModelCompatibility- Designed for All-New ＨＤ 10 & ＨＤ 10 Plus Tablet & ＨＤ 10 Kids Pro Tablet Latest model(Only compatible with 11th Generation, 2021 Release). NOT Fit for other generations.Kids-proof Case-Made with dense heavy duty EVA foam material can withstand considerable wear and tear and provide extreme shock protection. Super light weight and durable hazard free safe material perfect for kids and grownups alike.Built-in Kickstand - Designed with a foldable kick-stand on the back of the case, allows you to set up multiple angles and gives you the hands-free convenience when watching videos and movies.Precise cutouts- Full access to all ports, buttons, and cameras, speakers and rear-camera without removing the tablet case.What You Get- Tablet case x 1.(The tablet is not included, and NO screen protector included). If you encounter any problems, please feel free to contact us.

In [ ]:
def reteriver_data(query, quadrant_client, k):
    
    query_embedding = get_embedding(query)
    result = quadrant_client.query_points(
        collection_name="Amazon-items-collection-02-hybrid-serach",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-model-3-small",
                limit=20
            ),
            Prefetch(
                query=Document(
                    text=query,
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=20
            )

        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    retrieved_context_rating = []
    retrieved_image_urls = []
    retrieved_prices = []

    for point in result.points:
        payload = point.payload or {}
        retrieved_context_ids.append(payload.get("parent_asin"))
        retrieved_context.append(payload.get("description", ""))
        retrieved_context_rating.append(payload.get("average_rating"))
        similarity_scores.append(point.score)
        retrieved_image_urls.append(payload.get("image", ""))
        retrieved_prices.append(payload.get("price"))

    return (
        retrieved_context,
        retrieved_context_ids,
        retrieved_context_rating,
        similarity_scores,
        retrieved_image_urls,
        retrieved_prices
    )

In [68]:
result=reteriver_data("can i get some ipad",quadrant_client,k=20)

In [45]:
result

(['Case for iPad Pro 12.9 2022/2021/2020/2018 Gen 6th/5th/4th/3rd,2 in 1 Detachable Magnetic Case,Anti-Fingerprint Frosted Case and Washable Leather Protective Cover Support Pen Charger(Pink)✅【Protective Case for iPad Pro 12.9】❗❗No Pen included!❗❗The protective cover is designed for iPad Pro 12.9" 6th Gen 2022 (Model number: A2764/A2436/A2437/A2766),5th Gen 2021 (Model number: A2378/A2379/A2461/A2462),4th Gen 2020 (A2229/A2069/A2232/A2233),3rd Gen 2018 (A1876/A1895/A1983/A2014).♐It\'s Not compatible with any other devices. Please check the model number of your iPad back bottom.✅【2 in 1 Detachable & Magnetic Cover】The detachable design is more convenient to carry and use. When it\'s used as a protective case, you have a video mode or a writing mode. When it detached, you get the phone holder.✅【Washable & Stain-resistant Case】The premium leather and frosted case are both washable. You can easily get a new look on your case with a single tissue, even if it\'s stained with coffee, oil, or other grime.🔴And the frosted case is anti-fingerprint.🔴✅【Smart Folio & Pencil 2 Compatible】Our protective case supports auto sleep/wake function, which can extend the life of your ipad. It also supports Pencil’s magnetic attachment and wireless charging.✅【Full Protection & Warranty Support】 The all-inclusive design with upgrade edged for camera and screen can protect your iPad well. We provide our customers with a 24/7 Email Service & Returnable Guarantee. If you have any questions or suggestions, please contact us.',
  'MEEgoodo Case for Kids iPad Pro M2 12.9 Case 6th/5th/4th/3rd Generation 2022 2021 2020 2018 with Pencil Holder/Rotating Stand/Shoulder Strap, Protection Duty Shockproof Silicone Cover, Emerald Green𝘿𝙀𝙎𝙄𝙂𝙉𝙀𝘿 𝙁𝙊𝙍 𝙄𝙋𝘼𝘿 𝙋𝙍𝙊 𝙈𝟮 𝟭𝟮.𝟵 𝙄𝙉𝘾𝙃 𝘾𝘼𝙎𝙀 𝟮𝟬𝟮𝟮 𝟮𝟬𝟮𝟭 𝟮𝟬𝟮𝟬 𝟮𝟬𝟭𝟴 - 𝗢𝗡𝗟𝗬 Compatible with Model iPad Pro M2 6th Generation 12.9" 2022, Model Number:A2436/A2764/A2437/A2766 and iPad Pro 5th Generation 12.9" 2021, Model Number: A2379/A2461/A2462 /A2378 and iPad Pro 4th Generation 12.9" 2020, Model : A2229/A2069/A2232/A2233 and iPad Pro 3rd Generation 12.9" 2018, Model : A1876/A1895/1983/A2014.𝙉𝙤𝙩 compatible with any other iPad models.𝙈𝙐𝙇𝙏𝙄𝙁𝙐𝙉𝘾𝙏𝙄𝙊𝙉𝘼𝙇 𝙃𝘼𝙉𝘿𝙇𝙀-𝙆𝙄𝘾𝙆𝙎𝙏𝘼𝙉𝘿 - The 360 Degree rotating Kickstand provides multi-angle viewing(easy to grip & comfortable to hold), easy to use your case ipad pro 12.9 in your outdoor traveling, working, gaming with kids. Hanging your iPad on the wall easy access to your favorite shows. Provide protection and convenience when you play or work with iPad.𝟯-𝙄𝙉-𝟭 𝙋𝙍𝙊𝙏𝙀𝘾𝙏𝙄𝙑𝙀 𝘿𝙀𝙎𝙄𝙂𝙉 -The New 12.9 ipad pro case is made from the Three-layer structure design with screen frame, Slim Heavy Duty Shockproof Soft Silicone & Plastic providing full-body protection to prevent drops, shocks, bumps, scratches and dirt. Guaranteed to withstand normal usage while looking amazing.𝙍𝙀𝙈𝙊𝙑𝘼𝘽𝙇𝙀 & 𝘼𝘿𝙅𝙐𝙎𝙏𝙈𝙀𝙉𝙏 𝘾𝘼𝙍𝙍𝙔𝙄𝙉𝙂 𝙎𝙏𝙍𝘼𝙋 - Portable Shoulder Strap allows to carry your iPad conveniently when you are at work, on a trip or outdoors. You could even hang it behind the head rest of car seat or wherever you want.𝘾𝙐𝙎𝙏𝙊𝙈𝙀𝙍 𝙎𝙀𝙍𝙑𝙄𝘾𝙀 - Convenient to use all the controls and features (Cameras, Speaker, Ports and Buttons). If you are ever not satisfied with the performance of MEEgoodo for iPad Pro Case simply contact us we’ll give you a refund. The warranty period of our company is one year warranty, repair applications can be submitted within this time frame.',
  'GEEKSDOM STOCK Case Compatible with iPad 9th Generation, Military Grade Drop Tested Full Body Heavy Duty Shockproof Protective Cover for iPad 9th Gen 10.2 Inch 2021 with Stand🌲🌲[Compatible Models] - Designed specifically for iPad 10.2 9th/8th/7th generation case (A2602 A2603 A2604 A2605 / A2270 A2428 A2429 A2430/A2197 A2198 A2200 ) 2021/2020/2019. Screen protector not included.🌲🌲[Full Body Protection]: Three-Layer shockproof case has passed the Military Grade Drop Test: MIL-STD 810G-516.6. This iPad 9th generation case is made of flexible TPU and hard PC, offers 360 full body protection to your iPad 10.2 from daily bumps, scrapes, and accidental drops.🌲🌲[Adjustable Hand Strap + 360 Rotatable Kickstand]: Adjustable hand strap prevents your iPad 9th gen slipping out from your hand. 360° rotating stand supports the position of multi-angles and outdoor travelling, working, gaming with kids.🌲🌲[Pencil Holder + Precise Cutouts]: Designed with pencil holder, Not occupying space and easy to put the Apple Pencil in and out. The case allows easy access to all buttons and port covers of the case to prevent dust from entering into iPad 10.2 2021.🎁🎁[Detachable Shoulder Strap] Free your hands! iPad 10.2 9th generation case \u200bperfect for traveling, climbing, going business, etc.',
  "ASWINN Tablet Floor Stand, Adjustable Universal 360-degree Rotatable Metal Tablet Holder, Ipad Stand Floor for iPad/iPhoneX/iPad Pro or Other 4.5~12.9 Inches Devices (Black)【Free Your Hands】: With this flexible robots arm tablet floor stand, you can find a more comfortable way to use iPad & iPhone in bed or sofa in winter. Release your hands while make your leisure time more enjoyable，the best Christmas gift or New Year gifts for wife,husband,elders,friend or colleague.【Versatile Robots arm iPad floor Stand】This ergonomic robots arm tablet holder suits most tablets and phones. you can easily get your desired angle to meet your needs at different angles and positions. Except for watching movies, you are also allowed to use your iPad for visual presentations, like reading sheet music, watching videos, zoom calls, online teaching, public speaking, reading e-books, giving performances, etc.【Wide Compatibility】It works with various tablets and mobile devices ranging from 4.5 to 12.9 inches, including iPad mini, iPad, iPad Air, iPad Pro 12.9'', and many other tablets. For smartphones like iPhone7, 7plus, 8, 8plus, x, XR, xs, xs max, iPhone 11, 12, 13,14 series.Galaxy Tab,Fire 7, Fire HD 8, Fire HD 10, N- Switch and etc.【360 degree rotation and height adjustable】 - The tablet floor stand can be rotated 360 degree, making it easy to switch your tablet from portrait mode to landscape mode. The height can be adjusted in a range of 27-62 inches, makes this iPad floor stand easy to suit all of your viewing postures, such as lying, sitting, standing and so on.【Strong Stability】Heavy duty base makes the stand more stable and reliable than others. The carbon steel and reinforced base guarantee the longer service life (Please keep the arm and base in the same direction, otherwise press the base with a heavy object). ASWINN tablet floor stand provides safe and secure support for your device.【Three Year Warranty】If there are some missing parts when you receive the product, please contact us directly for replacement. We provide high quality service,if you don't love it, you can get a full refund,total risk-free purchase,we provide three year warranty.",
  'YIMIKOL Kids Case for iPad 9th Generation/iPad 8th Generation/iPad 7th Generation, iPad 10.2 inch Case 2021/2020/2019, Heavy Duty Shockproof Rugged Protective 10.2" Cover for Boys Girls (Black+Gold)🍎【Compatible Models】 YIMIKOL case compatible with 10.2 inch new ipad 9th generation (2021 Released)/iPad 8th Generation (2020)/iPad 7th generation (2019) . Model Number: (A2602 A2603 A2604 A2605/ A2270 A2428 A2429 A2430/ A2197 A2198 A2200). NOT fits for any other devices.🍎【3 Layer Shockproof Design】 This kid case for iPad 9th generation made of durable hard PC+silicone, 3-layer full body protection structure, provide a perfect protection & anti-scratch. NOTE: This ipad 10.2 inch case WITHOUT built-in screen protector.🍎【Functional Kickstand】 Case for 9th generation ipad 10.2 inch built-in convenient kickstand with 2 angles: Typing & Viewing angles. Premium case for ipad 7th generation is convenient for studying, gaming, watching video, etc.🍎【Precise Cutouts】 The kids case for ipad 8th generation is easy to access all buttons, speakers, cameras through the precisely-cut openings. Especially the charging port with rubber flap which can keep dust out. It\'s also a nice and practical gift for your kids and friends.🍎【What You Get】 If you have any questions of our case for ipad 7th/8th/9th generation 10.2 inch, please feel free to contact us at any time. We sure all the question can be solved properly.',
  'ESR for iPad Air 5th Generation Case 2022 / iPad Air 4th Case 2020, Rugged Protection, Detachable Magnetic Cover, Adjustable Portrait/Landscape Stand with Raised Screen View, 8 Stand Angles, BlackCompatibility: only compatible with iPad Air 5th Generation 2022 and iPad Air 4th Generation 2020; not compatible with any other iPad modelsDetachable Magnetic Cover: keep your screen covered, fold it up into a stand for viewing/writing/portrait modes, or remove it for better ergonomics while gamingRugged Protection: rugged shock-resistant polymer provides robust protection against scratches and dropsStable and Adjustable Stand: magnetically locks to 8 different stand positions that stay stable in bed, on the couch, or anywhere elseStand Your Way: raised screen view, portrait mode, and magnetic fridge mounting let you comfortably view and use your iPad in the office, kitchen, and beyondComplete Customer Support: detailed setup videos and FAQs, comprehensive 12-month warranty, lifetime support, and personalized help',
  "INFILAND iPad Mini 6 case (8.3 inch, 2021), 【Ultra-Clear Back & PU Leather Cover】【6 FT Drop Protection】 iPad Mini 6th Generation Case with Pencil Holder Support Wireless Charging -Clear Rose Gold💎【Exclusive Design】This INFILAND case is designed for iPad Mini 6th Generation 8.3 Inch 2021 Released only. Precise Incision, All functions work perfectly.💎【Stylish & Unique】This iPad mini 2021 case back uses exclusive crystal ion-exchange process and high-quality polycarbonate material imported from Germany. This allows it to provide long-lasting ultra-clarity and scratch resistance.And the case is edged with a transparent TPU material in a near iPad color. These designs are perfect for showing off the iPad's own lovely colors and logo.💎【Military-Grade Drop Protection】The case for iPad mini 6 certified military-grade drop test by SGS, and the special shock-resistant polymer provides strong protection. To cope with accidental drops, it also features a patented design equipped with a combined shock-absorbing airbag and upgraded cushion space, making the four corners 300% more shock-resistant.💎【Built-in Pencil holder】We designed a pen slot on the right side of the iPad mini 6 case. It supports Apple Pencil 2 magnetic clamping and wireless charging. No more worry about the pencil get lost easily.💎【Auto Sleep/Wake Feature】Automatically wake up or sleep your device by opening & closing its magnetic cover. Easy operation and energy-saving. We offer free 30 day returns and a 3 year warranty. You can always contact us through Amazon with any problems. We will provide a satisfactory solution.",
  'New iPad 10th Generation 10.9 inch 2022 for Kids Girls, with Tempered Glass Screen Protector&Shoulder Strap|Ambison Heavy Duty Shockproof Rugged 10.9" 10 Gen Cover for Kids Girls Children(Rose Red)🌻【Exclusively designed】 New iPad 10.9 inch - Full Body Protective case for iPad 10th Generation 10.9 Inch 2022(Model number:A2696,A2757,A2777).NOT compatible with any other models.🌻【Comes with 9H Tempered Glass Screen Protector】Support Apple Pencil,Easy Installation,Made of 9H hardness tempered glass, the IPAD 10th screen protector can effectively withstand unwanted scuffs and scratches, reducing damage to the screen for iPad 10th Generation tablet.If your protective film is accidentally damaged in transit, CUSTOMER SERVICE TEAM will provide satisfaction.🌻【Easy Inlstall】Only Premium Soft silicone rubber and hybrid hard PC + front hard PC bumper 2 in 1 design.Military Grade Drop Case protect to your ipad 10th 10.9 from all angles while the kids children are having fun. Shockproof/Drop-proof/Impact resistant/Scratch-proof.🌻【Built in Pencil Holder &Butterfly Stand】iPad 10th Generation 2022 Cases built-in Pencil holder allows you to store and carry your Apple pencil easily.The vivid butterfly stand design frees your hands and makes your iPad unique. Adjust the best angle to watch the video, working and typing.(APPLE Pencil is NOT included!)🌻【Adjustable Shoulder Strap】Adjustable shoulder strap offers much more convenience for carrying your iPad when you are on a business trip or doing outdoor activities. It can be also hung on the car headrest for back-seat passengers’ entertainment.',
  "BMOUO iPad 10th Generation Case, iPad 10.9 Case 2022 with 9H Tempered Glass Screen Protector, 360° Rotatable Kickstand & Hand Strap & Pencil Holder 10th Gen iPad Case for iPad 10th Generation, Black➤【Shockproof iPad 10th Generation Case】Just Compatible with iPad 10th Generation 10.9 inch 2022 (Model: A2696/A2757/A2777). NOT compatible with any other versions of iPad. Please check the model number of your iPad on the back before purchase.➤【9H Tempered Glass Screen Protector】Comes with a 9H hard tempered glass screen protector,made of high quality scratch-resistant 0.33mm premium tempered glass with high sensitivity and transparency that works perfectly with the iPad Pencil. Your iPad 10th Generation will get full coverage and shockproof protection.➤【360° Swivel Stand & Adjustable Hand/Shoulder Strap】❶\xa0Designed with a 360° turntable sturdy kickstand, can provides multiple angles (30°/45°/60°) for easy viewing. ❷Adjustable hand strap, securely and convenient using with one hand when in a meeting or outdoor activities.➌ Comes with an adjustable shoulder strap (length from 32'' to 61''), enough to bear 10th generation ipad, perfect to carry it on car➤【Upgraded 4-Layer Protection】iPad 10th gen case, Features a 4-layer protective structure that provides full body protection against accidental drops, bumps and shocks. All controls to easily access all iPad functions without having to remove the iPad 10th Generation from the case.➤【100% Satisfactory Customer SERVICES】 BMOUO provides you professional services. Free Charge of Product Changing or Refunding after received products within 180 days & 360 days Maintenance for iPad 10th generation case!",
  'Tablet Shoulder Sleeve Bag for 11 inch iPad Pro,10.9 inch iPad Air 4,10.2 in iPad, Tablet Sleeve Carrying Case (10.9inch)【Dimension & Compatible】Internal dimensions:11"x8"x2.5",iPad bag perfectly fit 11" iPad Pro 1st/2nd/3rd generation (2018-2021 Model)/ 10.9" iPad Air 4 /10.5 inch Pad Air/ iPad Pro with Magic/Smart Keyboard Folio or Logitech Slim Folio Pro Case, Microsoft Surface Go 3/2/1; 10.2" iPad, 9.7"11" iPad Pro/ iPad Air/iPad, iPad Mini 5/4/3/2/1 with cover on it, 10.1 Samsung Galaxy Tablet, Fire 7/Fire HD 8/All-new Fire HD 10/Introducing Fire HD 10 Productivity Bundle【Splash-proof & Perfect Protection】The tablet sleeve is made of high-quality polyester external and soft inner lining,which is not only splash-proof but also protect your tablet and accessories from drops, bumps and scratches.【Large Capacity】The large number of inner compartments design can enough iPads, books and daily necessities(mobile phones,umbrella,wallet, passport,etc.).Three external pocket storage accessories(chargers, cables, power bank, USB drives, etc.).【Different Applications】Fashion and Lightweight Design meet all your requirements for daily use at work, business trip, go to school, business meeting or speech etc.【What You Get】11 inch tablet shoulder bag, our worry-free 24-month warranty and friendly customer service.',
  'Bam Bino Space Suit iPad 10th Generation Case for Kids | 10th Gen iPad Case (10th Generation) with Screen Guard, Pencil Holder, Handle, Shoulder Strap [Not for iPad Air 5/4]IT\'S NOT A CASE. IT\'S A SPACE SUIT! 🚀 A very tough protective Apple iPad 10th generation case for kids with screen protector and pencil holder. iPad carrying case with shoulder strap, large handle, 2-angle stand. All details considered.iPAD 10.9 CASE FOR KIDS OF ALL AGES 👨🚀 Shock-proof foam 10.9 inch iPad case. Dedicated cutouts for all iPad 10.9 case kids features, pencil holder. iPad 2022 case\'s screen guard absorbs all impact, and it\'s also night friendly!iPAD 10.9 CASE WITH PENCIL HOLDER ✏ Fits iPad 10.9 inch 10th gen case only. This iPad kids case adjusts to study, play, travel, and exercise modes. Features: Car Play, Drawing Stand, Movie Stand.ORIGINAL CASE DESIGN 🤩 making the best child proof case for iPad 10.9. Safe and protective kids iPad case. Carry with large handle, safety shoulder strap, 2-angle stand.LIFETIME "UNIVERSITY" WARRANTY 🎓 Warranty valid until child graduates. 100% non-toxic. ROHS compliant. No heavy metals, no lead. Eco- friendly 🌱compostable packaging.⚠️ONLY FITS IPAD (10TH GENERATION) models, A2696, A2757, A2777. Double-check your model at the back of your iPad or open Settings, tap General, then tap About. DOESN’T FIT iPAD AIR 5/4',
  "iPhone Charger Cable, Oliomp (Apple MFi Certified) 6ft LED Light Up Visible Lightning Cable iPhone Charging Cord for Apple iPhone 13/13ProMax/13Mini/12/11 Pro Max/XS/XR/X/8/7/6S/6Plus (Blue)LED Charging Cable: The LED light iPhone lightning cable has a fashionable appearance and gorgeous light, LED lighting cycle can help you easily find your devices in dark and makes charging way more convenient and fun. It glows in the dark or and not too bright to interrupt or distract you when driving and sleepingSuperior Material Cable: High purity copper wire features anti oxidation and anti rust, which will keep long-lasting fast charging performance and using LED cold light source, won't be hot, with safety and low-energy. The premium aluminum alloy casing for better heat insulation casing TPE material is different from other TPE, 10000 bending life, it has better feel, better durability and flexibility.Strong Compatibility: Compatible with iPhone 13/12/11 / XS / Max / XR / X / 8 Plus / 8 / 7 Plus / / 7 / 6s Plus / 6s / 6 Plus / 6 / 5s / 5c / 5 / iPad Pro / iPad Air / Air 2 / iPad mini / mini 2 / mini 4 / iPad 4th gen / iPod Touch 5th gen / iPod Touch 5th gen / iPod Nano 7th gen and Beats Pill+Fast Charging & Data Sync: This iPhone Charger cable support fast charging speed up to 2.4 amp and data transmission speed up to 480Mb/s. Lights slows down as the battery getting full.What You Get: We provide this iPhone charger cable with one, allowing for easy storage and carrying.And we have professional technical team, We take care of all quality-related issues after you receive the package.",
  'Uppuppy Case for Apple iPad Air 2/1st Generation & iPad 5th(2017)/6th(2018)/Pro 9.7 inch Composition Notebook Cute Kawaii Book Partten Folio a1474 a1475 a1566 a1673 Cover Unique Cases for Women TeensFULL PROTECTION: Made of premium durable PU leather and soft TPU, it is stain resistant, and easy to clean, The high-definition printing process makes clear pattern and it not fade easily.MAGNETIC CLOUSUR: Built-in magnetic strip, this funda para iPad Air 2/iPad Air 1/iPad 5th gen(2017)/iPad 6th gen(2018) 9.7 inch with the smart funtion of auto sleep/wake, no wasting the power energy and extend your iPad standby time.UNIQUE Design: This iPad folio flip case has a classic cartoon character design, makes your iPad look more vivid and stylish, it is also a good gift for family and friends.ADJUSTABLE ANGLES: The tablet stand of this for iPad 9.7 inch case makes your iPad can stand at two different positions on the table. Provide you comfortable viewing and typing experiences.PRECISE CUTOUTS: This case fits perfectly with all the controls of your iPad Air 2nd/1st/iPad 5th/6th gen, you can access to buttons, speakers, camera easily, no need to take off the case to charge.',